// Added from the supplied Livro base v1.3. Short, original rules summaries.
// Visuals select equipped-agent silhouettes; the 165 original catalog images stay intact.
const slug=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const rows=[];
function add(name,group,category,spaces,summary,page,icon,kind,variant,slot,details=[],source='Livro base'){rows.push({id:slug(`${source}-${group}-${name}`),name,group,category,spaces,summary,source,page:String(page),details,visual:{icon,kind,variant,slot}});}
add('Escudo','Proteções','I',2,'Ocupa uma mão e concede +2 na Defesa.',62,'Proteção pesada','held','shield','weapon', [['Defesa','+2'],['Empunhadura','Uma mão']]);
const op=(n,c,s,d,p,i,k,v,l)=>add(n,'Operacionais',c,s,d,p,i,k,v,l);
op('Arpéu','0',1,'Prender o arpéu exige Pontaria DT 15; subir com a corda concede +5 em Atletismo.',65,'Kit de escalada','belt','belt-pouch','utility');
op('Binóculos','0',1,'Concede +5 em Percepção para observar a grandes distâncias.',65,'Óculos de visão térmica','held','binoculars','weapon');
op('Bloqueador de sinal','I',1,'Impede que celulares em alcance médio se conectem à rede.',65,'Alarme de movimento','pocket','belt-pouch','utility');
op('Corda','0',1,'Rolo de 10 m; concede +5 em Atletismo para descer buracos ou prédios, além de amarrar pessoas inconscientes.',65,'Kit de escalada','belt','belt-pouch','utility');
op('Equipamento de sobrevivência','0',2,'Concede +5 em Sobrevivência para acampar e se orientar, e permite fazer esses testes sem treinamento.',65,'Kit de perícia','belt','belt-pouch','utility');
op('Máscara de gás','0',1,'Concede +10 em Fortitude contra efeitos que dependem de respiração.',65,'Retalho Tenebroso','mask','gas-mask','face');
op('Mochila militar','I',0,'Aumenta a capacidade de carga em 2 espaços. O benefício de várias mochilas não se acumula.',65,'Paraquedas','backpack','backpack','back');
op('Pé de cabra','0',1,'Ferramenta de exploração: +5 nos testes de Força indicados pelo item.',65,'Bastão policial','held','baton','weapon');
op('Pistola sinalizadora','0',1,'Dispara um sinalizador luminoso; também funciona como arma leve de disparo em alcance curto, causando 2d6 de dano de fogo. Vem com 2 cargas.',65,'Pistola de dardos','held','pistol','weapon');
op('Traje hazmat','I',2,'Traje de proteção ambiental: +5 nos testes contra efeitos ambientais e resistência a químico 10.',66,'Traje espacial','suit','hazmat-suit','outfit');
for(const e of ['Conhecimento','Energia','Morte','Sangue']){
 add(`Amarras de ${e}`,'Paranormais','II',1,`Restrição de ${e} contra criaturas vulneráveis ao elemento. Armadilha (ação completa, 2 PE): área de 3x3 m; Reflexos ou fica imóvel até o fim da cena. Laçar (ação padrão, 1 PE): alcance curto; Vontade ou fica paralisado até seu próximo turno, sustentando por 1 PE/rodada.`,66,'Algemas','belt','belt-cuffs','utility');
 add(`Componentes ritualísticos de ${e}`,'Paranormais','0',1,`Conjunto de componentes para conjurar rituais de ${e}.`,66,'Agrupador ritualístico','held','component-holder','weapon');
 add(`Scanner de manifestação paranormal de ${e}`,'Paranormais','II',1,`Ativar é uma ação padrão; enquanto ativo, consome 1 PE por rodada e revela a direção de manifestações de ${e} (rituais, criaturas, itens amaldiçoados) em alcance longo.`,67,'Catalisador perturbador','held','arcane-device','weapon');
}
add('Câmera de aura paranormal','Paranormais','II',1,'Ação padrão e 1 PE: tira uma foto instantânea que revela auras paranormais em pessoas e objetos, na cor do elemento associado.',66,'Câmera Obscura','held','camera','weapon');
add('Emissor de pulsos paranormais','Paranormais','II',1,'Ação completa e 1 PE: emite um pulso de um elemento à escolha, atraindo criaturas desse elemento e afastando as do elemento oposto; Vontade evita.',66,'Catalisador ampliador','held','arcane-device','weapon');
add('Escuta de ruídos paranormais','Paranormais','II',1,'Ação completa e 2 PE: grava ruídos paranormais por até 24 horas; ouvir a gravação concede +5 em Ocultismo para identificar a criatura.',66,'Rádio Chiador','held','radio','weapon');
add('Medidor de estabilidade da membrana','Paranormais','II',1,'Um agente treinado em Ocultismo pode usá-lo para avaliar o estado da Membrana numa área, indicando a chance de uma manifestação; não é uma resposta definitiva.',67,'Catalisador perturbador','held','arcane-device','weapon');
const special=(n,d,p,i,k,v,l,c='II')=>add(n,'Paranormais',c,1,d,p,i,k,v,l);
special('Coroa de Espinhos','Reação: transforma um dano mental que sofreria em dano de Sangue; enquanto vestida, você não recupera Sanidade por descanso. Exige uma semana de uso contínuo para ativar.',148,'Arreio Neural','headband','neural-headband','head');
special('Frasco de Vitalidade','1 minuto e até 20 de dano próprio enchem o frasco; ação padrão para beber e recuperar essa quantidade de PV, testando Fortitude DT 20 ou ficando enjoado por 1 rodada.',148,'Frasco de lodo','held','bottle','weapon');
special('Pérola de Sangue','Ação de movimento para absorvê-la: +5 em Agilidade, Força e Vigor (e testes desses atributos) até o fim da cena. Ao final, Fortitude DT 20 ou fica fatigado; falha por 5+ causa parada cardíaca (morrendo).',148,'Amuleto sagrado','necklace','element-pendant','neck');
special('Punhos Enraivecidos','Ataques desarmados causam +1d8 de dano de Sangue letal; a cada acerto desarmado, pode pagar PE crescente (2, depois +2 por ataque já feito no turno) para atacar de novo.',148,'Soqueira','gauntlets','colossus-gloves','arms');
special('Seringa de Transfiguração','Ação padrão para sugar sangue de um alvo adjacente (ataque se involuntário); outra ação padrão injeta em alguém, transfigurando sua aparência para a do doador por 1 dia (como Distorcer Aparência). Ao acabar, 1 em 1d6 causa dano de 1 PV permanente.',148,'Injeção de Lodo','held','injector','weapon');
special('Amarras Mortais','Ação padrão e 2 PE: manobra agarrar com +10 contra um alvo Grande ou menor em alcance curto; ação de movimento puxa um alvo agarrado para adjacente.',148,'Braçadeira reforçada','wrist','bracer','arms');
special('Casaco de Lodo','Concede resistência a corte, impacto, Morte e perfuração 5, mas aplica vulnerabilidade a dano balístico e de Energia.',149,'Vestimenta','garment','garment','outfit');
special('Coletora','Ação completa para apunhalar alguém morrendo: mata o alvo e armazena 1d8 PE (máx. 20), utilizáveis como seus após uma semana de posse; portar a adaga piora o descanso com pesadelos.',149,'A Primeira Adaga','held','knife','weapon');
special('Vislumbre do Fim','Ação de movimento para se concentrar num ser visto e obter informações sobre a morte dele: um contador de tempo (pessoas comuns) ou o pior valor de resistência e vulnerabilidades (Marcados/criaturas).',149,'Óculos escuros','glasses','sunglasses','eyes');
special('Anéis do Elo Mental','Usados por duas pessoas por 24h, ligam-nas como o ritual Invadir Mente (ligação telepática); testes de Vontade usam o melhor entre as duas, mas dano mental e condições mentais/de medo afetam ambas.',149,'Amuleto sagrado','wrist','knuckles','arms');
special('Lanterna Reveladora','Ação padrão e 1 PE ligam a lanterna por uma cena, replicando o ritual Terceiro Olho; criaturas de Sangue iluminadas por ela priorizam atacar você.',149,'Lanterna','held','flashlight','weapon');
special('Máscara das Pessoas nas Sombras','Concede resistência a Conhecimento 10; ação de movimento e 2 PE teletransportam você entre sombras vistas em alcance médio.',149,'Retalho Tenebroso','mask','cloth-mask','face');
special('Munição Jurada','Um ritual de 1 hora vincula a bala a um ser conhecido: contra ele, +10 no teste de ataque, dobra a margem de ameaça e +6d12 de dano de Conhecimento; enquanto a possuir, -2 na Defesa e em ataques contra outros alvos.',150,'Balas pesadas','pocket','belt-pouch','ammo');
special('Arcabuz dos Moretti','Arma simples de fogo, uma mão, +2 em testes de ataque, dano de Energia, alcance curto, crítico x3, sem munição; ao disparar, role 1d6 para o dado de dano: 1) 2d4, 2) 2d6, 3) 2d8, 4) 2d10, 5) 2d12, 6) 2d20.',150,'Fuzil Alheio','held','rifle','weapon');
special('Bateria Reversa','Ação padrão e 2 PE descarregam um dispositivo eletrônico em alcance curto; se cheia, outra ação padrão recarrega um aparelho descarregado. Testa Ocultismo DT 15 (+5 por uso no dia); falha faz explodir, 12d6 de dano de Energia a 3 m.',150,'Bateria potente','pocket','belt-pouch','utility');
special('Peitoral da Segunda Chance','Ao chegar a 0 PV, gasta 5 PE seus automaticamente para reanimar com 4d10 PV (falha se não houver PE); 1 em 1d10 de matar instantaneamente com a descarga.',150,'Proteção leve','vest','light-armor','armor');
special('Relógio de Arnaldo','Uma vez por rodada, 1 PE permite rolar de novo qualquer dado com resultado 1; o custo sobe +1 a cada ativação no mesmo dia. Item único.',150,'Aplicador de medicamentos','wrist','wrist-device','arms');
special('Talismã da Sorte','Ao sofrer dano, reação e 3 PE rolam 1d4: 2-3 evita o dano; 4 evita o dano mas o talismã se desfaz; 1 dobra o dano sofrido e o talismã se desfaz.',150,'Amuleto sagrado','necklace','amulet','neck');
special('Teclado de Conexão Neural','Ao plugar num computador (ação de movimento), usa-o sem barreira tecnológica/idioma, +10 em testes para invadir sistemas e metade do tempo para localizar arquivos; sofre 1d6 de dano mental por rodada de uso.',150,'Notebook','held','laptop','weapon');
special('Tela do Pesadelo','Ação padrão e 2 PE ativam a tela; quem a tocar testa Vontade (DT do usuário +5) ou fica atordoado e sofre 4d6 de dano mental por rodada até passar no teste ou enlouquecer. Fica inerte após o efeito.',151,'Celular','held','phone','weapon');
special('Veículo Energizado','O veículo não precisa de combustível; o motorista pode gastar reação e Pilotagem DT 25 para atravessar um objeto como incorpóreo por um instante.',151,'Ligação direta infernal','vehicle','inventory','vehicle');
special('Jaqueta de Veríssimo','Resistência a dano paranormal 15; reação e 2 PE tornam você o alvo de um dano que atingiria um aliado adjacente. Item único de categoria IV.',151,'Vestimenta','garment','garment','outfit','IV');
special('Dedo Decepado','Concede um poder paranormal do antigo dono (define o elemento da maldição). Ao dormir/relaxar, 1 em 1d4 impede recuperar PV/PE/Sanidade; -10 em Diplomacia se visto com o item. Exige uma semana de uso para ativar.',151,'Amuleto sagrado','necklace','amulet','neck');
// Arquivos Secretos #4 — reuses existing sprites and agent-variant states, same as the Livro base additions above.
add('Granada de Gás Lacrimogêneo','Explosivos','I',1,'Consumível de raio de 6 m: 4d6 de dano químico, enjoado e dificuldade respiratória. Fortitude reduz o dano à metade e evita enjoado. Fora da área, a dificuldade respiratória dura 1d4 rodadas.',70,'Granada de fumaça','belt','belt-grenade','utility',[],'Arquivos Secretos #4');
add('Granada de Tinta','Explosivos','0',1,'Consumível de raio de 6 m: deixa os alvos vulneráveis e aplica −2d20 em Furtividade pela cena; Reflexos evita.',70,'Granada de atordoamento','belt','belt-grenade','utility',[],'Arquivos Secretos #4');
add('Granada Ctrl+C Ctrl+V','Explosivos','II',1,'Granada amaldiçoada de Energia: alcance médio, raio de 6 m, 8d6 de dano de Energia; Reflexos reduz à metade. Após cada explosão, 1d4 par cria outra granada dentro da área anterior, até quatro explosões no total.',70,'Granada de PEM','belt','belt-grenade','utility',[['Elemento','Energia']],'Arquivos Secretos #4');
add('Lançador de Granadas','Armas','II',2,'Arma pesada de duas mãos e alcance longo que comporta seis granadas 40 mm; recarregar uma custa ação de movimento. Um acerto direto nega a resistência apenas do alvo atingido; disparar num ponto dispensa o ataque e todos os alvos resistem. Granadas de arremesso não são compatíveis.',71,'Bazuca','held','launcher','weapon',[],'Arquivos Secretos #4');
// Arquivos Secretos #5 — reuses existing sprites, same pattern as AS4 above.
add('Câmera Filmadora','Operacionais','0',1,'Fornece +2 em testes de Investigação e Percepção; também funciona como lanterna (cone de 9 m) ou em modo de visão noturna, como Visão no Escuro.',60,'Câmera Obscura','held','camera','weapon',[],'Arquivos Secretos #5');
add('Faixas da Vidência','Paranormais','III',1,'Vestimenta que concede +5 na Defesa e em testes de resistência contra ataques e habilidades originados em alcance curto de você, mas -5 contra os originados a mais de 9 m; também concede +2 em Intimidação.',60,'Vestimenta','garment','garment','outfit',[['Elemento','Morte']],'Arquivos Secretos #5');
add('Joias da Mente','Paranormais','III',1,'Vestimenta (um piercing e um brinco, que só funcionam usados juntos) que concede +2 em Diplomacia e resistência a dano mental 10.',60,'Amuleto sagrado','necklace','amulet','neck',[['Elemento','Conhecimento']],'Arquivos Secretos #5');
add('Larva da Fúria','Paranormais','II',1,'Ação de movimento para ingerir e consumir o item: até o fim da cena, recebe +4 em testes de ataque e rolagens de dano corpo a corpo, mas não pode fazer nada que exija calma e concentração (como usar Furtividade ou conjurar rituais). A fúria termina se você terminar uma rodada sem atacar nem ser alvo de um efeito hostil.',61,'Frasco de lodo','held','bottle','weapon',[['Elemento','Sangue']],'Arquivos Secretos #5');
add('Skate Caótico','Paranormais','II',2,'Usado nos pés por quem for treinado em Acrobacia, Atletismo ou Pilotagem, concede +3 m de deslocamento. Como arma improvisada corpo a corpo de duas mãos, causa 1d12 de dano de impacto (crítico x2). Como escudo, concede +5 na Defesa. Para modificações e maldições, é tratado como uma proteção.',61,'Bastão policial','held','baton','weapon',[['Elemento','Energia']],'Arquivos Secretos #5');
add('Tênis Lépidos','Paranormais','III',1,'Vestimenta que concede +12 em Atletismo e +3 m de deslocamento. Por 2 PE, até o fim do turno ignora terreno difícil, recebe deslocamento de escalada igual ao terrestre e fica imune a dano de queda de até 9 m.',61,'Pé de morto','boots','dead-boots','feet',[['Elemento','Energia']],'Arquivos Secretos #5');
// Arquivos Secretos #7 — reuses existing sprites, same pattern as AS4/AS5 above.
add('Carranca Caçadora','Paranormais','II',2,'Ao colocar na boca um material ligado a uma criatura paranormal (roupa rasgada, pelo sujo de Lodo etc.), seus olhos apontam por 10 minutos o caminho mais perigoso até ela ou até o último lugar em que esteve. Depois disso consome o material e não guia mais até essa criatura (mas pode ser reutilizada para outras).',78,'Crânio espiral','held','skull-charm','weapon',[],'Arquivos Secretos #7');
add('Cajado da Cruz de Sangue','Paranormais','III',2,'Arma simples corpo a corpo de duas mãos e ágil (permite Combater com Duas Armas como se fosse uma arma de uma mão e uma leve). Empunhada por um ocultista que conheça ao menos um ritual de Sangue, reduz o custo de rituais e poderes de Sangue em 1 PE, aumenta a DT deles em +1 e o dano em +1 dado do mesmo tipo.',78,'Cajado','held','staff','weapon',[['Dano','1d12 corte'],['Crítico','20/x2'],['Elemento','Sangue']],'Arquivos Secretos #7');
add('Pé de Coelho','Paranormais','I',1,'Vestimenta. Uma vez por cena, gasta uma ação de movimento para ativá-la: até o fim da cena, recebe +1d4 em todos os testes, mas se o resultado do d4 for ímpar, sofre um acidente e perde 1d4 PV.',79,'Amuleto sagrado','necklace','amulet','neck',[],'Arquivos Secretos #7');
add('Sal Dourado','Paranormais','I',1,'Formado em linha numa porta ou janela (3 usos esvaziam o saleiro) ou em círculo (1 uso), barra a passagem de criaturas de Sangue com VD 80 ou menos: Vontade DT 20 ou a criatura fica frustrada até o fim da cena e não consegue atravessar; se passar, também fica frustrada mas consegue atravessar.',79,'Kit de perícia','belt','belt-pouch','utility',[['Elemento','Sangue']],'Arquivos Secretos #7');
add('Terço Maculado','Paranormais','II',1,'Vestimenta amaldiçoada: ao vesti-la, herda uma súplica reprimida definida pelo mestre; agir a favor dela concede +2d10 no teste envolvido. Não pode ser removido enquanto vivo (tentar falha automaticamente e causa 2d10 de dano) e agir contra a súplica também pode causar 2d10 de dano, a critério do mestre. Só é removido se decepado ou se a súplica for cumprida, virando um item mundano.',79,'Amuleto sagrado','necklace','amulet','neck',[['Elemento','Sangue']],'Arquivos Secretos #7');
// Arquivos Secretos #6 (v1.1) — reuses existing sprites, same pattern as AS4/AS5/AS7 above.
add('Anel Invertido','Paranormais','II',0.5,'Enquanto estiver usando o anel, ao sofrer dano causado por um nidere, pode gastar uma reação e 2 PE para receber RD 4d10 contra esse dano.',73,'Amuleto sagrado','necklace','amulet','neck',[['Elemento','Morte']],'Arquivos Secretos #6');
add('Aplicador de Adrenalina','Operacionais','I',1,'Ação padrão para injetar a epinefrina em você ou num ser adjacente: concede 2d8+2 PV temporários, +3 m de deslocamento e +2 em testes baseados em Força, Agilidade e Vigor até o fim da cena. Quando o efeito acaba, o alvo sofre rebote e fica fatigado por uma cena. Conta como um medicamento.',73,'Aplicador de medicamentos','wrist','wrist-device','arms',[],'Arquivos Secretos #6');
add('Lança-nitrogênio','Armas','III',2,'Arma de fogo pesada de duas mãos e alcance curto que atinge todos os seres numa linha de 1,5 m de largura com um único teste de ataque comparado à Defesa de cada um. Além do dano, os atingidos ficam enredados pelo congelamento até gastarem uma ação padrão para quebrar o gelo (Fortitude DT AGI muda a condição para lento). Usa combustível como munição, igual a um lança-chamas.',73,'Lança-chamas','held','flamethrower','weapon',[['Proficiência','Pesada'],['Empunhadura','Duas mãos'],['Dano','6d6 frio'],['Crítico','20/x2'],['Alcance','Curto']],'Arquivos Secretos #6');
export const ADDITIONAL_ITEMS=Object.freeze(rows);
export const ITEM_NAME_ALIASES=Object.freeze({'Marreta':['Maça'],'Moto-serra':['Motosserra'],'Balas pesadas':['Balas longas'],'Lanterna':['Lanterna tática']});
