export const PATENTS = [
  "Recruta",
  "Operador",
  "Agente Especial",
  "Oficial de Operações",
  "Agente de Elite",
];

export const SKILL_ATTRIBUTES = {
  Acrobacia: "AGI",
  Adestramento: "PRE",
  Artes: "PRE",
  Atletismo: "FOR",
  Atualidades: "INT",
  Ciências: "INT",
  Crime: "AGI",
  Diplomacia: "PRE",
  Enganação: "PRE",
  Fortitude: "VIG",
  Furtividade: "AGI",
  Iniciativa: "AGI",
  Intimidação: "PRE",
  Intuição: "PRE",
  Investigação: "INT",
  Luta: "FOR",
  Medicina: "INT",
  Ocultismo: "INT",
  Percepção: "PRE",
  Pilotagem: "AGI",
  Pontaria: "AGI",
  Profissão: "INT",
  Reflexos: "AGI",
  Religião: "PRE",
  Sobrevivência: "INT",
  Tática: "INT",
  Tecnologia: "INT",
  Vontade: "PRE",
};

const slug = (value) =>
  String(value)
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");

const ability = ({ name, category, group, summary, cost = "Passivo", requirement = "Nenhum", unlockNex = 0, unlockStage = 0, source = "Livro base", page = "", details = [], key = "" }) => ({
  id: slug(`${category}-${group}-${name}${key ? `-${key}` : ""}`),
  name,
  category,
  group,
  summary,
  cost,
  requirement,
  unlockNex,
  unlockStage,
  source,
  page,
  details,
});

export const CORE_CLASS_ABILITIES = [
  ability({ name: "Empenho", category: "Sobrevivente", group: "Habilidades de classe", summary: "Depois de fazer um teste de perícia, gaste 1 PE para receber +2 no resultado.", cost: "1 PE", requirement: "Classe Sobrevivente", unlockStage: 1, source: "Sobrevivendo ao Horror", page: "31" }),
  ability({ name: "Treinamento Especial", category: "Sobrevivente", group: "Habilidades de classe", summary: "Quando a história permitir, o próximo avanço pode converter o sobrevivente em Combatente, Especialista ou Ocultista de NEX 5%, mantendo as habilidades já recebidas e aplicando os ajustes da classe escolhida.", cost: "Narrativo", requirement: "Autorização do mestre", unlockStage: 1, source: "Sobrevivendo ao Horror", page: "32", details: ["Combatente: +8 PV, duas escolhas de perícia, armas táticas, proteções leves e Ataque Especial.", "Especialista: +4 PV, +1 PE, +4 SAN, seis perícias, proteções leves, Eclético e Perito.", "Ocultista: +2 PE, +8 SAN, Ocultismo, Vontade, duas perícias e Escolhido pelo Outro Lado."] }),
  ability({ name: "Cicatrizado", category: "Sobrevivente", group: "Habilidades de classe", summary: "Escolha um perigo paranormal ligado a um elemento. Uma vez por sessão, use uma reação e reduza permanentemente 1 ponto de um recurso máximo para ignorar um dano mental ou gasto de PE, ou reduzir um dano físico à metade.", cost: "1 vez por sessão", requirement: "Sobrevivente · Estágio 5", unlockStage: 5, source: "Sobrevivendo ao Horror", page: "31", details: ["A escolha do perigo e do elemento fica registrada na ficha.", "O teste de resistência contra o perigo escolhido sofre a penalidade indicada pela regra."] }),
  ability({ name: "Ataque Especial", category: "Combatente", group: "Habilidades de classe", summary: "Gaste PE ao atacar para aumentar o teste, o dano ou os dois, respeitando o limite disponível no NEX.", cost: "2 a 5 PE", requirement: "Classe Combatente", unlockNex: 5 }),
  ability({ name: "Eclético", category: "Especialista", group: "Habilidades de classe", summary: "Permite receber temporariamente os benefícios de treinamento em uma perícia usada no teste.", cost: "2 PE", requirement: "Classe Especialista", unlockNex: 5 }),
  ability({ name: "Perito", category: "Especialista", group: "Habilidades de classe", summary: "Escolha duas perícias treinadas, exceto Luta e Pontaria, para acrescentar um dado de bônus ao gastar PE.", cost: "2 a 5 PE", requirement: "Classe Especialista", unlockNex: 5 }),
  ability({ name: "Escolhido pelo Outro Lado", category: "Ocultista", group: "Habilidades de classe", summary: "Concede os primeiros rituais e libera círculos superiores conforme o NEX do ocultista.", cost: "Conforme o ritual", requirement: "Classe Ocultista", unlockNex: 5 }),
];

export const CLASS_POWERS = [
  // Combatente — livro base
  ability({ name: "Acuidade com Arma", category: "Combatente", group: "Poderes de Combatente", summary: "Permite usar Agilidade no ataque e no dano com armas leves corpo a corpo ou de arremesso.", requirement: "AGI 2", unlockNex: 15 }),
  ability({ name: "Armamento Pesado", category: "Combatente", group: "Poderes de Combatente", summary: "Concede proficiência com armas pesadas e permite operá-las sem a penalidade de falta de proficiência.", unlockNex: 15 }),
  ability({ name: "Ataque de Oportunidade", category: "Combatente", group: "Poderes de Combatente", summary: "Permite reagir com um ataque corpo a corpo quando um alvo adjacente se afasta de forma descuidada.", cost: "1 PE", unlockNex: 15 }),
  ability({ name: "Combater com Duas Armas", category: "Combatente", group: "Poderes de Combatente", summary: "Ao atacar com duas armas adequadas, permite um ataque com cada uma, aplicando a penalidade prevista.", requirement: "AGI 3 e treinado em Luta ou Pontaria", unlockNex: 15 }),
  ability({ name: "Combate Defensivo", category: "Combatente", group: "Poderes de Combatente", summary: "Troca precisão ofensiva por Defesa até o próximo turno quando você realiza uma ação de ataque.", requirement: "INT 2", unlockNex: 15 }),
  ability({ name: "Golpe Demolidor", category: "Combatente", group: "Poderes de Combatente", summary: "Aprimora ataques contra objetos e manobras de quebrar com dados adicionais de dano.", cost: "1 PE", requirement: "FOR 2 e treinado em Luta", unlockNex: 15 }),
  ability({ name: "Golpe Pesado", category: "Combatente", group: "Poderes de Combatente", summary: "Aumenta em um passo o dano de armas corpo a corpo empunhadas por você.", requirement: "FOR 2", unlockNex: 15 }),
  ability({ name: "Incansável", category: "Combatente", group: "Poderes de Combatente", summary: "Uma vez por cena, concede uma ação extra de investigação baseada em Força ou Agilidade.", cost: "2 PE", unlockNex: 15 }),
  ability({ name: "Presteza Atlética", category: "Combatente", group: "Poderes de Combatente", summary: "Ao facilitar uma investigação, permite usar Força ou Agilidade e reforçar o bônus dado a um aliado.", cost: "1 PE", unlockNex: 15 }),
  ability({ name: "Proteção Pesada", category: "Combatente", group: "Poderes de Combatente", summary: "Concede proficiência com proteções pesadas.", requirement: "NEX 30%", unlockNex: 30 }),
  ability({ name: "Reflexos Defensivos", category: "Combatente", group: "Poderes de Combatente", summary: "Aumenta Defesa e testes de resistência contra inimigos em alcance curto.", requirement: "AGI 2", unlockNex: 15 }),
  ability({ name: "Saque Rápido", category: "Combatente", group: "Poderes de Combatente", summary: "Permite sacar ou guardar itens livremente e reduz o tempo necessário para recarregar armas.", requirement: "Treinado em Iniciativa", unlockNex: 15 }),
  ability({ name: "Segurar o Gatilho", category: "Combatente", group: "Poderes de Combatente", summary: "Após acertar com arma de fogo, permite repetir ataques contra o mesmo alvo pagando um custo crescente.", cost: "1 PE ou mais", requirement: "NEX 60%", unlockNex: 60 }),
  ability({ name: "Sentido Tático", category: "Combatente", group: "Poderes de Combatente", summary: "Analisa o ambiente para aumentar Defesa e testes de resistência até o fim da cena.", cost: "2 PE e ação de movimento", requirement: "Treinado em Percepção e Tática", unlockNex: 15 }),
  ability({ name: "Tanque de Guerra", category: "Combatente", group: "Poderes de Combatente", summary: "Melhora a Defesa e a resistência concedidas por uma proteção pesada equipada.", requirement: "Proteção Pesada e NEX 30%", unlockNex: 30 }),
  ability({ name: "Tiro Certeiro", category: "Combatente", group: "Poderes de Combatente", summary: "Soma Agilidade ao dano com armas de disparo e evita a penalidade por alvo em combate corpo a corpo.", requirement: "Treinado em Pontaria", unlockNex: 15 }),
  ability({ name: "Tiro de Cobertura", category: "Combatente", group: "Poderes de Combatente", summary: "Faz um disparo de pressão que pode prender um alvo no lugar e reduzir seus ataques por uma rodada.", cost: "1 PE e ação padrão", unlockNex: 15 }),
  ability({ name: "Transcender", category: "Combatente", group: "Poderes de Combatente", summary: "Permite escolher um poder paranormal, aplicando os custos e pré-requisitos correspondentes.", cost: "Conforme o poder", unlockNex: 15 }),
  ability({ name: "Treinamento em Perícia", category: "Combatente", group: "Poderes de Combatente", summary: "Eleva o treinamento de duas perícias; pode ser escolhido novamente em avanços futuros.", unlockNex: 15 }),

  // Especialista — livro base
  ability({ name: "Acuidade com Arma", category: "Especialista", group: "Poderes de Especialista", summary: "Permite usar Agilidade no ataque e no dano com armas leves corpo a corpo ou de arremesso.", requirement: "AGI 2", unlockNex: 15 }),
  ability({ name: "Balística Avançada", category: "Especialista", group: "Poderes de Especialista", summary: "Concede proficiência com armas táticas de fogo e melhora o dano causado com elas.", unlockNex: 15 }),
  ability({ name: "Conhecimento Aplicado", category: "Especialista", group: "Poderes de Especialista", summary: "Em testes que não sejam Luta ou Pontaria, permite trocar o atributo-base por Intelecto.", cost: "2 PE", requirement: "INT 2", unlockNex: 15 }),
  ability({ name: "Hacker", category: "Especialista", group: "Poderes de Especialista", summary: "Melhora testes de Tecnologia para invadir sistemas e reduz o tempo das invasões.", requirement: "Treinado em Tecnologia", unlockNex: 15 }),
  ability({ name: "Mãos Rápidas", category: "Especialista", group: "Poderes de Especialista", summary: "Permite executar certas ações de Crime como ação livre.", cost: "1 PE", requirement: "AGI 3 e treinado em Crime", unlockNex: 15 }),
  ability({ name: "Mochila de Utilidades", category: "Especialista", group: "Poderes de Especialista", summary: "Reduz a categoria e o espaço ocupado por um kit de perícia escolhido.", unlockNex: 15 }),
  ability({ name: "Movimento Tático", category: "Especialista", group: "Poderes de Especialista", summary: "Ignora terreno difícil e concede deslocamento de escalada durante o turno.", cost: "1 PE", requirement: "Treinado em Atletismo", unlockNex: 15 }),
  ability({ name: "Na Trilha Certa", category: "Especialista", group: "Poderes de Especialista", summary: "Sucessos ao procurar pistas podem gerar dados extras cumulativos para o próximo teste da investigação.", cost: "1 PE ou mais", unlockNex: 15 }),
  ability({ name: "Nerd", category: "Especialista", group: "Poderes de Especialista", summary: "Um teste de Atualidades pode revelar uma informação útil para a cena.", cost: "2 PE", unlockNex: 15 }),
  ability({ name: "Ninja Urbano", category: "Especialista", group: "Poderes de Especialista", summary: "Concede proficiência com armas táticas corpo a corpo e melhora o dano com elas.", unlockNex: 15 }),
  ability({ name: "Pensamento Ágil", category: "Especialista", group: "Poderes de Especialista", summary: "Durante investigação, permite realizar uma ação extra para procurar pistas.", cost: "2 PE", unlockNex: 15 }),
  ability({ name: "Perito em Explosivos", category: "Especialista", group: "Poderes de Especialista", summary: "Aumenta a DT dos seus explosivos e permite excluir aliados da área afetada.", unlockNex: 15 }),
  ability({ name: "Primeira Impressão", category: "Especialista", group: "Poderes de Especialista", summary: "Concede dados extras ao primeiro teste social ou de leitura de pessoa em cada cena.", unlockNex: 15 }),
  ability({ name: "Transcender", category: "Especialista", group: "Poderes de Especialista", summary: "Permite escolher um poder paranormal, aplicando os custos e pré-requisitos correspondentes.", cost: "Conforme o poder", unlockNex: 15 }),
  ability({ name: "Treinamento em Perícia", category: "Especialista", group: "Poderes de Especialista", summary: "Eleva o treinamento de duas perícias; pode ser escolhido novamente em avanços futuros.", unlockNex: 15 }),

  // Ocultista — livro base
  ability({ name: "Camuflar Ocultismo", category: "Ocultista", group: "Poderes de Ocultista", summary: "Oculta componentes e manifestações da conjuração, dificultando reconhecer que você lançou um ritual.", cost: "2 PE", unlockNex: 15 }),
  ability({ name: "Envolto em Mistério", category: "Ocultista", group: "Poderes de Ocultista", summary: "Melhora Enganação e Intimidação contra pessoas sem treinamento em Ocultismo.", unlockNex: 15 }),
  ability({ name: "Especialista em Elemento", category: "Ocultista", group: "Poderes de Ocultista", summary: "Escolha um elemento; a DT para resistir aos seus rituais desse elemento aumenta.", unlockNex: 15 }),
  ability({ name: "Ferramentas Paranormais", category: "Ocultista", group: "Poderes de Ocultista", summary: "Uma vez por cena, ativa um equipamento paranormal sem o custo inicial da ativação.", cost: "1 vez por cena", unlockNex: 15 }),
  ability({ name: "Fluxo de Poder", category: "Ocultista", group: "Poderes de Ocultista", summary: "Permite sustentar dois efeitos de ritual ao mesmo tempo, pagando cada manutenção.", cost: "Conforme os rituais", requirement: "NEX 60%", unlockNex: 60 }),
  ability({ name: "Guiado pelo Paranormal", category: "Ocultista", group: "Poderes de Ocultista", summary: "Concede uma ação adicional de investigação uma vez por cena.", cost: "2 PE", unlockNex: 15 }),
  ability({ name: "Identificação Paranormal", category: "Ocultista", group: "Poderes de Ocultista", summary: "Concede grande bônus em Ocultismo para identificar criaturas, objetos e rituais.", unlockNex: 15 }),
  ability({ name: "Intuição Paranormal", category: "Ocultista", group: "Poderes de Ocultista", summary: "Ao facilitar uma investigação, soma Intelecto ou Presença ao teste.", unlockNex: 15 }),
  ability({ name: "Mestre em Elemento", category: "Ocultista", group: "Poderes de Ocultista", summary: "Reduz o custo dos rituais de um elemento já escolhido em Especialista em Elemento.", requirement: "Especialista em Elemento e NEX 45%", unlockNex: 45 }),
  ability({ name: "Ritual Potente", category: "Ocultista", group: "Poderes de Ocultista", summary: "Soma Intelecto ao dano ou à recuperação de seus rituais.", requirement: "INT 1", unlockNex: 15 }),
  ability({ name: "Ritual Predileto", category: "Ocultista", group: "Poderes de Ocultista", summary: "Escolha um ritual conhecido e reduza seu custo de conjuração.", unlockNex: 15 }),
  ability({ name: "Tatuagem Ritualística", category: "Ocultista", group: "Poderes de Ocultista", summary: "Reduz o custo de rituais pessoais que tenham você como alvo.", unlockNex: 15 }),
  ability({ name: "Transcender", category: "Ocultista", group: "Poderes de Ocultista", summary: "Permite escolher um poder paranormal, aplicando os custos e pré-requisitos correspondentes.", cost: "Conforme o poder", unlockNex: 15 }),
  ability({ name: "Treinamento em Perícia", category: "Ocultista", group: "Poderes de Ocultista", summary: "Eleva o treinamento de duas perícias; pode ser escolhido novamente em avanços futuros.", unlockNex: 15 }),

  // Sobrevivendo ao Horror — poderes adicionais
  ...[
    ["Instinto de Fuga", "Ajuda a escapar e reposicionar-se quando a situação fica perigosa.", "Conforme o uso"],
    ["Apego Angustiado", "Transforma um vínculo importante em motivação para resistir ou agir.", "Conforme o uso"],
    ["Caminho para Forca", "Ao se sacrificar para atrasar uma ameaça, amplia a ajuda concedida aos aliados.", "1 PE"],
    ["Ciente das Cicatrizes", "Permite usar Luta ou Pontaria para analisar pistas ligadas a armas e ferimentos.", "Passivo"],
    ["Correria Desesperada", "Aumenta deslocamento e melhora testes para fugir em perseguições.", "Passivo"],
    ["Engolir o Choro", "Ignora penalidades de condições ao fugir ou agir furtivamente.", "Passivo"],
    ["Paranoia Defensiva", "Concede proteção adicional quando você se prepara para uma ameaça.", "Passivo"],
    ["Sacrificar os Joelhos", "Permite um esforço brusco de movimento com uma consequência temporária.", "Conforme o uso"],
    ["Sem Tempo, Irmão", "Acelera uma ação em um momento crítico.", "Conforme o uso"],
    ["Valentão", "Melhora ações de pressão física e intimidação.", "Passivo"],
    ["Mochileiro", "Aumenta sua capacidade de transportar equipamento útil.", "Passivo"],
  ].map(([name, summary, cost]) => ability({ name, category: "Combatente", group: "Poderes de Combatente", summary, cost, unlockNex: 15, source: "Sobrevivendo ao Horror" })),
  ...[
    ["Acolher o Terror", "Permite entregar-se ao medo uma vez adicional por sessão."],
    ["Especialista Diletante", "Permite aproveitar uma técnica de outra área de especialista."],
    ["Flashback", "Declara uma preparação anterior plausível para ajudar na cena atual."],
    ["Contatos Oportunos", "Aciona uma conexão útil para obter ajuda ou informação."],
    ["Mãos Firmes", "Reduz interferências ao executar tarefas delicadas sob pressão."],
    ["Disfarce Sutil", "Melhora a criação e manutenção de identidades discretas."],
    ["Esconderijo Desesperado", "Facilita mover-se sem revelar a posição e reduz a visibilidade ao esconder-se."],
    ["Leitura Fria", "Observa uma pessoa para descobrir detalhes ou converter a incerteza em PE temporários."],
    ["Plano de Fuga", "Prepara uma rota ou recurso para sair de uma situação complicada."],
    ["Remoer Memórias", "Substitui um teste de Intelecto ou Presença por uma verificação mental fixa."],
    ["Resistir à Pressão", "Estende uma investigação por uma rodada e melhora os testes do grupo nessa rodada."],
  ].map(([name, summary]) => ability({ name, category: "Especialista", group: "Poderes de Especialista", summary, cost: "Conforme o uso", unlockNex: 15, source: "Sobrevivendo ao Horror" })),
  ...[
    ["Nos Olhos do Monstro", "Ajuda a interpretar criaturas e manifestações paranormais."],
    ["Olhar Sinistro", "Usa a presença paranormal para pressionar um alvo."],
    ["Deixe os Sussurros Guiarem", "Permite buscar orientação do Outro Lado durante uma investigação."],
    ["Domínio Esotérico", "Amplia o controle sobre instrumentos e práticas ocultistas."],
    ["Estalos Macabros", "Produz um efeito paranormal breve para distrair ou perturbar."],
    ["Minha Dor me Impulsiona", "Quando já está ferido, usa esforço para melhorar testes físicos de mobilidade."],
    ["Sentido Premonitório", "Antecipa acontecimentos imediatos de investigação, furtividade ou perseguição."],
    ["Sincronia Paranormal", "Cria uma ligação sustentada que distribui dados de bônus entre aliados ligados."],
    ["Traçado Conjuratório", "Prepara um símbolo no chão que fortalece conjuração e resistência dentro da área."],
  ].map(([name, summary]) => ability({ name, category: "Ocultista", group: "Poderes de Ocultista", summary, cost: "Conforme o uso", unlockNex: 15, source: "Sobrevivendo ao Horror" })),
  ability({ name: "Acostumado à Maldição de <Elemento>", category: "Ocultista", group: "Poderes de Ocultista", summary: "Escolha Sangue, Morte, Conhecimento ou Energia. Falhar no preço da maldição de um item desse elemento não causa a perda de SAN; os outros efeitos ainda se aplicam.", requirement: "INT 2 e ritual de 2º círculo do elemento", unlockNex: 15, source: "Arquivos Secretos #1", page: "44", details: ["O elemento é definido quando o poder é adquirido.", "A proteção vale apenas para a perda de SAN do preço da maldição."] }),
  ability({ name: "Reter Ritual de Combate", category: "Ocultista", group: "Poderes de Ocultista", summary: "Permite mudar para cena a duração de um ritual retido que afeta negativamente um alvo quando ele sai da linha de efeito, ou preservar rituais quando uma condição encerraria a retenção.", cost: "Reação e 1 PE por ritual", requirement: "INT 2, ritual de 1º círculo e regra Reter Ritual", unlockNex: 15, source: "Arquivos Secretos #1", page: "44", details: ["Cada ritual preservado exige seu próprio custo."] }),
  ability({ name: "Ritual Intenso", category: "Ocultista", group: "Poderes de Ocultista", summary: "Soma sua Presença às rolagens de dano e às rolagens de cura de seus rituais.", requirement: "PRE 2", unlockNex: 15, source: "Arquivos Secretos #1", page: "44" }),
  ability({ name: "Saúde Sobrenatural", category: "Ocultista", group: "Poderes de Ocultista", summary: "Uma vez por cena, recebe PV temporários iguais a dez vezes sua Presença. Eles terminam no fim da cena e não acumulam com outro uso.", cost: "Ação de movimento e 3 PE", requirement: "INT 2, PRE 2 e ritual de 1º círculo", unlockNex: 15, source: "Arquivos Secretos #1", page: "44" }),
  ability({ name: "Predador Perfeito", category: "Combatente", group: "Poderes de Combatente", summary: "Uma vez por rodada, permite realizar uma ação padrão adicional que precisa ser usada de maneira ofensiva.", cost: "5 PE", requirement: "Nenhum", unlockNex: 15, source: "Arquivos Secretos #2", page: "40" }),
  ability({ name: "Golpes de Arena", category: "Combatente", group: "Poderes de Combatente", summary: "Após acertar um ataque corpo a corpo, permite fazer outro ataque ou uma manobra contra o mesmo alvo.", cost: "2 PE", requirement: "Treinado em Luta", unlockNex: 15, source: "Arquivos Secretos #2", page: "46" }),
  ability({ name: "Assassinato Furtivo", category: "Especialista", group: "Poderes de Especialista", summary: "Aumenta o dano do Ataque Furtivo e permite trocar os dados extras de d6 para d8 ao acertar.", cost: "2 PE", requirement: "Ataque Furtivo", unlockNex: 15, source: "Arquivos Secretos #2", page: "52" }),
  ability({ name: "Especialista em Matar", category: "Especialista", group: "Poderes de Especialista", summary: "Ao atacar, concede bônus distribuídos entre o teste de ataque e o dano; o custo e o bônus aumentam com o NEX.", cost: "2 a 5 PE", requirement: "AGI 2 ou FOR 2; treinado em Luta ou Pontaria", unlockNex: 15, source: "Arquivos Secretos #2", page: "58", details: ["NEX 15%: +4 por 2 PE; 25%: +8 por 3 PE; 55%: +12 por 4 PE; 85%: +16 por 5 PE."] }),
  ability({ name: "Dominar Habilidade Ritualística", category: "Ocultista", group: "Poderes de Ocultista", summary: "Escolha uma habilidade de trilha de Ocultista cujo NEX você já tenha alcançado. Dependências entre habilidades continuam valendo.", requirement: "INT 3, treinado em Ocultismo e capacidade de conjurar rituais", unlockNex: 15, source: "Arquivos Secretos #2", page: "74", details: ["Pode ser adquirido até três vezes, escolhendo uma habilidade em cada aquisição."] }),
  ability({ name: "Marteladas", category: "Combatente", group: "Poderes de Combatente", summary: "Realiza três ataques desarmados contra o mesmo alvo e resolve o dano como uma única fonte.", cost: "Ação completa e 3 PE", requirement: "FOR 2, treinado em Luta e Artista Marcial", unlockNex: 15, source: "Arquivos Secretos #2", page: "86" }),
  ability({ name: "Liturgia de Fortalecimento Ritualístico", category: "Ocultista", group: "Poderes de Ocultista", summary: "Durante um interlúdio, fortalece um ritual conhecido e aumenta sua DT até o próximo interlúdio.", cost: "Ação de interlúdio e 2 PE", requirement: "INT 2 e PRE 2", unlockNex: 15, source: "Arquivos Secretos #2", page: "92" }),
];

export const GENERAL_POWERS = [
  // Sobrevivendo ao Horror — poderes gerais
  ability({ name: "Acrobático", category: "Gerais", group: "Poderes Gerais", summary: "Concede treinamento em Acrobacia ou +2 se já for treinado; terreno difícil não reduz seu deslocamento nem impede investidas.", requirement: "AGI 2", unlockNex: 15, source: "Sobrevivendo ao Horror", page: "32" }),
  ability({ name: "Ás do Volante", category: "Gerais", group: "Poderes Gerais", summary: "Concede treinamento em Pilotagem ou +2 se já for treinado. Uma vez por rodada, um teste de Pilotagem pode evitar dano ao veículo pilotado.", requirement: "AGI 2", unlockNex: 15, source: "Sobrevivendo ao Horror", page: "32" }),
  ability({ name: "Atlético", category: "Gerais", group: "Poderes Gerais", summary: "Concede treinamento em Atletismo ou +2 se já for treinado e aumenta o deslocamento em 3 m.", requirement: "FOR 2", unlockNex: 15, source: "Sobrevivendo ao Horror", page: "32" }),
  ability({ name: "Atraente", category: "Gerais", group: "Poderes Gerais", summary: "Concede +5 em Artes, Diplomacia, Enganação e Intimidação contra pessoas que possam se sentir atraídas por você.", requirement: "PRE 2", unlockNex: 15, source: "Sobrevivendo ao Horror", page: "32" }),
  ability({ name: "Dedos Ágeis", category: "Gerais", group: "Poderes Gerais", summary: "Concede treinamento em Crime ou +2 se já for treinado; acelera ações de arrombar, furtar e sabotar conforme a regra.", requirement: "AGI 2", unlockNex: 15, source: "Sobrevivendo ao Horror", page: "32" }),
  ability({ name: "Detector de Mentiras", category: "Gerais", group: "Poderes Gerais", summary: "Concede treinamento em Intuição ou +2 se já for treinado e aplica −10 aos testes de Enganação feitos para mentir para você.", requirement: "PRE 2", unlockNex: 15, source: "Sobrevivendo ao Horror", page: "32" }),
  ability({ name: "Especialista em Emergências", category: "Gerais", group: "Poderes Gerais", summary: "Concede treinamento em Medicina ou +2 se já for treinado; permite aplicar cicatrizantes e medicamentos como ação de movimento e sacar um deles livremente uma vez por rodada.", requirement: "INT 2", unlockNex: 15, source: "Sobrevivendo ao Horror", page: "32" }),
  ability({ name: "Estigmado", category: "Gerais", group: "Poderes Gerais", summary: "Ao sofrer dano mental causado por medo, você pode convertê-lo em perda equivalente de PV.", unlockNex: 15, source: "Sobrevivendo ao Horror", page: "32" }),
  ability({ name: "Foco em Perícia", category: "Gerais", group: "Poderes Gerais", summary: "Escolha uma perícia treinada, exceto Luta e Pontaria. Você rola +1d20 nos testes dela; pode repetir o poder para perícias diferentes.", requirement: "Treinado na perícia escolhida", unlockNex: 15, source: "Sobrevivendo ao Horror", page: "32" }),
  ability({ name: "Inventário Organizado", category: "Gerais", group: "Poderes Gerais", summary: "Soma Intelecto à capacidade de carga e faz itens de 0,5 espaço ocuparem apenas 0,25 espaço.", requirement: "INT 2", unlockNex: 15, source: "Sobrevivendo ao Horror", page: "32" }),
  ability({ name: "Informado", category: "Gerais", group: "Poderes Gerais", summary: "Concede treinamento em Atualidades ou +2 se já for treinado; com aprovação do mestre, Atualidades substitui outra perícia em testes de informação.", requirement: "INT 2", unlockNex: 15, source: "Sobrevivendo ao Horror", page: "33" }),
  ability({ name: "Interrogador", category: "Gerais", group: "Poderes Gerais", summary: "Concede treinamento em Intimidação ou +2 se já for treinado e permite coagir com uma ação padrão, uma vez por cena por alvo.", requirement: "FOR 2", unlockNex: 15, source: "Sobrevivendo ao Horror", page: "33" }),
  ability({ name: "Mentiroso Nato", category: "Gerais", group: "Poderes Gerais", summary: "Concede treinamento em Enganação ou +2 se já for treinado e reduz a penalidade por mentiras muito improváveis.", requirement: "PRE 2", unlockNex: 15, source: "Sobrevivendo ao Horror", page: "33" }),
  ability({ name: "Observador", category: "Gerais", group: "Poderes Gerais", summary: "Concede treinamento em Investigação ou +2 se já for treinado e soma Intelecto aos testes de Intuição.", requirement: "INT 2", unlockNex: 15, source: "Sobrevivendo ao Horror", page: "33" }),
  ability({ name: "Pai de Pet", category: "Gerais", group: "Poderes Gerais", summary: "Concede treinamento em Adestramento ou +2 se já for treinado e um aliado animal que fornece +2 em duas perícias válidas escolhidas.", requirement: "PRE 2", unlockNex: 15, source: "Sobrevivendo ao Horror", page: "33" }),
  ability({ name: "Palavras de Devoção", category: "Gerais", group: "Poderes Gerais", summary: "Concede treinamento em Religião ou +2 se já for treinado. Uma vez por cena, fortalece contra dano mental um grupo limitado por sua Presença.", cost: "3 PE e ação completa", requirement: "PRE 2", unlockNex: 15, source: "Sobrevivendo ao Horror", page: "34", details: ["Participantes recebem resistência a dano mental 5 até o fim da cena."] }),
  ability({ name: "Parceiro", category: "Gerais", group: "Poderes Gerais", summary: "Concede um aliado de tipo escolhido. Se ele deixar o grupo, uma folga da Ordem é necessária para obter outro.", requirement: "Treinado em Diplomacia e NEX 30%", unlockNex: 30, source: "Sobrevivendo ao Horror", page: "34" }),
  ability({ name: "Pensamento Tático", category: "Gerais", group: "Poderes Gerais", summary: "Concede treinamento em Tática ou +2 se já for treinado. Analisar terreno pode dar uma ação de movimento extra ao grupo na primeira rodada do próximo combate ali.", requirement: "INT 2", unlockNex: 15, source: "Sobrevivendo ao Horror", page: "34" }),
  ability({ name: "Personalidade Esotérica", category: "Gerais", group: "Poderes Gerais", summary: "Concede +3 PE máximos e treinamento em Ocultismo, ou +2 na perícia se já for treinado.", requirement: "INT 2", unlockNex: 15, source: "Sobrevivendo ao Horror", page: "34" }),
  ability({ name: "Persuasivo", category: "Gerais", group: "Poderes Gerais", summary: "Concede treinamento em Diplomacia ou +2 se já for treinado e reduz em 5 a penalidade de pedidos custosos ou perigosos.", requirement: "PRE 2", unlockNex: 15, source: "Sobrevivendo ao Horror", page: "34" }),
  ability({ name: "Pesquisador Científico", category: "Gerais", group: "Poderes Gerais", summary: "Concede treinamento em Ciências ou +2 se já for treinado; Ciências pode substituir Ocultismo ou Sobrevivência para identificar criaturas e animais.", requirement: "INT 2", unlockNex: 15, source: "Sobrevivendo ao Horror", page: "34" }),
  ability({ name: "Proativo", category: "Gerais", group: "Poderes Gerais", summary: "Concede treinamento em Iniciativa ou +2 se já for treinado. Um resultado natural 19 ou 20 em um dos dados concede uma ação padrão extra no primeiro turno.", requirement: "AGI 2", unlockNex: 15, source: "Sobrevivendo ao Horror", page: "34" }),
  ability({ name: "Provisões de Emergência", category: "Gerais", group: "Poderes Gerais", summary: "Uma vez por missão, uma ação de interlúdio permite obter uma nova seleção de equipamentos correspondente à patente inicial da missão.", cost: "1 vez por missão", unlockNex: 15, source: "Sobrevivendo ao Horror", page: "34" }),
  ability({ name: "Racionalidade Inflexível", category: "Gerais", group: "Poderes Gerais", summary: "Permite usar Intelecto no lugar de Presença em Vontade e no cálculo dos PE máximos.", requirement: "INT 3", unlockNex: 15, source: "Sobrevivendo ao Horror", page: "34" }),
  ability({ name: "Rato de Computador", category: "Gerais", group: "Poderes Gerais", summary: "Concede treinamento em Tecnologia ou +2 se já for treinado, acelera operações digitais e permite procurar uma pista sem gastar rodada uma vez por cena de investigação.", requirement: "INT 2", unlockNex: 15, source: "Sobrevivendo ao Horror", page: "35" }),
  ability({ name: "Resposta Rápida", category: "Gerais", group: "Poderes Gerais", summary: "Concede treinamento em Reflexos ou +2 se já for treinado. Ao falhar em Percepção para evitar ficar desprevenido, pode refazer o teste com Reflexos.", cost: "2 PE", requirement: "AGI 2", unlockNex: 15, source: "Sobrevivendo ao Horror", page: "35" }),
  ability({ name: "Talentoso", category: "Gerais", group: "Poderes Gerais", summary: "Concede treinamento em Artes ou +2 se já for treinado e melhora gradualmente o bônus concedido ao impressionar com Artes.", requirement: "PRE 2", unlockNex: 15, source: "Sobrevivendo ao Horror", page: "35" }),
  ability({ name: "Teimosia Obstinada", category: "Gerais", group: "Poderes Gerais", summary: "Concede treinamento em Vontade ou +2 se já for treinado. Contra condições mentais ou mudança de atitude, pode receber +5 no teste.", cost: "2 PE", requirement: "PRE 2", unlockNex: 15, source: "Sobrevivendo ao Horror", page: "35" }),
  ability({ name: "Tenacidade", category: "Gerais", group: "Poderes Gerais", summary: "Concede treinamento em Fortitude ou +2 se já for treinado e libera um teste progressivo para encerrar a condição morrendo enquanto ainda estiver consciente.", requirement: "VIG 2", unlockNex: 15, source: "Sobrevivendo ao Horror", page: "35" }),
  ability({ name: "Sentidos Aguçados", category: "Gerais", group: "Poderes Gerais", summary: "Concede treinamento em Percepção ou +2 se já for treinado, evita ficar desprevenido contra alvos não vistos e permite refazer a chance de falha por camuflagem.", requirement: "PRE 2", unlockNex: 15, source: "Sobrevivendo ao Horror", page: "35" }),
  ability({ name: "Sobrevivencialista", category: "Gerais", group: "Poderes Gerais", summary: "Concede treinamento em Sobrevivência ou +2 se já for treinado, +2 contra clima e ignora a redução de deslocamento de terreno difícil natural.", requirement: "INT 2", unlockNex: 15, source: "Sobrevivendo ao Horror", page: "35" }),
  ability({ name: "Sorrateiro", category: "Gerais", group: "Poderes Gerais", summary: "Concede treinamento em Furtividade ou +2 se já for treinado e remove penalidades específicas por movimento e perseguição furtiva.", requirement: "AGI 2", unlockNex: 15, source: "Sobrevivendo ao Horror", page: "35" }),
  ability({ name: "Vitalidade Reforçada", category: "Gerais", group: "Poderes Gerais", summary: "Concede +1 PV por nível ou por cada 5% de NEX, além de +2 em Fortitude.", requirement: "VIG 2", unlockNex: 15, source: "Sobrevivendo ao Horror", page: "35" }),
  ability({ name: "Vontade Inabalável", category: "Gerais", group: "Poderes Gerais", summary: "Concede +1 PE a cada dois níveis ou 10% de NEX, além de +2 em Vontade.", requirement: "PRE 2", unlockNex: 15, source: "Sobrevivendo ao Horror", page: "35" }),
  ability({ name: "Artista Marcial", category: "Gerais", group: "Poderes Gerais", summary: "Seus ataques desarmados causam 1d6, podem usar Agilidade e melhoram para 1d8 no NEX 35% e 1d10 no NEX 70%.", requirement: "AGI 2", unlockNex: 15, source: "Sobrevivendo ao Horror", page: "32" }),
  ability({ name: "Combater com Duas Armas", category: "Gerais", group: "Poderes Gerais", summary: "Ao atacar com duas armas adequadas, permite um ataque com cada uma, aplicando a penalidade prevista.", requirement: "AGI 3 e treinado em Luta ou Pontaria", unlockNex: 15, source: "Sobrevivendo ao Horror", page: "32" }),
  ability({ name: "Saque Rápido", category: "Gerais", group: "Poderes Gerais", summary: "Permite sacar ou guardar itens livremente e reduz o tempo necessário para recarregar armas.", requirement: "Treinado em Iniciativa", unlockNex: 15, source: "Sobrevivendo ao Horror", page: "32" }),
  ability({ name: "Tiro Certeiro", category: "Gerais", group: "Poderes Gerais", summary: "Soma Agilidade ao dano com armas de disparo e evita a penalidade por alvo em combate corpo a corpo.", requirement: "Treinado em Pontaria", unlockNex: 15, source: "Sobrevivendo ao Horror", page: "32" }),
  ability({ name: "Cicatrizes Expostas", category: "Gerais", group: "Poderes Gerais", summary: "Ao expor uma cicatriz, seus danos recebem +1d8 do mesmo tipo até o fim da cena, mas você sofre uma penalidade de um dado em Vontade e em ações que exijam calma.", cost: "Ação de movimento", requirement: "Ter cicatrizes", unlockNex: 15, source: "Arquivos Secretos #1", page: "46", details: ["O efeito também começa se outra criatura expuser a cicatriz."] }),
  ability({ name: "Curiosidade Oculta", category: "Gerais", group: "Poderes Gerais", summary: "Concede treinamento em Ocultismo ou +2 se você já for treinado. Em um teste de Vontade, permite usar Ocultismo no lugar dela.", cost: "2 PE para substituir o teste", requirement: "INT 2", unlockNex: 15, source: "Arquivos Secretos #1", page: "46" }),
  ability({ name: "Especialista Esotérico", category: "Gerais", group: "Poderes Gerais", summary: "Ao conjurar um ritual, permite combinar os efeitos de até três catalisadores ritualísticos diferentes.", requirement: "INT 3, ritual de 2º círculo e Domínio Esotérico", unlockNex: 30, source: "Arquivos Secretos #1", page: "46" }),
  ability({ name: "<Habilidade> Aprimorada", category: "Gerais", group: "Poderes Gerais", summary: "Escolha uma habilidade ou ritual com DT. A DT aumenta em +2; o poder pode ser repetido para escolhas diferentes ou duas vezes para a mesma escolha, chegando a +5.", requirement: "Habilidade ou ritual com DT", unlockNex: 15, source: "Arquivos Secretos #1", page: "46" }),
  ability({ name: "Instintos Urbanos", category: "Gerais", group: "Poderes Gerais", summary: "Concede treinamento em Crime ou +2 se já for treinado. Em local fechado, um teste de Crime DT 20 pode identificar uma rota de fuga e conceder uma ação de movimento extra no primeiro turno da fuga e +2 na Defesa até escapar.", requirement: "AGI 2", unlockNex: 15, source: "Arquivos Secretos #1", page: "46", details: ["Se não houver rota identificável, o bônus de +2 na Defesa vale enquanto você permanecer no local."] }),
  ability({ name: "Revidar Violento", category: "Gerais", group: "Poderes Gerais", summary: "Concede uma segunda reação especial de defesa na rodada, desde que ela seja usada para contra-atacar.", requirement: "FOR 2 ou AGI 2", unlockNex: 15, source: "Arquivos Secretos #2", page: "40" }),
  ability({ name: "Corpo Fechado", category: "Gerais", group: "Poderes Gerais", summary: "Concede uma segunda reação especial de defesa na rodada, desde que ela seja um bloqueio.", requirement: "VIG 2", unlockNex: 15, source: "Arquivos Secretos #2", page: "46" }),
  ability({ name: "Esquiva Tática", category: "Gerais", group: "Poderes Gerais", summary: "Concede uma segunda reação especial de defesa na rodada, desde que ela seja uma esquiva.", requirement: "AGI 2", unlockNex: 15, source: "Arquivos Secretos #2", page: "52" }),
  ability({ name: "Palpite Confiante", category: "Gerais", group: "Poderes Gerais", summary: "Em um teste baseado em Intelecto ou Presença, soma Intelecto ao resultado.", cost: "1 PE", requirement: "INT 2", unlockNex: 15, source: "Arquivos Secretos #2", page: "58" }),
  ability({ name: "Arte da Música Macabra", category: "Gerais", group: "Poderes Gerais", summary: "Fortalece o próximo ataque, dano, margem de ameaça ou alcance de uma pessoa próxima que possa ouvir a apresentação.", cost: "Ação padrão e 2 PE", requirement: "Nenhum", unlockNex: 15, source: "Arquivos Secretos #2", page: "82" }),
  ability({ name: "Sintonização Mental com Proteção", category: "Gerais", group: "Poderes Gerais", summary: "Em um interlúdio, vincula uma proteção e permite que ela use um atributo escolhido no lugar de Agilidade para calcular Defesa até o próximo interlúdio.", cost: "Ação de interlúdio e 3 PE", requirement: "INT 2 ou PRE 2, treinado em Ocultismo e capacidade de conjurar rituais", unlockNex: 15, source: "Arquivos Secretos #2", page: "82" }),
  ability({ name: "Movimentação Tática", category: "Gerais", group: "Poderes Gerais", summary: "Ao avançar em direção a uma cobertura ou inimigo, dobra o deslocamento usado naquele movimento.", cost: "1 PE", requirement: "FOR 2, treinado em Atletismo e Tática", unlockNex: 15, source: "Arquivos Secretos #2", page: "86" }),
  ability({ name: "Sentido Tático", category: "Gerais", group: "Poderes Gerais", summary: "Impede que o personagem fique desprevenido e permite dificultar que um alvo se esconda dele por uma rodada.", cost: "2 PE", requirement: "PRE 2, treinado em Percepção e Tática", unlockNex: 15, source: "Arquivos Secretos #2", page: "86" }),
  ability({ name: "Prática com Materiais Ritualísticos", category: "Gerais", group: "Poderes Gerais", summary: "Remove a penalidade da primeira etapa de uma conjuração complexa ao empregar materiais ligados a uma Entidade.", requirement: "INT 2, treinado em Ocultismo e capacidade de conjurar rituais", unlockNex: 15, source: "Arquivos Secretos #2", page: "74" }),
  ability({ name: "Estágio Terminal", category: "Gerais", group: "Poderes Gerais", summary: "Uma vez por rodada, enquanto estiver machucado, concede uma ação de movimento adicional.", cost: "2 PE", requirement: "AGI 2", unlockNex: 15, source: "Arquivos Secretos #2", page: "78" }),
  ability({ name: "Kian Vai Nos Salvar", category: "Gerais", group: "Poderes Gerais", summary: "Em um desafio ligado à fé do personagem, o mestre pode liberar temporariamente um ritual de Conhecimento de até 3º círculo para aquela cena.", requirement: "PRE 2 e capacidade de conjurar rituais", unlockNex: 15, source: "Arquivos Secretos #2", page: "78", details: ["O ritual temporário não conta no limite de rituais conhecidos e apenas um pode ser liberado em cada cena."] }),
  ability({ name: "Tratamento de Emergência", category: "Gerais", group: "Poderes Gerais", summary: "Concede PV temporários a uma pessoa próxima; quando essa proteção termina, ela fica enfraquecida pelo restante da cena.", cost: "Ação padrão e 2 PE", requirement: "INT 2 e treinado em Medicina", unlockNex: 15, source: "Arquivos Secretos #2", page: "78", details: ["O mesmo alvo recebe esse benefício apenas uma vez por cena."] }),
  ability({ name: "Sintonização Mental com Arma", category: "Gerais", group: "Poderes Gerais", summary: "Em um interlúdio, vincula uma arma e permite usar um atributo escolhido nos testes de ataque e dano até o próximo interlúdio.", cost: "Ação de interlúdio e 3 PE", requirement: "INT 2 ou PRE 2, treinado em Ocultismo e capacidade de conjurar rituais", unlockNex: 15, source: "Arquivos Secretos #2", page: "83" }),
  ability({ name: "Especialista em Correntes", key: "fixacao", category: "Gerais", group: "Poderes Gerais", summary: "Permite prender itens com correntes para impedir que sejam desarmados ou retirados e melhora manobras feitas com equipamentos semelhantes.", cost: "Ação completa", requirement: "AGI 2", unlockNex: 15, source: "Arquivos Secretos #2", page: "70", details: ["Carregar vários itens presos dessa maneira pode gerar penalidade por carga."] }),
  ability({ name: "Especialista em Correntes", key: "controle", category: "Gerais", group: "Poderes Gerais", summary: "Ao acertar com uma corrente ou arma semelhante, permite puxar o alvo e dificultar ataques dele contra outras pessoas.", cost: "2 PE", requirement: "FOR 2 ou AGI 2 e treinado em Luta", unlockNex: 15, source: "Arquivos Secretos #2", page: "70" }),
];

const trail = (category, group, source, entries) =>
  entries.map(([name, unlockNex, summary, cost = "Passivo", requirement = "Trilha escolhida"]) =>
    ability({ name, category, group, summary, cost, requirement, unlockNex, source }),
  );

export const TRAIL_ABILITIES = [
  ...trail("Sobrevivente", "Durão", "Sobrevivendo ao Horror", [
    ["Durão", 2, "Recebe +4 PV no estágio 2 e mais +2 PV ao chegar ao estágio 3."],
    ["Pancada Forte", 4, "Ao fazer um ataque, gaste 1 PE para receber +1d20 no teste de ataque.", "1 PE"],
  ]).map((entry) => ({ ...entry, unlockStage: entry.unlockNex, unlockNex: 0 })),
  ...trail("Sobrevivente", "Esperto", "Sobrevivendo ao Horror", [
    ["Esperto", 2, "Concede treinamento em uma perícia adicional à sua escolha."],
    ["Entendido", 4, "Escolha duas perícias treinadas, exceto Luta e Pontaria; ao testá-las, gaste 1 PE para somar 1d4 ao resultado.", "1 PE"],
  ]).map((entry) => ({ ...entry, unlockStage: entry.unlockNex, unlockNex: 0 })),
  ...trail("Sobrevivente", "Esotérico", "Sobrevivendo ao Horror", [
    ["Esotérico", 2, "Sente energias paranormais em alcance curto para obter pistas ou alertas definidos pelo mestre.", "1 PE e ação padrão"],
    ["Iniciado", 4, "Aprende e pode conjurar um ritual de 1º círculo à escolha."],
  ]).map((entry) => ({ ...entry, unlockStage: entry.unlockNex, unlockNex: 0 })),
  ...trail("Combatente", "Aniquilador", "Livro base", [
    ["A Favorita", 10, "Escolha uma arma; ela passa a exigir uma categoria a menos para ser requisitada."],
    ["Técnica Secreta", 40, "Ao atacar com a arma favorita, aplique uma técnica para ampliar crítico ou atravessar resistência.", "2 PE"],
    ["Técnica Sublime", 65, "Libera técnicas avançadas para ampliar dano ou atingir mais de um alvo com a arma favorita.", "3 PE"],
    ["Máquina de Matar", 99, "A arma favorita ganha margem de ameaça maior e sobe um passo de dano."],
  ]),
  ...trail("Combatente", "Comandante de Campo", "Livro base", [
    ["Inspirar Confiança", 10, "Permite que um aliado próximo refaça um teste recém-realizado.", "2 PE e reação"],
    ["Estrategista", 40, "Concede ações de movimento a aliados orientados por você.", "1 PE por aliado e ação padrão"],
    ["Brecha na Guarda", 65, "Quando um aliado causa dano, abre espaço para um ataque adicional contra o mesmo alvo.", "2 PE e reação"],
    ["Oficial Comandante", 99, "Coordena aliados visíveis para que recebam uma ação padrão adicional.", "5 PE e ação completa"],
  ]),
  ...trail("Combatente", "Guerreiro", "Livro base", [
    ["Técnica Letal", 10, "Aumenta a margem de ameaça de ataques corpo a corpo."],
    ["Revidar", 40, "Depois de bloquear, permite atacar o oponente que realizou o golpe.", "2 PE e reação"],
    ["Força Opressora", 65, "Após acertar corpo a corpo, permite derrubar ou empurrar o alvo.", "1 PE"],
    ["Potência Máxima", 99, "Dobra os bônus numéricos do Ataque Especial usado com arma corpo a corpo."],
  ]),
  ...trail("Combatente", "Operações Especiais", "Livro base", [
    ["Iniciativa Aprimorada", 10, "Concede bônus elevado em Iniciativa."],
    ["Ataque Extra", 40, "Uma vez por rodada, permite fazer um ataque adicional.", "2 PE"],
    ["Surto de Adrenalina", 65, "Uma vez por rodada, concede uma ação padrão ou de movimento adicional.", "5 PE"],
    ["Sempre Alerta", 99, "Concede uma ação padrão adicional no começo de cada cena de combate."],
  ]),
  ...trail("Combatente", "Tropa de Choque", "Livro base", [
    ["Casca Grossa", 10, "Aumenta os PV conforme o NEX e melhora a resistência ao bloquear."],
    ["Cai Dentro", 40, "Pode redirecionar para você um ataque feito contra um aliado próximo.", "1 PE e reação"],
    ["Duro de Matar", 65, "Reduz pela metade um dano recebido; no ápice também funciona contra dano paranormal.", "2 PE e reação"],
    ["Inquebrável", 99, "Em estado crítico, aumenta Defesa e resistência e mantém sua capacidade de agir."],
  ]),
  ...trail("Especialista", "Atirador de Elite", "Livro base", [
    ["Mira de Elite", 10, "Concede proficiência com armas de fogo longas e soma Intelecto ao dano."],
    ["Disparo Letal", 40, "Ao mirar, amplia a margem de ameaça do próximo disparo.", "1 PE"],
    ["Disparo Impactante", 65, "Permite executar manobras com ataques à distância de armas adequadas.", "2 PE"],
    ["Atirar para Matar", 99, "Acertos críticos com arma de fogo causam o dano máximo da rolagem."],
  ]),
  ...trail("Especialista", "Infiltrador", "Livro base", [
    ["Ataque Furtivo", 10, "Uma vez por rodada, acrescenta dano contra alvo desprevenido ou flanqueado.", "1 PE"],
    ["Gatuno", 40, "Melhora Atletismo e Crime e remove penalidades de movimento ao escalar e esconder-se."],
    ["Assassinar", 65, "Analisa um alvo para ampliar o próximo Ataque Furtivo e aplicar um efeito incapacitante.", "3 PE e ação de movimento"],
    ["Sombra Fugaz", 99, "Permite esconder-se após uma ação chamativa sem a penalidade normal.", "3 PE"],
  ]),
  ...trail("Especialista", "Médico de Campo", "Livro base", [
    ["Paramédico", 10, "Usa Medicina para recuperar PV de um alvo adjacente.", "2 PE e ação padrão"],
    ["Equipe de Trauma", 40, "Aumenta a recuperação do Paramédico e permite remover uma condição física simples."],
    ["Resgate", 65, "Melhora seu deslocamento ao socorrer alguém e permite retirar um aliado do perigo.", "2 PE"],
    ["Reanimação", 99, "Tenta estabilizar e reerguer imediatamente um aliado incapacitado.", "5 PE e ação completa"],
  ]),
  ...trail("Especialista", "Negociador", "Livro base", [
    ["Eloquência", 10, "Permite alterar a atitude de alguém com Diplomacia durante uma conversa.", "1 PE"],
    ["Discurso Motivador", 40, "Concede dados extras em perícias aos aliados próximos durante a cena.", "4 PE e ação padrão"],
    ["Eu Conheço um Cara", 65, "Aciona um contato para obter ajuda, informação ou um serviço plausível.", "Conforme a situação"],
    ["Truque de Mestre", 99, "Uma vez por cena, transforma um teste social recém-realizado em resultado máximo.", "5 PE"],
  ]),
  ...trail("Especialista", "Técnico", "Livro base", [
    ["Inventário Otimizado", 10, "Aumenta a capacidade de carga usando Intelecto."],
    ["Remendão", 40, "Reduz a categoria de equipamentos gerais e permite reparos rápidos.", "Conforme o uso"],
    ["Improvisar", 65, "Monta temporariamente um equipamento geral que não estava no inventário.", "2 PE e ação completa"],
    ["Preparado para Tudo", 99, "Aumenta o benefício do inventário otimizado e facilita ter a ferramenta certa."],
  ]),
  ...trail("Ocultista", "Conduíte", "Livro base", [
    ["Ampliar Ritual", 10, "Aumenta o alcance ou duplica a área de um ritual.", "+2 PE"],
    ["Acelerar Ritual", 40, "Uma vez por rodada, conjura um ritual como ação livre.", "+4 PE"],
    ["Anular Ritual", 65, "Disputa Ocultismo com outro conjurador para cancelar um ritual que o tenha como alvo.", "PE igual ao custo do ritual e reação"],
    ["Canalizar o Medo", 99, "Ensina o ritual Canalizar o Medo.", "Conforme o ritual"],
  ]),
  ...trail("Ocultista", "Flagelador", "Livro base", [
    ["Poder do Flagelo", 10, "Permite pagar parte do custo de rituais com PV, dentro das restrições da habilidade.", "2 PV por PE"],
    ["Abraçar a Dor", 40, "Reduz pela metade um dano físico recebido.", "2 PE e reação"],
    ["Absorver Agonia", 65, "Quando um ritual derruba um inimigo, concede PE temporários conforme o círculo usado."],
    ["Medo Tangível", 99, "Ensina o ritual Medo Tangível.", "Conforme o ritual"],
  ]),
  ...trail("Ocultista", "Graduado", "Livro base", [
    ["Saber Ampliado", 10, "Aumenta a quantidade de rituais conhecidos e amplia novas escolhas em NEX futuros."],
    ["Grimório Ritualístico", 40, "Registra rituais extras que podem ser preparados após estudo do grimório."],
    ["Rituais Eficientes", 65, "Reduz o custo das versões aprimoradas dos rituais."],
    ["Conhecendo o Medo", 99, "Ensina o ritual Conhecendo o Medo.", "Conforme o ritual"],
  ]),
  ...trail("Ocultista", "Intuitivo", "Livro base", [
    ["Mente Sã", 10, "Concede resistência mental e melhora testes contra efeitos paranormais."],
    ["Presença Poderosa", 40, "Aumenta o limite de PE por rodada apenas para conjurar rituais."],
    ["Inabalável", 65, "Concede resistência a dano mental e paranormal e melhora certas resistências."],
    ["Presença do Medo", 99, "Ensina o ritual Presença do Medo.", "Conforme o ritual"],
  ]),
  ...trail("Ocultista", "Lâmina Paranormal", "Livro base", [
    ["Lâmina Maldita", 10, "Permite usar Ocultismo em ataques com arma afetada por Amaldiçoar Arma."],
    ["Gladiador Paranormal", 40, "Acertos corpo a corpo ajudam a recuperar PE temporários uma vez por rodada."],
    ["Conjuração Marcial", 65, "Ao conjurar um ritual, permite realizar um ataque corpo a corpo como ação livre.", "2 PE"],
    ["Lâmina do Medo", 99, "Ensina o ritual Lâmina do Medo.", "Conforme o ritual"],
  ]),

  // Trilhas de Sobrevivendo ao Horror e Arquivos Secretos
  ...trail("Combatente", "Agente Secreto", "Sobrevivendo ao Horror", [
    ["Carteirada", 10, "Usa autoridade e credenciais para obter cooperação em situações plausíveis."],
    ["O Sorriso", 40, "Amplia sua influência social e ajuda a desarmar suspeitas."],
    ["Método Investigativo", 65, "Organiza pistas e melhora a eficiência em cenas de investigação."],
    ["Multifacetado", 99, "Permite alternar entre técnicas de agente conforme a missão."],
  ]),
  ...trail("Combatente", "Caçador", "Sobrevivendo ao Horror", [
    ["Rastrear o Paranormal", 10, "Segue vestígios e sinais deixados por uma ameaça paranormal."],
    ["Estudar Fraquezas", 40, "Analisa uma ameaça para descobrir e explorar vulnerabilidades."],
    ["Atacar das Sombras", 65, "Melhora um ataque iniciado em posição furtiva ou vantajosa."],
    ["Estudar a Presa", 99, "Mantém uma análise profunda de uma presa escolhida durante a missão."],
  ]),
  ...trail("Combatente", "Monstruoso", "Sobrevivendo ao Horror", [
    ["Ser Amaldiçoado", 10, "Escolha um elemento; você recebe um benefício e uma marca paranormal ligada a ele."],
    ["Ser Macabro", 40, "A conexão escolhida evolui e libera um novo efeito do elemento."],
    ["Ser Assustador", 65, "A presença monstruosa fica mais intensa e amplia seus recursos de combate."],
    ["Ser Aterrorizante", 99, "Alcança o efeito máximo da transformação ligada ao elemento."],
  ]),
  ...trail("Especialista", "Bibliotecário", "Sobrevivendo ao Horror", [
    ["Conhecimento Prático", 10, "Usa estudo acumulado para apoiar testes de conhecimento e investigação."],
    ["Leitor Contumaz", 40, "Consegue extrair informações úteis de documentos com maior rapidez."],
    ["Rato de Biblioteca", 65, "Amplia o repertório de conhecimentos e fontes consultáveis."],
    ["A Força do Saber", 99, "Transforma conhecimento preparado em uma vantagem decisiva."],
  ]),
  ...trail("Especialista", "Perseverante", "Sobrevivendo ao Horror", [
    ["Soluções Improvisadas", 10, "Adapta recursos disponíveis para resolver um problema imediato."],
    ["Fuga Obstinada", 40, "Ajuda a continuar em movimento e escapar de contenções."],
    ["Determinação Inquestionável", 65, "Fortalece testes e recursos quando você insiste em um objetivo."],
    ["Só Mais um Passo", 99, "Permite realizar uma última ação decisiva apesar de condições adversas."],
  ]),
  ...trail("Especialista", "Muambeiro", "Sobrevivendo ao Horror", [
    ["Mascate", 10, "Facilita encontrar, avaliar e negociar equipamentos."],
    ["Fabricação", 40, "Permite produzir itens durante os períodos adequados usando recursos disponíveis."],
    ["Laboratório de Campo", 65, "Transforma seu equipamento em uma estação improvisada de trabalho."],
    ["Achado Conveniente", 99, "Revela um item útil e plausível guardado para a ocasião."],
  ]),
  ...trail("Ocultista", "Exorcista", "Sobrevivendo ao Horror", [
    ["Revelação do Mal", 10, "Ajuda a perceber e identificar influências paranormais."],
    ["Poder da Fé", 40, "Converte convicção em proteção ou reforço contra o paranormal."],
    ["Parareligiosidade", 65, "Combina práticas religiosas e ocultistas para fortalecer rituais de contenção."],
    ["Chagas da Resistência", 99, "Concede uma defesa extrema contra manifestações paranormais."],
  ]),
  ...trail("Ocultista", "Possuído", "Sobrevivendo ao Horror", [
    ["Poder Não Desejado", 10, "Uma presença interna concede um poder paranormal com consequências narrativas."],
    ["As Sombras Dentro", 40, "Permite liberar por instantes uma capacidade da presença que o acompanha."],
    ["Ele Me Ensina", 65, "A entidade compartilha conhecimento e amplia suas opções ocultistas."],
    ["Tornamo-nos Um", 99, "A ligação com a presença chega ao estágio máximo da trilha."],
  ]),
  ...trail("Ocultista", "Parapsicólogo", "Sobrevivendo ao Horror", [
    ["Terapia", 10, "Permite usar Profissão (psicólogo) em interações e para resistir a certos efeitos mentais."],
    ["Palavras-chave", 40, "Ao acalmar alguém, pode gastar PE para restaurar SAN ou PD.", "1 PE por ponto restaurado"],
    ["Reprogramação Mental", 65, "Durante um interlúdio, concede temporariamente uma habilidade válida a uma pessoa voluntária.", "5 PE"],
    ["A Sanidade Está Lá Fora", 99, "Remove condições de medo ou mentais de uma pessoa próxima.", "5 PE e ação de movimento"],
  ]),
  ...trail("Ocultista", "Maledictólogo", "Arquivos Secretos #1", [
    ["Identificação Macabra", 10, "Aprimora a análise de itens e efeitos amaldiçoados."],
    ["Compreensão de Maldições", 40, "Aprofunda o uso e a resistência a maldições estudadas."],
    ["Reproduzir Maldição", 65, "Imita temporariamente uma maldição compreendida pela trilha."],
    ["Maldição Suprema", 99, "Desbloqueia a aplicação mais avançada do estudo de maldições."],
  ]),
];

export const PARANORMAL_POWERS = [
  ability({ name: "Absorver Conhecimento", category: "Poderes Paranormais", group: "Conhecimento", summary: "Com uma fonte escrita em mãos, permite obter automaticamente uma resposta contida nela; também melhora o dado de bônus da ação de interlúdio ler.", cost: "1 PE e ação completa", requirement: "Afinidade reduz em 1 PE certos rituais de Conhecimento por toque", unlockNex: 15, source: "Sobrevivendo ao Horror", page: "46" }),
  ability({ name: "Apatia Herege", category: "Poderes Paranormais", group: "Conhecimento", summary: "Ao testar contra uma condição de medo, permite refazer o teste e aceitar o segundo resultado.", cost: "2 PE", requirement: "Conhecimento 1; afinidade permite escolher o melhor resultado", unlockNex: 30, source: "Sobrevivendo ao Horror", page: "47" }),
  ability({ name: "Antecipar Vitalidade", category: "Poderes Paranormais", group: "Morte", summary: "Em um teste, acumule uma carga para rolar +1d20. O máximo é seu Vigor e as cargas são removidas durante ações de interlúdio dormir em vez de recuperar PV.", requirement: "Afinidade aumenta o limite de cargas em 2", unlockNex: 15, source: "Sobrevivendo ao Horror", page: "46" }),
  ability({ name: "Aura de Pavor", category: "Poderes Paranormais", group: "Morte", summary: "Afeta uma pessoa ou animal em alcance médio com uma condição de medo; Vontade reduz o efeito e cada alvo só pode ser afetado uma vez por dia.", cost: "2 PE e ação de movimento", requirement: "Afinidade aumenta a DT e permite escolher vários alvos", unlockNex: 15, source: "Sobrevivendo ao Horror", page: "46" }),
  ability({ name: "Conexão Empática", category: "Poderes Paranormais", group: "Energia", summary: "Ao tocar um objeto elétrico ligado, permite conversar com ele até o fim da cena ou até soltar o objeto; as informações dependem do que ele consegue registrar.", cost: "2 PE e ação completa", requirement: "Energia 1; afinidade concede +5 em testes mentais com o objeto", unlockNex: 30, source: "Sobrevivendo ao Horror", page: "47" }),
  ability({ name: "Espreitar da Besta", category: "Poderes Paranormais", group: "Sangue", summary: "Concede +5 em Furtividade, permite usá-la no lugar de Atletismo ao caçar em perseguições e remove a penalidade indicada para ações discretas.", requirement: "Afinidade aumenta o bônus de Furtividade para +10", unlockNex: 15, source: "Sobrevivendo ao Horror", page: "46" }),
  ability({ name: "Instintos Sanguinários", category: "Poderes Paranormais", group: "Sangue", summary: "Concede visão no escuro e faro.", requirement: "Afinidade evita flanqueamento e desprevenido e concede +5 em resistências contra armadilhas", unlockNex: 15, source: "Sobrevivendo ao Horror", page: "46" }),
  ability({ name: "Valer-se do Caos", category: "Poderes Paranormais", group: "Energia", summary: "Antes de um teste, permite rolar +1d20; uma falha ou resultado baixo nesse dado extra causa perda de 1d4 SAN.", requirement: "Afinidade reduz a faixa que ativa a perda de SAN", unlockNex: 15, source: "Sobrevivendo ao Horror", page: "47" }),
  ability({ name: "Aprender Ritual", category: "Poderes Paranormais", group: "Conhecimento", summary: "Aprende um ritual permitido pelo círculo disponível para o personagem.", cost: "Conforme o ritual", requirement: "Afinidade: aprende novamente um ritual do elemento", unlockNex: 15 }),
  ability({ name: "Expansão de Conhecimento", category: "Poderes Paranormais", group: "Conhecimento", summary: "Permite escolher um poder de classe que não seja da sua classe, cumprindo os pré-requisitos.", requirement: "INT 2; afinidade reduz exigências", unlockNex: 30 }),
  ability({ name: "Precognição", category: "Poderes Paranormais", group: "Conhecimento", summary: "Concede bônus defensivo e em Reflexos por antecipar ameaças.", requirement: "Afinidade amplia o benefício", unlockNex: 15 }),
  ability({ name: "Visão do Oculto", category: "Poderes Paranormais", group: "Conhecimento", summary: "Permite enxergar no escuro e perceber manifestações sutis do paranormal.", requirement: "Afinidade amplia a percepção", unlockNex: 15 }),
  ability({ name: "Afortunado", category: "Poderes Paranormais", group: "Energia", summary: "Permite refazer resultados mínimos em dados escolhidos pelo poder.", requirement: "Afinidade melhora a repetição", unlockNex: 15 }),
  ability({ name: "Campo Protetor", category: "Poderes Paranormais", group: "Energia", summary: "Ao esquivar, converte Energia em bônus adicional de Defesa.", cost: "1 PE", requirement: "Afinidade amplia o bônus", unlockNex: 15 }),
  ability({ name: "Golpe de Sorte", category: "Poderes Paranormais", group: "Energia", summary: "Aumenta a margem de ameaça dos seus ataques.", requirement: "Afinidade melhora o multiplicador de crítico", unlockNex: 15 }),
  ability({ name: "Manipular Entropia", category: "Poderes Paranormais", group: "Energia", summary: "Força a repetição de um dado lançado por uma criatura próxima.", cost: "2 PE e reação", requirement: "Afinidade permite afetar mais dados", unlockNex: 15 }),
  ability({ name: "Encarar a Morte", category: "Poderes Paranormais", group: "Morte", summary: "Aumenta o limite de PE disponível em cada rodada.", requirement: "Afinidade amplia o aumento", unlockNex: 15 }),
  ability({ name: "Escapar da Morte", category: "Poderes Paranormais", group: "Morte", summary: "Uma vez por cena, evita uma consequência fatal ou incapacitante conforme a regra do poder.", cost: "1 vez por cena", requirement: "Afinidade melhora o uso", unlockNex: 15 }),
  ability({ name: "Potencial Aprimorado", category: "Poderes Paranormais", group: "Morte", summary: "Aumenta seus Pontos de Esforço máximos conforme o NEX.", requirement: "Afinidade aumenta novamente", unlockNex: 15 }),
  ability({ name: "Surto Temporal", category: "Poderes Paranormais", group: "Morte", summary: "Uma vez por cena, concede uma ação padrão adicional no seu turno.", cost: "3 PE", requirement: "Morte 2; afinidade libera novo uso", unlockNex: 30 }),
  ability({ name: "Anatomia Insana", category: "Poderes Paranormais", group: "Sangue", summary: "Concede chance de ignorar dano extra de acertos críticos e ataques furtivos.", requirement: "Afinidade amplia a proteção", unlockNex: 15 }),
  ability({ name: "Arma de Sangue", category: "Poderes Paranormais", group: "Sangue", summary: "Manifesta uma arma natural paranormal para ataques corpo a corpo.", cost: "1 PE", requirement: "Afinidade aprimora a arma", unlockNex: 15 }),
  ability({ name: "Sangue de Ferro", category: "Poderes Paranormais", group: "Sangue", summary: "Aumenta os PV máximos conforme o NEX.", requirement: "Afinidade aumenta novamente", unlockNex: 15 }),
  ability({ name: "Sangue Vivo", category: "Poderes Paranormais", group: "Sangue", summary: "Em condição crítica, pode recuperar PV no começo do turno.", cost: "2 PE", requirement: "Sangue 2; afinidade melhora a recuperação", unlockNex: 30 }),
  ability({ name: "Resistir a Elemento", category: "Poderes Paranormais", group: "Geral", summary: "Escolha um elemento e receba resistência ao dano ligado a ele.", requirement: "Afinidade aumenta a resistência", unlockNex: 15 }),
  ability({ name: "Ferro Maculado", category: "Poderes Paranormais", group: "Sangue", summary: "Ao atacar com arma de disparo, amaldiçoa a munição até o fim do turno e acrescenta +1d6 de dano de Sangue, que também é multiplicado no crítico.", cost: "2 PV", requirement: "Afinidade aumenta o adicional para +1d8", unlockNex: 15, source: "Arquivos Secretos #1", page: "47" }),
  ability({ name: "Placas Sanguinolentas", category: "Poderes Paranormais", group: "Sangue", summary: "Depois de conjurar um ritual de Sangue, recebe Defesa igual ao círculo do ritual até o começo do próximo turno.", requirement: "Ritual de Sangue; com afinidade, bônus igual a círculo +2", unlockNex: 15, source: "Arquivos Secretos #1", page: "47" }),
  ability({ name: "Sangue Corrosivo", category: "Poderes Paranormais", group: "Sangue", summary: "Até o fim da cena, uma criatura adjacente que causar dano a você sofre 1d10 de dano de Sangue.", cost: "Ação de movimento e 1 PE", requirement: "Afinidade aumenta para 2d10", unlockNex: 15, source: "Arquivos Secretos #1", page: "47" }),
  ability({ name: "Sangue Prazeroso", category: "Poderes Paranormais", group: "Sangue", summary: "Enquanto estiver machucado, concede resistência a dano 5.", requirement: "Sangue 1; afinidade concede 20 PV temporários uma vez por cena", unlockNex: 15, source: "Arquivos Secretos #1", page: "47" }),
  ability({ name: "Pressão Atmosférica", category: "Poderes Paranormais", group: "Energia", summary: "Após acertar um ataque corpo a corpo contra um alvo agarrado, acrescenta dano de Energia e pode deixá-lo atordoado por uma rodada.", cost: "3 PE", requirement: "Afinidade amplia os efeitos", unlockNex: 15, source: "Arquivos Secretos #2", page: "46" }),
  ability({ name: "Disparo da Morte", category: "Poderes Paranormais", group: "Morte", summary: "Antes de um ataque à distância, amplia a margem de ameaça; com afinidade, também atravessa parte da proteção do alvo.", cost: "3 PE", requirement: "Afinidade amplia o efeito", unlockNex: 15, source: "Arquivos Secretos #2", page: "58" }),
  ability({ name: "Predador de Sangue", category: "Poderes Paranormais", group: "Sangue", summary: "Memoriza os sinais de uma pessoa para melhorar testes usados para rastreá-la, percebê-la e atacá-la; a afinidade amplia o número de alvos memorizados.", cost: "Ação padrão e 3 PE", requirement: "Afinidade amplia o efeito", unlockNex: 15, source: "Arquivos Secretos #2", page: "40" }),
  ability({ name: "Zona dos Sussurros", category: "Poderes Paranormais", group: "Conhecimento", summary: "Marca uma área que melhora ataques e permite agir furtivamente após ações chamativas; a afinidade melhora o dano contra alvos vulneráveis.", cost: "Ação completa e 3 PE", requirement: "Afinidade amplia o efeito", unlockNex: 15, source: "Arquivos Secretos #2", page: "52", details: ["Mantém até três áreas; criar outra encerra uma das anteriores."] }),
  ability({ name: "Engolir Sangue", category: "Poderes Paranormais", group: "Sangue", summary: "Ao realizar um ato macabro com uma porção orgânica, recupera PV, mas sofre uma perda de SAN; a afinidade aumenta a recuperação.", cost: "Ação completa e 1d4 SAN", requirement: "Afinidade amplia o efeito", unlockNex: 15, source: "Arquivos Secretos #2", page: "93" }),
];

export const ORIGIN_POWER_DETAILS = {
  "Saber é Poder": ["Aprimora um teste baseado em Intelecto quando você investe esforço.", "2 PE"],
  "Técnica Medicinal": ["Melhora a recuperação obtida com cuidados de Medicina.", "Conforme o uso"],
  "Vislumbres do Passado": ["O mestre pode revelar fragmentos úteis da história esquecida do personagem.", "Narrativo"],
  "Magnum Opus": ["Uma obra reconhecível facilita interações com quem aprecia seu trabalho.", "Passivo"],
  "110%": ["Permite gastar esforço para melhorar testes físicos ligados ao treinamento atlético.", "2 PE"],
  "O Crime Compensa": ["Ao fim da missão, pode conseguir um item adicional dentro do limite da origem.", "Entre missões"],
  "Traços do Outro Lado": ["Concede um poder paranormal inicial, junto das consequências previstas pela regra.", "Automático"],
  Calejado: ["Aumenta seus PV máximos e representa resistência adquirida.", "Passivo"],
  "Ferramentas Favoritas": ["Escolha um item útil da profissão para reduzir sua categoria de requisição.", "Passivo"],
  "Processo Otimizado": ["Uma vez por cena, usa experiência profissional para melhorar um teste de perícia.", "2 PE"],
  "Faro para Pistas": ["Ao procurar pistas, pode receber ajuda extra do mestre para encontrar uma conexão.", "1 PE"],
  "Mão Pesada": ["Aumenta o dano causado por ataques corpo a corpo.", "Passivo"],
  "Patrocinador da Ordem": ["Melhora o acesso do grupo a equipamento no começo da missão.", "Entre missões"],
  "Posição de Combate": ["No começo do combate, permite reposicionar-se rapidamente.", "2 PE"],
  "Treinamento Militar": ["Melhora o dano com armas de fogo.", "Passivo"],
  "Ferramentas da Profissão": ["Escolha uma ferramenta de trabalho que passa a funcionar como arma favorecida.", "Passivo"],
  Patrulha: ["Ajuda a perceber ameaças e agir no início de confrontos.", "Passivo"],
  Exorcismo: ["Apoia aliados próximos em testes contra efeitos paranormais.", "2 PE"],
  "Espírito Cívico": ["Ao ajudar alguém, melhora o bônus concedido pela ação.", "Passivo"],
  "Eu Já Sabia": ["Uma vez por cena, usa suas suspeitas para melhorar um teste recém-realizado.", "2 PE"],
  "Computação Avançada": ["Permite usar Tecnologia no lugar de certas perícias ao operar dispositivos adequados.", "Conforme o uso"],
  "Trilhas e Rumos": ["Ajuda o grupo a viajar, orientar-se e encontrar abrigo em ambientes naturais.", "Passivo"],
  Impostor: ["Permite substituir uma perícia social por Enganação em uma situação plausível.", "2 PE"],
  Empenho: ["Concede bônus em um teste de perícia quando você se dedica ao máximo.", "1 PE"],
  "Companheiro Animal": ["Concede um aliado animal com uma função escolhida para ajudar o grupo.", "Passivo"],
  "Acostumado ao Extremo": ["Aumenta a resistência a ambientes hostis e situações físicas extremas.", "Passivo"],
  "Fome do Outro Lado": ["Prepara alimento especial que concede um benefício paranormal temporário.", "Durante interlúdio"],
  "Poder da Amizade": ["Um vínculo com os companheiros pode reforçar testes em momentos importantes.", "Conforme o uso"],
  "Não é fantasia, é cosplay!": ["Usa figurino e interpretação para criar um disfarce convincente.", "Conforme o uso"],
  Conexões: ["Aciona contatos institucionais para conseguir informação ou acesso plausível.", "Conforme a cena"],
  "Manual do Sobrevivente": ["Concede preparo prático para exploração, fuga e obtenção de recursos.", "Passivo"],
  Mutação: ["Escolha uma alteração do experimento que concede um benefício específico.", "Passivo"],
  "Conhecimento Oculto": ["Ajuda a identificar criaturas e lembrar informações sobre ameaças paranormais.", "Conforme o uso"],
  "Através da Lente": ["Uma câmera ajuda a perceber detalhes e registrar indícios difíceis de notar.", "Conforme o uso"],
  "Invenção Paranormal": ["Cria um dispositivo experimental com um efeito paranormal definido pela origem.", "Conforme o item"],
  "A Culpa é das Estrelas": ["Usa práticas místicas para obter uma orientação limitada sobre a situação.", "Conforme o uso"],
  "Luto Habitual": ["A experiência profissional fortalece sua reação diante de cenas perturbadoras.", "Passivo"],
  "Mapa Celeste": ["Permite orientar-se e guiar o grupo usando sinais naturais e o céu.", "Passivo"],
  "Fôlego de Nadador": ["Melhora natação, mergulho e resistência ao permanecer sem respirar.", "Passivo"],
  "Mãos no Volante": ["Aprimora manobras e controle de veículos em situações de risco.", "Conforme o uso"],
  "O Inteligentão": ["Usa conhecimento de cultura e tecnologia para obter uma vantagem contextual.", "Conforme o uso"],
  "Luta ou Fuga": ["Diante de perigo imediato, escolhe um benefício para enfrentar ou evitar a ameaça.", "Conforme a cena"],
  Terapia: ["Usa conhecimento psicológico para apoiar outras pessoas contra efeitos mentais.", "Conforme o uso"],
  "Encontrar a Verdade": ["Conecta depoimentos e pistas para apontar uma informação relevante à investigação.", "Conforme o uso"],
  "Mácula Ritualística": ["A cicatriz paranormal conecta o personagem a um elemento e concede o benefício definido pela origem.", "Passivo"],
  "Sofrimento de Sangue": ["Transforma a ligação da origem com Sangue em um recurso de resistência ou confronto.", "Conforme o uso"],
};

export const ORIGIN_BACKGROUNDS = {
  "Acadêmico": "Você passou boa parte da vida entre estudos, pesquisas e ambientes de ensino, aprendendo a encontrar respostas onde outros veem apenas informação solta.",
  "Agente de Saúde": "Sua experiência cuidando de pessoas ensinou a reconhecer sintomas, manter a calma e agir quando alguém precisa de atendimento.",
  "Amnésico": "Uma parte importante do seu passado desapareceu. As lacunas da memória podem esconder capacidades, contatos ou acontecimentos ligados à missão.",
  "Artista": "Você viveu de alguma forma de arte e aprendeu a se expressar, chamar atenção e criar conexões com públicos diferentes.",
  "Atleta": "Treinos e competições moldaram sua disciplina, condicionamento e capacidade de superar limites físicos.",
  "Criminoso": "Você conhece atalhos ilegais, ambientes clandestinos e maneiras discretas de conseguir aquilo que precisa.",
  "Cultista Arrependido": "Você já esteve próximo de um grupo paranormal e agora usa o que aprendeu para combater aquilo que antes ajudava.",
  "Desgarrado": "Acostumado a depender de si mesmo, você aprendeu a resistir a dificuldades e sobreviver com poucos recursos.",
  "Engenheiro": "Seu trabalho envolve planejar, construir e resolver problemas técnicos usando ferramentas e raciocínio prático.",
  "Executivo": "Você conhece pressão, negociação e processos profissionais, usando organização para obter resultados rapidamente.",
  "Investigador": "Seguir pistas, comparar versões e perceber incoerências fazia parte da sua rotina antes de entrar para a Ordem.",
  "Lutador": "Anos de treino corporal ensinaram você a reagir depressa e transformar técnica física em vantagem.",
  "Magnata": "Recursos, influência e contatos fizeram parte da sua vida, abrindo portas que normalmente permaneceriam fechadas.",
  "Mercenário": "Você trabalhou em situações de risco e aprendeu a avaliar posições, ameaças e rotas antes que o confronto comece.",
  "Militar": "Disciplina, preparo e familiaridade com operações armadas formaram sua maneira direta de enfrentar perigos.",
  "Operário": "O trabalho manual ensinou você a aguentar esforço prolongado e dominar as ferramentas da própria profissão.",
  "Policial": "Patrulhas e ocorrências treinaram sua percepção, sua postura diante de ameaças e o uso responsável de equipamento.",
  "Religioso": "Sua fé e atuação em uma comunidade espiritual ajudam a orientar pessoas e enfrentar manifestações paranormais.",
  "Servidor Público": "Você conhece instituições, procedimentos e o valor de cooperar para que um grupo alcance um objetivo comum.",
  "Teórico da Conspiração": "Você passou anos conectando acontecimentos estranhos e procurando explicações escondidas por trás do cotidiano.",
  "T.I.": "Tecnologia, redes e sistemas fazem parte da sua rotina, permitindo resolver problemas digitais e encontrar dados importantes.",
  "Trabalhador Rural": "A vida longe dos grandes centros ensinou orientação, leitura do ambiente e soluções práticas para imprevistos.",
  "Trambiqueiro": "Você domina improviso social, distrações e histórias convincentes para sair de situações complicadas.",
  "Universitário": "A rotina acadêmica deu acesso a assuntos variados, grupos diferentes e uma disposição enorme para aprender sob pressão.",
  "Amigo dos Animais": "Você criou uma ligação especial com animais e sabe interpretar comportamento, conquistar confiança e trabalhar ao lado deles.",
  "Astronauta": "Treinamento para ambientes extremos ensinou controle emocional, conhecimento técnico e resistência a condições incomuns.",
  "Chef do Outro Lado": "Culinária e paranormal se encontraram na sua história, transformando preparo de alimentos em uma ferramenta incomum.",
  "Colegial": "Você ainda vive a rotina escolar, mas amizades, curiosidade e domínio de tecnologia já se provaram úteis diante do impossível.",
  "Cosplayer": "Criar figurinos e interpretar personagens desenvolveu sua criatividade, presença e habilidade para assumir aparências convincentes.",
  "Diplomata": "Você aprendeu a circular por culturas e instituições diferentes, construindo contatos e evitando conflitos desnecessários.",
  "Explorador": "Expedições e viagens ensinaram planejamento, resistência e maneiras de continuar avançando em lugares desconhecidos.",
  "Experimento": "Alguma intervenção incomum alterou você. As consequências fazem parte do personagem e podem ter relação com o paranormal.",
  "Fanático por Criaturas": "Você coleciona relatos e informações sobre seres estranhos, tentando reconhecer padrões antes que seja tarde.",
  "Fotógrafo": "Seu olhar treinado encontra enquadramentos e detalhes que passam despercebidos, preservando pistas em imagens.",
  "Inventor Paranormal": "Você mistura engenharia e fenômenos do Outro Lado para criar protótipos que outras pessoas considerariam impossíveis.",
  "Jovem Místico": "Práticas espirituais e crenças alternativas despertaram cedo sua sensibilidade para sinais que outros ignoram.",
  "Legista do Turno da Noite": "O trabalho técnico em horários silenciosos fortaleceu sua atenção a evidências e sua calma diante do incomum.",
  "Mateiro": "Você conhece caminhos naturais, sinais do clima e técnicas para guiar um grupo com segurança fora da cidade.",
  "Mergulhador": "Experiência embaixo d’água treinou seu fôlego, autocontrole e resistência em ambientes difíceis.",
  "Motorista": "Muitas horas ao volante deram reflexos, controle de veículos e experiência para reagir a imprevistos na estrada.",
  "Nerd Entusiasta": "Você transforma curiosidade por ciência, cultura e tecnologia em conhecimento útil para situações inesperadas.",
  "Profetizado": "Uma previsão colocou seu nome no centro de acontecimentos futuros, mesmo que ninguém saiba exatamente como ela vai se cumprir.",
  "Psicólogo": "Você estudou comportamento e escuta, aprendendo a apoiar pessoas e reconhecer mudanças emocionais importantes.",
  "Repórter Investigativo": "Você sabe entrevistar, cruzar fontes e insistir até encontrar a informação que alguém tentou esconder.",
  "Ferido por Ritual": "Um ritual deixou uma marca paranormal duradoura e uma ligação com determinado elemento do Outro Lado.",
  "Transtornado Arrependido": "Você abandonou um grupo perigoso e carrega conhecimento sobre seus métodos, tentando dar outro destino ao que viveu.",
};

const RITUAL_COSTS = { 1: 1, 2: 3, 3: 6, 4: 10 };
const ritual = (name, element, circle, summary, source = "Livro base", mechanics = {}) => ({
  id: slug(`ritual-${source}-${Array.isArray(element) ? element.join("-") : element}-${circle}-${name}`),
  name,
  element: Array.isArray(element) ? element[0] : element,
  elements: Array.isArray(element) ? element : [element],
  circle,
  cost: `${RITUAL_COSTS[circle]} PE/PD`,
  summary,
  source,
  ...mechanics,
});

export const RITUALS = [
  // 1º círculo
  ritual("Compreensão Paranormal", "Conhecimento", 1, "Permite compreender uma mensagem, escrita ou idioma que normalmente seria inacessível."),
  ritual("Enfeitiçar", "Conhecimento", 1, "Torna um alvo mais receptivo à sua presença e às suas palavras por um período curto."),
  ritual("Perturbação", "Conhecimento", 1, "Implanta uma ordem mental curta; a resistência do alvo define se ele a segue."),
  ritual("Ouvir os Sussurros", "Conhecimento", 1, "Faz perguntas limitadas ao Outro Lado para obter presságios ou pistas."),
  ritual("Terceiro Olho", "Conhecimento", 1, "Permite perceber auras e presenças paranormais próximas."),
  ritual("Tecer Ilusões", "Conhecimento", 1, "Cria uma ilusão visual ou sonora simples em uma área."),
  ritual("Amaldiçoar Tecnologia", "Energia", 1, "Aprimora temporariamente uma tecnologia ou arma com uma modificação escolhida."),
  ritual("Eletrocussão", "Energia", 1, "Dispara Energia contra um alvo, causando dano elétrico e podendo afetar seus movimentos."),
  ritual("Embaralhar", "Energia", 1, "Cria imagens instáveis ao redor do conjurador e aumenta sua Defesa."),
  ritual("Luz", "Energia", 1, "Cria uma fonte de luz controlável que também pode ser intensificada."),
  ritual("Polarização Caótica", "Energia", 1, "Manipula objetos soltos com força magnética paranormal."),
  ritual("Cicatrização", "Morte", 1, "Acelera a recuperação de um alvo, com o efeito colateral temporal previsto pelo ritual."),
  ritual("Consumir Manancial", "Morte", 1, "Absorve energia do ambiente para conceder PV temporários ao conjurador."),
  ritual("Decadência", "Morte", 1, "Concentra Morte em um alvo para causar dano e deteriorar sua resistência."),
  ritual("Definhar", "Morte", 1, "Enfraquece um alvo e aplica uma condição física negativa."),
  ritual("Nuvem de Cinzas", "Morte", 1, "Preenche uma área com cinzas que dificultam a visão."),
  ritual("Espirais da Perdição", "Morte", 1, "Marca um alvo para reduzir a eficiência de seus ataques."),
  ritual("Armadura de Sangue", "Sangue", 1, "Reveste o alvo com proteção paranormal e aumenta sua Defesa."),
  ritual("Arma Atroz", "Sangue", 1, "Aprimora uma arma corpo a corpo, elevando seu potencial ofensivo."),
  ritual("Fortalecimento Sensorial", "Sangue", 1, "Amplia sentidos, percepção e capacidade de reagir ao ambiente."),
  ritual("Ódio Incontrolável", "Sangue", 1, "Coloca um alvo em estado de agressividade intensa, melhorando combate corpo a corpo e limitando decisões."),
  ritual("Distorcer Aparência", "Sangue", 1, "Altera temporariamente traços físicos para criar outra aparência."),
  ritual("Corpo Adaptado", "Sangue", 1, "Adapta o corpo do alvo a uma condição ambiental hostil escolhida."),
  ritual("Cinerária", "Medo", 1, "Cria uma área que fortalece conjurações e interage com a Névoa paranormal."),

  // 2º círculo
  ritual("Aprimoramento Mental", "Conhecimento", 2, "Aumenta temporariamente Intelecto, Presença ou ambos, conforme a versão usada."),
  ritual("Detecção de Ameaças", "Conhecimento", 2, "Revela a direção de perigos e presenças hostis em uma área."),
  ritual("Esconder dos Olhos", "Conhecimento", 2, "Oculta o alvo da visão comum por um período limitado."),
  ritual("Ligação Telepática", "Conhecimento", 2, "Cria comunicação mental entre pessoas escolhidas."),
  ritual("Localização", "Conhecimento", 2, "Aponta a direção de um objeto ou pessoa conhecida dentro do alcance do ritual."),
  ritual("Chamas do Caos", "Energia", 2, "Controla fogo paranormal para atacar, proteger ou modificar a área."),
  ritual("Coincidência Forçada", "Energia", 2, "Distorce probabilidades e concede bônus em testes dos alvos escolhidos."),
  ritual("Contenção Fantasmagórica", "Energia", 2, "Cria laços energéticos que restringem o deslocamento de um alvo."),
  ritual("Dissonância Acústica", "Energia", 2, "Cria uma área de ruído anômalo que atrapalha comunicação e conjuração."),
  ritual("Sopro do Caos", "Energia", 2, "Libera uma corrente caótica que empurra, derruba ou reposiciona alvos."),
  ritual("Tela de Ruído", "Energia", 2, "Forma uma barreira reativa que absorve parte do dano recebido."),
  ritual("Eco Espiral", "Morte", 2, "Registra o dano sofrido por um alvo e o devolve parcialmente ao fim do efeito."),
  ritual("Desacelerar Impacto", "Morte", 2, "Reduz dano de queda, colisão ou impacto por meio de distorção temporal."),
  ritual("Paradoxo", "Morte", 2, "Cria uma distorção temporal que causa dano em uma área."),
  ritual("Miasma", "Morte", 2, "Produz uma nuvem nociva que afeta criaturas em uma região."),
  ritual("Velocidade Mortal", "Morte", 2, "Acelera o alvo, concedendo uma ação adicional limitada enquanto for sustentado."),
  ritual("Descarnar", "Sangue", 2, "Causa dano de Sangue contínuo e impõe uma condição física ao alvo."),
  ritual("Transfusão Vital", "Sangue", 2, "Transfere vitalidade entre o conjurador e outra criatura."),
  ritual("Físico Aprimorado", "Sangue", 2, "Aumenta temporariamente Força, Agilidade ou Vigor."),
  ritual("Hemofagia", "Sangue", 2, "Um ataque corporal fortalecido causa dano e recupera parte da vitalidade do conjurador."),
  ritual("Rejeitar Névoa", "Medo", 2, "Afasta temporariamente manifestações da Névoa em uma área."),

  // 3º círculo
  ritual("Alterar Memória", "Conhecimento", 3, "Edita uma lembrança recente de um alvo que falhe em resistir."),
  ritual("Contato Paranormal", "Conhecimento", 3, "Busca respostas mais profundas no Outro Lado, assumindo os riscos da consulta."),
  ritual("Mergulho Mental", "Conhecimento", 3, "Permite entrar na mente de um alvo para observar pensamentos e memórias."),
  ritual("Vidência", "Conhecimento", 3, "Mostra à distância um lugar, pessoa ou objeto ligado ao conjurador."),
  ritual("Convocação Instantânea", "Energia", 3, "Guarda um objeto em um espaço paranormal e o recupera instantaneamente depois."),
  ritual("Salto Fantasma", "Energia", 3, "Teletransporta o conjurador ou um alvo para um ponto dentro do alcance."),
  ritual("Transfigurar Água", "Energia", 3, "Manipula uma grande quantidade de água, alterando movimento e forma."),
  ritual("Transfigurar Terra", "Energia", 3, "Molda o terreno e cria alterações físicas temporárias na área."),
  ritual("Âncora Temporal", "Morte", 3, "Prende um alvo à própria posição temporal e dificulta seu deslocamento."),
  ritual("Poeira da Podridão", "Morte", 3, "Espalha partículas paranormais que causam dano e enfraquecimento em área."),
  ritual("Tentáculos de Lodo", "Morte", 3, "Invoca formas de lodo que agarram e atacam criaturas em uma região."),
  ritual("Zerar Entropia", "Morte", 3, "Interrompe o fluxo temporal de um alvo por um período curto."),
  ritual("Ferver Sangue", "Sangue", 3, "Provoca dano intenso de Sangue e dificulta as ações do alvo."),
  ritual("Forma Monstruosa", "Sangue", 3, "Transforma o alvo para ampliar atributos físicos e capacidade de combate."),
  ritual("Purgatório", "Sangue", 3, "Cria uma área opressora que amplifica dano e dificulta a movimentação."),
  ritual("Vomitar Pestes", "Sangue", 3, "Conjura uma infestação paranormal que ocupa uma área e ataca alvos."),
  ritual("Neutralizar Ritual", "Medo", 3, "Suprime ou encerra outro efeito ritualístico dentro dos limites da conjuração."),

  // 4º círculo
  ritual("Controle Mental", "Conhecimento", 4, "Assume o controle das decisões de um alvo que não resista ao ritual."),
  ritual("Possessão", "Conhecimento", 4, "Projeta a consciência do conjurador para controlar outro corpo temporariamente."),
  ritual("Visão da Verdade", "Conhecimento", 4, "Revela ilusões, transformações e detalhes ocultos pelo paranormal."),
  ritual("Alterar Destino", "Energia", 4, "Distorce probabilidades para permitir novas rolagens e evitar resultados ruins."),
  ritual("Deflagração de Energia", "Energia", 4, "Libera uma grande descarga de Energia que causa dano em uma área ampla."),
  ritual("Teletransporte", "Energia", 4, "Transporta o grupo por uma grande distância até um destino definido."),
  ritual("Convocar o Algoz", "Morte", 4, "Invoca uma manifestação que persegue e enfraquece um alvo marcado."),
  ritual("Distorcer o Tempo", "Morte", 4, "Cria uma zona temporal alterada que concede ações adicionais ao conjurador."),
  ritual("Fim Inevitável", "Morte", 4, "Forma uma anomalia que atrai criaturas e causa dano crescente na área."),
  ritual("Capturar o Coração", "Sangue", 4, "Cria um vínculo extremo com um alvo e permite afetar sua vitalidade à distância."),
  ritual("Invólucro de Carne", "Sangue", 4, "Cria uma duplicata corporal temporária obediente ao conjurador."),
  ritual("Vínculo de Sangue", "Sangue", 4, "Une os destinos de duas criaturas e compartilha parte dos efeitos entre elas."),
  ritual("Canalizar o Medo", "Medo", 4, "Converte a afinidade com o Medo em flexibilidade para conjurar outros rituais."),
  ritual("Conhecendo o Medo", "Medo", 4, "Expõe um alvo a uma verdade paranormal que reduz suas capacidades."),
  ritual("Presença do Medo", "Medo", 4, "Cria uma presença opressora que afeta criaturas próximas."),
  ritual("Medo Tangível", "Medo", 4, "Condensa o Medo em uma proteção paranormal resistente."),
  ritual("Lâmina do Medo", "Medo", 4, "Fortalece uma arma com Medo para produzir um ataque ritualístico decisivo."),

  // Sobrevivendo ao Horror
  ritual("Esfolar", "Sangue", 1, "Marca um alvo com Sangue e o deixa mais vulnerável a certos efeitos.", "Sobrevivendo ao Horror"),
  ritual("Sede de Adrenalina", "Sangue", 2, "Força o corpo a um pico temporário de desempenho e cobra o esforço depois.", "Sobrevivendo ao Horror"),
  ritual("Odor da Caçada", "Sangue", 3, "Permite perseguir um alvo marcado e melhora ações ligadas à caçada.", "Sobrevivendo ao Horror"),
  ritual("Martírio de Sangue", "Sangue", 4, "Cria uma ligação sacrificial que converte sofrimento em um efeito ritualístico poderoso.", "Sobrevivendo ao Horror"),
  ritual("Apagar as Luzes", "Morte", 1, "Extingue fontes de luz e encobre a área com influência de Morte.", "Sobrevivendo ao Horror"),
  ritual("Língua Morta", "Morte", 2, "Permite obter comunicação limitada com vestígios deixados por quem morreu.", "Sobrevivendo ao Horror"),
  ritual("Fedor Pútrido", "Morte", 3, "Cria uma área debilitante ligada à decomposição paranormal.", "Sobrevivendo ao Horror"),
  ritual("Singularidade Temporal", "Morte", 4, "Concentra uma distorção extrema de tempo e espaço em uma região.", "Sobrevivendo ao Horror"),
  ritual("Desfazer Sinapses", "Conhecimento", 1, "Interfere brevemente nos impulsos mentais e dificulta a próxima ação do alvo.", "Sobrevivendo ao Horror"),
  ritual("Aurora da Verdade", "Conhecimento", 2, "Revela contradições, ocultações e sinais de falsidade na área.", "Sobrevivendo ao Horror"),
  ritual("Relembrar Fragmento", "Conhecimento", 3, "Recupera uma lembrança ou informação mental fragmentada.", "Sobrevivendo ao Horror"),
  ritual("Pronunciar Sigilo", "Conhecimento", 4, "Ativa um símbolo de Conhecimento com um efeito amplo de controle ou revelação.", "Sobrevivendo ao Horror"),
  ritual("Overclock", "Energia", 1, "Acelera temporariamente o funcionamento de um dispositivo.", "Sobrevivendo ao Horror"),
  ritual("Tremeluzir", "Energia", 2, "Torna a posição de um alvo instável e difícil de acompanhar.", "Sobrevivendo ao Horror"),
  ritual("Mutar", "Energia", 3, "Altera ou suprime sons dentro da área escolhida.", "Sobrevivendo ao Horror"),
  ritual("Milagre Ionizante", "Energia", 3, "Manipula carga elétrica para energizar, interromper ou restaurar tecnologia.", "Sobrevivendo ao Horror"),
  // Arquivos Secretos #2 — rituais apresentados para uso em mesa
  ritual("Mapa Sanguíneo", "Sangue", 2, "Marca uma superfície e revela em tempo real a posição de seres dentro de uma grande região; cada alvo pode resistir.", "Arquivos Secretos #2", { page: "65", execution: "Padrão", range: "Toque", target: "1 superfície", duration: "Cena", resistance: "Vontade evita", enhancements: ["Discente (+3 PE): também indica a condição geral dos alvos afetados."] }),
  ritual("Capturar Momento", "Morte", 2, "Registra em um símbolo os seres percebidos dentro de uma região; versões avançadas permitem liberar Energia entrópica sobre os alvos registrados.", "Arquivos Secretos #2", { page: "66", execution: "Padrão", range: "Médio", target: "Esfera de 18 m de raio", duration: "Cena", resistance: "Permanece até ser dissipado", enhancements: ["Discente (+3 PE): libera o símbolo para causar dano de Morte na área.", "Verdadeiro (+7 PE): aumenta o dano; exige 3º círculo."] }),
  ritual("Labirinto Mental", "Conhecimento", 2, "Aprisiona a atenção de uma pessoa em um labirinto mental e limita suas ações enquanto ela não conseguir resistir.", "Arquivos Secretos #2", { page: "66", execution: "Padrão", range: "Médio", target: "1 pessoa", duration: "1d4 rodadas", resistance: "Vontade evita", enhancements: ["Discente (+3 PE): aumenta o alcance para longo.", "Verdadeiro (+7 PE): aumenta o alcance e a duração; exige 3º círculo."] }),
  ritual("Rajada Caótica", "Energia", 2, "Projeta uma descarga de Energia contra um alvo; Reflexos reduz o dano à metade.", "Arquivos Secretos #2", { page: "67", execution: "Padrão", range: "Médio", target: "1 ser", duration: "Instantânea", resistance: "Reflexos reduz à metade", enhancements: ["Discente (+3 PE): aumenta os dados de dano."] }),
  ritual("Passagem de Conhecimento", ["Sangue", "Conhecimento"], 2, "Transfere a consciência do conjurador para outra pessoa ou troca as consciências entre os dois corpos. Cada participante mantém sua ficha, mas usa os atributos físicos do corpo ocupado.", "Arquivos Secretos #1", { page: "48", execution: "Completa", range: "Toque", target: "1 pessoa", duration: "Cena", resistance: "Vontade evita", details: ["Na sobreposição, o corpo do conjurador fica inconsciente e o alvo pode repetir a resistência para recuperar o controle.", "Na troca completa, cada consciência permanece no outro corpo até o efeito terminar ou o ritual desfazer a troca."], enhancements: ["Discente (+3 PE): alcance curto, duração de 1 dia e menos tentativas de recuperar o controle.", "Verdadeiro (+7 PE): alcance médio e duração permanente; exige 4º círculo e afinidade."] }),
  ritual("Passagem de Conhecimento Expandido", ["Sangue", "Conhecimento"], 4, "Realiza uma troca permanente de consciências entre dois grupos, sempre com quantidade par de participantes. Os envolvidos passam a usar atributos e habilidades dos novos corpos.", "Arquivos Secretos #1", { page: "50", execution: "1 dia", range: "Curto", target: "2 a 10 pessoas, em número par", duration: "Permanente", resistance: "Não indicada", requirement: "Conhecer Passagem de Conhecimento", details: ["Os participantes são divididos em dois grupos e cada integrante do grupo principal é ligado a alguém do outro.", "Para recuperar os corpos originais, o ritual deve ser realizado novamente com os envolvidos presentes."] }),
];

export const ABILITY_CATEGORIES = ["Sobrevivente", "Combatente", "Especialista", "Ocultista", "Gerais", "Origens", "Poderes Paranormais"];
export const RITUAL_ELEMENTS = ["Conhecimento", "Energia", "Morte", "Sangue", "Medo"];
export const RITUAL_CIRCLES = [1, 2, 3, 4];

export function allSelectableAbilities(origins = []) {
  const originAbilities = origins.map((origin) => {
    const [summary = `Habilidade concedida pela origem ${origin.name}.`, cost = "Passivo"] = ORIGIN_POWER_DETAILS[origin.power] ?? [];
    return ability({
      name: origin.power,
      category: "Origens",
      group: origin.name,
      summary,
      cost,
      requirement: `Origem ${origin.name}`,
      source: origin.source,
    });
  });
  return [...CLASS_POWERS, ...TRAIL_ABILITIES, ...GENERAL_POWERS, ...PARANORMAL_POWERS, ...originAbilities];
}
