// Catálogo de ameaças (mestre) — fichas de combate para o mestre consultar.
// Cada entrada é um resumo mecânico em texto próprio, nunca o parágrafo do
// livro; números conferidos visualmente contra o PDF (nunca inventados).
// Ver docs/threats-audit.md para o método de extração e o progresso por livro.

const slug = (value) =>
  String(value)
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");

// Ordem em que as abas de elemento aparecem na tela de Ameaças. "Realidade"
// não é um elemento do jogo — é o balde do próprio livro para ameaças
// mundanas (pessoas, animais) que fecham o capítulo de ameaças.
export const THREAT_ELEMENT_ORDER = ["Conhecimento", "Energia", "Morte", "Sangue", "Medo", "Realidade"];

export const THREAT_SIZES = ["Minúsculo", "Pequeno", "Médio", "Grande", "Enorme", "Colossal"];

// d20 é sempre a mesma face nesta mecânica: cada teste/perícia da ameaça é
// "dice" dados de 20 (o grau de treinamento dela) mais um bônus fixo.
function test(dice, bonus) {
  return { dice, bonus };
}

function threat({
  name,
  element,
  secondaryElements = [],
  category = "Criatura",
  size = "Médio",
  vd,
  presencaPerturbadora = null,
  enigmaDoMedo = "",
  percepcao = null,
  iniciativa = null,
  sentidosExtras = [],
  defesa,
  fortitude = null,
  reflexos = null,
  vontade = null,
  pontosDeVida,
  machucadoEm = null,
  resistencias = [],
  vulnerabilidades = [],
  imunidadesDano = [],
  imunidadesCondicoes = [],
  atributos,
  pericias = [],
  deslocamentoMetros,
  deslocamentoQuadrados,
  habilidadesPassivas = [],
  acoes = [],
  descricao,
  source = "Livro base",
  page = "",
}) {
  return {
    id: slug(`ameaca-${source}-${name}`),
    name,
    element,
    secondaryElements,
    category,
    size,
    vd,
    presencaPerturbadora,
    enigmaDoMedo,
    percepcao,
    iniciativa,
    sentidosExtras,
    defesa,
    fortitude,
    reflexos,
    vontade,
    pontosDeVida,
    machucadoEm: machucadoEm ?? (typeof pontosDeVida === "number" ? Math.floor(pontosDeVida / 2) : null),
    resistencias,
    vulnerabilidades,
    imunidadesDano,
    imunidadesCondicoes,
    atributos,
    pericias,
    deslocamentoMetros,
    deslocamentoQuadrados,
    habilidadesPassivas,
    acoes,
    descricao,
    source,
    page,
  };
}

export const THREATS = [
  threat({
    name: "Aberração de Carne",
    element: "Sangue",
    category: "Criatura",
    size: "Grande",
    vd: 40,
    presencaPerturbadora: { dt: 15, dado: "3d6", tipo: "mental", imuneDesdeNex: 30 },
    percepcao: test(1, 5),
    iniciativa: test(1, 0),
    sentidosExtras: ["Percepção às cegas"],
    defesa: 19,
    fortitude: test(1, 10),
    reflexos: test(1, 0),
    vontade: test(1, 0),
    pontosDeVida: 70,
    resistencias: [
      { tipos: ["Balístico", "Impacto", "Perfuração"], valor: 5 },
      { tipos: ["Sangue"], valor: 10 },
    ],
    vulnerabilidades: ["Morte"],
    atributos: { agi: 1, for: 3, int: 0, pre: 1, vig: 3 },
    deslocamentoMetros: 9,
    deslocamentoQuadrados: 6,
    acoes: [
      {
        tipo: "Padrão",
        nome: "Agredir",
        ataques: [
          { nome: "Pancada", execucao: "Corpo a corpo x2", teste: test(1, 10), dano: { formula: "2d6+6", tipo: "impacto" } },
        ],
      },
      {
        tipo: "Reação",
        nome: "Agarrão",
        descricao: "Se a aberração de carne acertar um ataque de pancada, ela pode tentar agarrar o alvo (teste 1d20+12). Ela pode manter até dois personagens agarrados por vez.",
      },
      {
        tipo: "Movimento",
        nome: "Abocanhar",
        descricao: "A aberração de carne leva até dois personagens agarrados para dentro de sua boca central, que são abocanhados e continuam agarrados. Quando é abocanhado, e no início de cada turno da aberração em que continuar agarrado desta forma, o personagem sofre 3d6 pontos de dano de perfuração (Fortitude DT 15 reduz à metade). Qualquer personagem adjacente pode gastar uma ação padrão e um teste de Atletismo (DT 20) para tentar tirar outro personagem de dentro da boca.",
      },
    ],
    descricao: "Dois corpos fundidos por um experimento fracassado, mantidos conscientes até a dor virar fúria. Uma boca central abre no meio do que sobrou dos estômagos, cercada por braços e pernas em excesso.",
    source: "Livro base",
    page: "182",
  }),
  threat({
    name: "Carente",
    element: "Sangue",
    secondaryElements: ["Morte"],
    category: "Criatura",
    size: "Grande",
    vd: 300,
    presencaPerturbadora: { dt: 35, dado: "7d8", tipo: "mental", imuneDesdeNex: 90 },
    percepcao: test(3, 10),
    iniciativa: test(4, 15),
    sentidosExtras: ["Percepção às cegas"],
    defesa: 40,
    fortitude: test(4, 25),
    reflexos: test(4, 25),
    vontade: test(3, 15),
    pontosDeVida: 700,
    resistencias: [{ tipos: ["Balístico", "Impacto", "Perfuração", "Sangue"], valor: 20 }],
    vulnerabilidades: ["Morte"],
    atributos: { agi: 4, for: 4, int: 2, pre: 3, vig: 4 },
    pericias: [
      { nome: "Atletismo", teste: test(4, 20) },
      { nome: "Enganação", teste: test(3, 15) },
    ],
    deslocamentoMetros: 12,
    deslocamentoQuadrados: 8,
    habilidadesPassivas: [
      { nome: "Carência", descricao: "Qualquer ser que já esteve envolvido na gestação de outro ser recebe +1d20 em ataques contra o carente, porém o carente também recebe +1d20 em ataques contra esse ser." },
      { nome: "Regeneração de Sangue", descricao: "O carente possui Cura Acelerada 20. Se ficar inconsciente ou sofrer dano de Energia, esta habilidade deixa de funcionar até o fim da cena." },
    ],
    acoes: [
      {
        tipo: "Padrão",
        nome: "Agredir",
        ataques: [
          { nome: "Garras de Sangue", execucao: "Corpo a corpo x2", teste: test(4, 35), dano: { formula: "2d8+20", tipo: "Sangue" } },
          { nome: "Ferrão de Sangue", execucao: "Corpo a corpo", teste: test(4, 35), dano: { formula: "2d12+20", tipo: "Sangue" } },
          { nome: "Tentáculo", execucao: "Corpo a corpo", teste: test(4, 35), dano: { formula: "2d8+20", tipo: "Sangue" } },
        ],
      },
      {
        tipo: "Movimento",
        nome: "Forma Infantil",
        descricao: "O carente se contorce de volta para o corpo da pequena criança para passar em espaços pequenos, se retraindo e expandindo quando achar necessário. Não consegue abrir a primeira porta para entrar num lugar; uma vez que essa porta é aberta e ele deixa a forma infantil, pode ignorar essa restrição.",
      },
      {
        tipo: "Reação",
        nome: "Rasteira de Tentáculo",
        descricao: "Uma vez por rodada, quando fica adjacente a dois ou mais seres, o carente faz um ataque de tentáculo contra um deles. Se acertar, a vítima fica caída e é empurrada 6m para longe dele.",
      },
      {
        tipo: "Livre",
        nome: "Sugada Mortal",
        descricao: "Usando seu ferrão, o carente consegue sugar fluidos e apodrecer os órgãos internos. Um ser atingido pelo ferrão de sangue fica debilitado e enjoado até o fim da cena (Fortitude DT 35 evita).",
      },
      {
        tipo: "Movimento",
        nome: "Você É Minha Mamãe?",
        descricao: "O carente usa a parte que simula o corpo de uma criança para abraçar um ser adjacente, que fica paralisado até ser solto (Reflexos DT 25 evita). O carente pode manter o abraço indefinidamente, mas é forçado a soltar o alvo se sofrer dano de Energia.",
      },
    ],
    descricao: "Nascido da inveja de quem nunca sentiu amor, finge ser uma criança perdida batendo à porta para conseguir entrar. O que sai de dentro do rosto vazio não tem nada de infantil.",
    source: "Livro base",
    page: "188",
  }),
  threat({
    name: "Aniquilação",
    element: "Sangue",
    secondaryElements: ["Medo"],
    category: "Criatura",
    size: "Colossal",
    vd: 380,
    presencaPerturbadora: { dt: 45, dado: "9d8", tipo: "mental", imuneDesdeNex: null },
    enigmaDoMedo: "Desconhecido. Ao ser resolvido, a Aniquilação perde sua resistência a dano e a habilidade Tempestade de Espinhos.",
    percepcao: test(4, 20),
    iniciativa: test(4, 20),
    sentidosExtras: ["Percepção às cegas"],
    defesa: 58,
    fortitude: test(5, 30),
    reflexos: test(4, 25),
    vontade: test(4, 20),
    pontosDeVida: 1200,
    resistencias: [{ tipos: ["Geral"], valor: 50 }],
    vulnerabilidades: ["Morte"],
    atributos: { agi: 4, for: 5, int: 3, pre: 4, vig: 5 },
    pericias: [{ nome: "Atletismo", teste: test(5, 20) }],
    deslocamentoMetros: 15,
    deslocamentoQuadrados: 10,
    acoes: [
      {
        tipo: "Padrão",
        nome: "Agredir",
        ataques: [
          { nome: "Garras", execucao: "Corpo a corpo x2", teste: test(5, 40), dano: { formula: "4d10+30", tipo: "Sangue" } },
          { nome: "Tentáculos Espinhentos", execucao: "Corpo a corpo x2", teste: test(5, 40), dano: { formula: "2d12+30", tipo: "Sangue" } },
        ],
      },
      {
        tipo: "Padrão",
        nome: "Agredir",
        ataques: [
          { nome: "Disparo de Espinhos", execucao: "Distância x3, alcance médio", teste: test(4, 40), dano: { formula: "2d10+20", tipo: "Sangue" } },
        ],
      },
      {
        tipo: "Reação",
        nome: "Agarrão",
        descricao: "Se a Aniquilação acertar um ataque de tentáculos espinhentos, pode tentar agarrar o alvo (teste 5d20+50). Mantém até quatro personagens agarrados por vez.",
      },
      {
        tipo: "Reação",
        nome: "Instinto Aniquilador",
        descricao: "Sempre que um personagem em alcance curto da Aniquilação se move mais de 3m, ela faz um ataque de tentáculos espinhentos contra ele.",
      },
      {
        tipo: "Livre",
        nome: "Apertar e Destruir",
        descricao: "No início do seu turno, a Aniquilação aperta os personagens agarrados com seus tentáculos, causando 40 pontos de dano de Sangue.",
      },
      {
        tipo: "Movimento",
        nome: "Bater as Asas",
        descricao: "Cada personagem em alcance longo sofre 8d6 pontos de dano mental, é empurrado 6m para longe da Aniquilação e fica atordoado por uma rodada (Fortitude DT 40 reduz o dano à metade e evita os efeitos).",
      },
      {
        tipo: "Movimento",
        nome: "Estrangulamento Final",
        descricao: "A Aniquilação se desloca 15m enquanto seus braços agarram e estrangulam. Cada personagem que fica adjacente a ela durante esse deslocamento fica agarrado e asfixiado (Reflexos DT 30 evita). Um agarrado pode escapar gastando uma ação padrão e passando num teste de Reflexos (DT 30).",
      },
      {
        tipo: "Completa",
        nome: "Tempestade de Espinhos",
        descricao: "A Aniquilação lança todos os seus espinhos: todos os personagens em alcance médio sofrem 20d6+20 pontos de dano de Sangue (Reflexos DT 40 reduz à metade). Só pode usar uma vez por cena e, ao usar, perde o Disparo de Espinhos até o fim da cena.",
      },
    ],
    descricao: "A maior criatura já registrada na história da Realidade — incontáveis braços menores brotando de braços maiores, e no centro do corpo uma bocarra com dentes do tamanho de pessoas adultas. Ninguém registra tê-la derrotado; talvez só esteja dormente.",
    source: "Livro base",
    page: "185",
  }),
  threat({
    name: "Dama de Sangue",
    element: "Sangue",
    secondaryElements: ["Morte", "Medo"],
    category: "Criatura",
    size: "Enorme",
    vd: 60,
    presencaPerturbadora: { dt: 20, dado: "3d6", tipo: "mental", imuneDesdeNex: 35 },
    enigmaDoMedo: "Invocada por um ritual que sacrifica sete pessoas para fazer desabrochar sete flores. Cada flor tem sua própria fraqueza, descrita junto da habilidade que ela concede.",
    percepcao: test(2, 10),
    iniciativa: test(2, 0),
    sentidosExtras: ["Percepção às cegas"],
    defesa: 20,
    fortitude: test(2, 10),
    reflexos: test(2, 5),
    vontade: test(2, 0),
    pontosDeVida: 105,
    resistencias: [
      { tipos: ["Balístico", "Impacto", "Perfuração"], valor: 10 },
      { tipos: ["Sangue"], valor: 20 },
    ],
    vulnerabilidades: ["Morte"],
    atributos: { agi: 2, for: 3, int: 1, pre: 2, vig: 2 },
    deslocamentoMetros: 12,
    deslocamentoQuadrados: 8,
    habilidadesPassivas: [
      { nome: "Consumir", descricao: "Ao ser invocada, a dama de Sangue ainda não tem as sete habilidades das flores. Cada corpo que consome (ação padrão, adjacente a um cadáver) concede a próxima habilidade da lista, na ordem: Arremessar, Chuva de Ácido, Espinhos, Grito Devastador, Miasma Fétido, Prisão de Tentáculos, Visão Macabra. Enquanto não tiver consumido sete corpos, gasta seu turno se deslocando até um cadáver para consumi-lo." },
    ],
    acoes: [
      {
        tipo: "Padrão",
        nome: "Agredir",
        ataques: [{ nome: "Tentáculo", execucao: "Corpo a corpo x2", teste: test(3, 10), dano: { formula: "2d6+5", tipo: "impacto" } }],
      },
      {
        tipo: "Movimento",
        nome: "Arremessar (Flor Rosa)",
        descricao: "Ergue um personagem em alcance curto e o arremessa a um ponto também em alcance curto: sofre 2d6 de dano de impacto e cai (Reflexos DT 15 evita tudo). A flor murcha se a dama entrar em contato com fertilizante, perdendo esta habilidade e sofrendo −1d20 em Luta.",
      },
      {
        tipo: "Movimento",
        nome: "Chuva de Ácido (Flor Vermelha)",
        descricao: "Espirra ácido em alcance curto: 4d4 de dano químico (Fortitude DT 15 reduz à metade). Murcha com contato com agrotóxico, perdendo esta habilidade e reduzindo suas resistências a dano em 5.",
      },
      {
        tipo: "Movimento",
        nome: "Espinhos (Flor Amarela)",
        descricao: "Dispara espinhos em até três alvos em alcance médio: 2d8 de dano de perfuração cada (Reflexos DT 15 reduz à metade). Murcha se a dama sofrer 10+ de dano de fogo de um único efeito, perdendo esta habilidade e sofrendo −1d20 em Reflexos.",
      },
      {
        tipo: "Movimento",
        nome: "Grito Devastador (Flor Roxa)",
        descricao: "Grito que causa confusão em todos em alcance curto (Vontade DT 15 evita; quem falha pode repetir o teste no fim do turno). Murcha com contato com o bulbo de bravo purpuris, perdendo esta habilidade e sofrendo −1d20 em Vontade.",
      },
      {
        tipo: "Padrão",
        nome: "Miasma Fétido (Flor Azul)",
        descricao: "Miasma que contamina o ar em alcance curto: enjoo por 1d4+1 rodadas (Fortitude DT 15 reduz a 1 rodada). Murcha se a dama sofrer dano de eletricidade ou Energia, perdendo esta habilidade e reduzindo seu deslocamento em 6m.",
      },
      {
        tipo: "Padrão",
        nome: "Prisão de Tentáculos (Flor Verde)",
        descricao: "Tentáculos prendem um personagem escolhido em alcance curto até que sejam destruídos (acerto automático, 20 PV). Murcha se molhada em água corrente, perdendo esta habilidade e reduzindo sua Defesa em 5.",
      },
      {
        tipo: "Movimento",
        nome: "Visão Macabra (Flor Laranja)",
        descricao: "Movimento hipnotizante que causa delírios: todos em alcance médio sofrem 1d6 de dano mental (Vontade DT 15 reduz à metade). Murcha se a dama sofrer 10+ de dano de corte de um único efeito, perdendo esta habilidade e reduzindo seus PV totais em 20.",
      },
    ],
    descricao: "Nasce de um corpo humano partido ao meio, com sete tentáculos floridos e um oitavo, maior, com uma flor dentada no lugar da boca. Cada flor concede um poder diferente — e cada uma tem sua própria fraqueza secreta.",
    source: "Livro base",
    page: "190",
  }),
  threat({
    name: "Enpap-X",
    element: "Sangue",
    secondaryElements: ["Conhecimento"],
    category: "Criatura",
    size: "Grande",
    vd: 180,
    presencaPerturbadora: { dt: 25, dado: "6d6", tipo: "mental", imuneDesdeNex: 60 },
    percepcao: test(2, 10),
    iniciativa: test(2, 10),
    sentidosExtras: ["Percepção às cegas"],
    defesa: 36,
    fortitude: test(3, 15),
    reflexos: test(2, 15),
    vontade: test(2, 10),
    pontosDeVida: 360,
    resistencias: [
      { tipos: ["Balístico", "Impacto", "Perfuração"], valor: 10 },
      { tipos: ["Sangue"], valor: 20 },
    ],
    vulnerabilidades: ["Morte"],
    atributos: { agi: 2, for: 4, int: 1, pre: 2, vig: 3 },
    deslocamentoMetros: 12,
    deslocamentoQuadrados: 8,
    habilidadesPassivas: [
      { nome: "Transformação", descricao: "O enpap-X começa o combate como um existido comum (ficha própria, fora deste catálogo). Ao ser reduzido a 0 PV, em vez de morrer, se transforma: passa a usar esta ficha (incluindo a Presença Perturbadora) e recupera todos os PV, ficando com 360." },
    ],
    acoes: [
      {
        tipo: "Padrão",
        nome: "Agredir",
        ataques: [{ nome: "Socão", execucao: "Corpo a corpo x4", teste: test(4, 20), dano: { formula: "2d10+10", tipo: "impacto" } }],
      },
      {
        tipo: "Padrão",
        nome: "Agredir",
        ataques: [{ nome: "Correntes", execucao: "Distância x3, alcance curto", teste: test(2, 15), dano: { formula: "2d8+10", tipo: "impacto" } }],
      },
      {
        tipo: "Livre",
        nome: "Acorrentar",
        descricao: "Se acertar um ataque de correntes num personagem Médio ou menor, pode tentar agarrá-lo à distância (teste 2d20+17). No início do seu turno, estrangula cada agarrado desta forma, causando 4d6 de dano de impacto. Mantém até dois agarrados simultaneamente.",
      },
      {
        tipo: "Reação",
        nome: "Forma Desencadeada",
        descricao: "Ao acertar crítico com um socão ou com uma corrente, pode derrubar o alvo ou empurrá-lo 3m na direção oposta.",
      },
      {
        tipo: "Reação",
        nome: "Crescer",
        descricao: "Sempre que acerta um personagem com o socão, recebe um bônus cumulativo de +1d6 em suas próximas rolagens de dano até o fim do turno: +1d6 no segundo acerto, +2d6 no terceiro, +3d6 no quarto.",
      },
      {
        tipo: "Movimento",
        nome: "Marcas do Terror",
        descricao: "Marcas em seu corpo brilham, revelando atrocidades. Todos em alcance curto sofrem 4d6 de dano mental (Vontade DT 25 reduz à metade); quem resiste fica imune a esta habilidade até o fim da cena.",
      },
    ],
    descricao: "Um existido comum tomado por dentro pelo Sangue, que só revela sua verdadeira forma — correntes, socos que crescem em força e marcas de atrocidades gravadas na pele — depois de ser derrotado uma primeira vez.",
    source: "Livro base",
    page: "192",
  }),
  threat({
    name: "Kerberos",
    element: "Sangue",
    category: "Criatura",
    size: "Enorme",
    vd: 340,
    presencaPerturbadora: { dt: 35, dado: "10d6", tipo: "mental", imuneDesdeNex: 99 },
    percepcao: test(3, 20),
    iniciativa: test(4, 15),
    sentidosExtras: ["Percepção às cegas"],
    defesa: 46,
    fortitude: test(5, 25),
    reflexos: test(4, 20),
    vontade: test(3, 15),
    pontosDeVida: 1150,
    resistencias: [
      { tipos: ["Balístico", "Impacto", "Perfuração"], valor: 20 },
      { tipos: ["Sangue"], valor: 20 },
    ],
    vulnerabilidades: ["Morte"],
    atributos: { agi: 4, for: 5, int: 0, pre: 3, vig: 5 },
    pericias: [{ nome: "Atletismo", teste: test(5, 25) }],
    deslocamentoMetros: 18,
    deslocamentoQuadrados: 12,
    habilidadesPassivas: [
      { nome: "Ataque Flexível", descricao: "O kerberos pode executar até quatro ataques por rodada, combinando ataques corpo a corpo e à distância, mas nunca repetindo o mesmo ataque mais de três vezes na mesma rodada." },
    ],
    acoes: [
      {
        tipo: "Padrão",
        nome: "Agredir",
        ataques: [{ nome: "Mordida", execucao: "Corpo a corpo", teste: test(5, 40), dano: { formula: "4d12+30", tipo: "Sangue" } }],
      },
      {
        tipo: "Padrão",
        nome: "Agredir",
        ataques: [{ nome: "Disparo de Espinhos", execucao: "Distância, alcance médio", teste: test(4, 35), dano: { formula: "4d8+20", tipo: "Sangue" } }],
      },
      {
        tipo: "Livre",
        nome: "Devorar",
        descricao: "Uma vez por cena, ao reduzir os PV de um personagem a 0 com sua mordida, pode devorá-lo, matando-o instantaneamente e recuperando PV iguais à metade dos PV totais da vítima. A vítima pode evitar com um teste de Fortitude (DT 40).",
      },
      {
        tipo: "Completa",
        nome: "Derrubar e Devorar",
        descricao: "Usa a manobra derrubar num personagem a até 3m (teste 5d20+45). Se vencer, desfere três ataques de mordida contra ele, com o dano de cada um aumentado para 4d12+40.",
      },
    ],
    descricao: "O cão de três cabeças, guardião de uma entrada paranormal importante, só existe dentro de um \"Inferno\" — uma área devastada pelo Sangue. Ilógico e imparável, mas preso a proteger um único ponto.",
    source: "Livro base",
    page: "194",
  }),
  threat({
    name: "Minotauro",
    element: "Sangue",
    category: "Criatura",
    size: "Grande",
    vd: 280,
    presencaPerturbadora: { dt: 35, dado: "8d6", tipo: "mental", imuneDesdeNex: 80 },
    percepcao: test(3, 20),
    iniciativa: test(4, 15),
    sentidosExtras: ["Percepção às cegas"],
    defesa: 44,
    fortitude: test(5, 20),
    reflexos: test(4, 15),
    vontade: test(3, 10),
    pontosDeVida: 750,
    resistencias: [
      { tipos: ["Balístico", "Impacto", "Perfuração"], valor: 20 },
      { tipos: ["Sangue"], valor: 20 },
    ],
    vulnerabilidades: ["Morte"],
    atributos: { agi: 4, for: 5, int: 1, pre: 3, vig: 5 },
    pericias: [{ nome: "Atletismo", teste: test(5, 20) }],
    deslocamentoMetros: 12,
    deslocamentoQuadrados: 8,
    acoes: [
      {
        tipo: "Padrão",
        nome: "Agredir",
        ataques: [
          { nome: "Chifres", execucao: "Corpo a corpo", teste: test(5, 30), dano: { formula: "6d12+20", tipo: "perfuração" } },
          { nome: "Machado", execucao: "Corpo a corpo x2", teste: test(5, 32), dano: { formula: "4d12+20", tipo: "corte" } },
        ],
      },
      {
        tipo: "Livre",
        nome: "Cravar Chifres",
        descricao: "Se acertar uma investida com os chifres, o alvo fica agarrado por eles. Enquanto mantém alguém agarrado assim não pode atacar com os chifres, mas no fim de cada turno da vítima ainda agarrada, ela sofre 4d12+20 de dano de Sangue.",
      },
    ],
    descricao: "Um animal enorme e bípede, infectado com pústulas de Sangue de um lado inteiro do corpo, com um machado fundido ao braço esquerdo. Vive em labirintos e já foi mantido em cativeiro para estudo, por razões que ninguém explica.",
    source: "Livro base",
    page: "197",
  }),
  threat({
    name: "Mulher Afogada",
    element: "Sangue",
    secondaryElements: ["Energia", "Medo"],
    category: "Criatura",
    size: "Grande",
    vd: 140,
    presencaPerturbadora: { dt: 25, dado: "4d8", tipo: "mental", imuneDesdeNex: 50 },
    enigmaDoMedo: "Enquanto o enigma não é resolvido, ela permanece na Forma de Sangue (líquida); depois de resolvido, é invocada em sua forma física e perde essa forma.",
    percepcao: test(2, 5),
    iniciativa: test(4, 10),
    sentidosExtras: ["Percepção às cegas"],
    defesa: 28,
    fortitude: test(3, 10),
    reflexos: test(4, 10),
    vontade: test(2, 5),
    pontosDeVida: 240,
    resistencias: [
      { tipos: ["Balístico", "Energia", "Impacto", "Perfuração"], valor: 10 },
      { tipos: ["Sangue"], valor: 20 },
    ],
    vulnerabilidades: ["Morte"],
    atributos: { agi: 4, for: 3, int: 2, pre: 2, vig: 3 },
    deslocamentoMetros: 9,
    deslocamentoQuadrados: 6,
    habilidadesPassivas: [
      { nome: "Forma de Sangue", descricao: "Por padrão, é encontrada como líquido de Sangue: nessa forma tem deslocamento 36m/24 quadrados, pode se mover por canos, frestas e orifícios como qualquer líquido, e ganha as habilidades Afogar em Sangue, Arrancar Sangue e Invadir Órgãos." },
    ],
    acoes: [
      {
        tipo: "Padrão",
        nome: "Agredir",
        ataques: [
          { nome: "Mordida", execucao: "Corpo a corpo", teste: test(3, 15), dano: { formula: "4d8+8", tipo: "perfuração" } },
          { nome: "Garras", execucao: "Corpo a corpo x2", teste: test(3, 15), dano: { formula: "4d6+6", tipo: "corte" } },
        ],
      },
      {
        tipo: "Padrão",
        nome: "Agredir",
        ataques: [{ nome: "Jato de Sangue", execucao: "Distância, alcance curto", teste: test(4, 10), dano: { formula: "4d8+8", tipo: "Sangue" } }],
      },
      {
        tipo: "Movimento",
        nome: "Sugar Sangue",
        descricao: "Devora o corpo de um personagem adjacente que tenha morrido nesta cena, recuperando 40 PV.",
      },
      {
        tipo: "Padrão",
        nome: "Afogar em Sangue (Forma de Sangue)",
        descricao: "Invade nariz e boca de um personagem em alcance curto, afogando-o com Sangue; ele fica asfixiado. No início de cada um dos seus turnos, pode testar Fortitude (DT 24) para encerrar a condição e expelir a mulher afogada para um espaço adjacente.",
      },
      {
        tipo: "Reação",
        nome: "Arrancar Sangue (Forma de Sangue)",
        descricao: "Toda vez que é arrancada de um corpo que está afogando, carrega parte do sangue da vítima, causando 6d6 de dano de Sangue e deixando-a fraca.",
      },
      {
        tipo: "Movimento",
        nome: "Invadir Órgãos (Forma de Sangue)",
        descricao: "Invade órgãos vitais de um personagem que está asfixiando: ele sofre 6d6 de dano de Sangue e fica enjoado.",
      },
    ],
    descricao: "Encontrada como um líquido vermelho capaz de escorrer por canos e frestas, invade quem se aproxima demais da água. \"Se deixar a torneira aberta, a mulher afogada desperta.\"",
    source: "Livro base",
    page: "199",
  }),
  threat({
    name: "Titã de Sangue",
    element: "Sangue",
    category: "Criatura",
    size: "Enorme",
    vd: 220,
    presencaPerturbadora: { dt: 30, dado: "7d6", tipo: "mental", imuneDesdeNex: 70 },
    percepcao: test(1, 15),
    iniciativa: test(2, 10),
    sentidosExtras: ["Percepção às cegas"],
    defesa: 35,
    fortitude: test(4, 15),
    reflexos: test(2, 10),
    vontade: test(1, 10),
    pontosDeVida: 550,
    resistencias: [
      { tipos: ["Balístico", "Impacto", "Perfuração"], valor: 20 },
      { tipos: ["Sangue"], valor: 20 },
    ],
    vulnerabilidades: ["Morte"],
    atributos: { agi: 2, for: 5, int: 1, pre: 1, vig: 4 },
    deslocamentoMetros: 12,
    deslocamentoQuadrados: 8,
    habilidadesPassivas: [
      { nome: "Sede de Sangue", descricao: "Os ataques do titã causam +4d6 de dano de Sangue em personagens que estejam machucados ou sangrando." },
    ],
    acoes: [
      {
        tipo: "Padrão",
        nome: "Agredir",
        ataques: [
          { nome: "Mordida", execucao: "Corpo a corpo", teste: test(5, 25), dano: { formula: "4d12+10", tipo: "perfuração" } },
          { nome: "Garras", execucao: "Corpo a corpo x2", teste: test(5, 25), dano: { formula: "4d8+10", tipo: "corte" } },
        ],
      },
      {
        tipo: "Livre",
        nome: "Estraçalhar",
        descricao: "Se acertar um ser com a mordida, ele é estraçalhado: sofre 4d12+10 de dano de perfuração adicional e fica sangrando até o fim da cena (Reflexos DT 30 reduz o dano à metade e evita a condição).",
      },
    ],
    descricao: "Um colosso de braços grossos e uma boca cravejada de presas amareladas, movido só pela sede pelo sangue de quem já está ferido.",
    source: "Livro base",
    page: "201",
  }),
  threat({
    name: "Zumbi de Sangue",
    element: "Sangue",
    category: "Criatura",
    size: "Médio",
    vd: 20,
    presencaPerturbadora: { dt: 15, dado: "2d6", tipo: "mental", imuneDesdeNex: 25 },
    percepcao: test(1, 10),
    iniciativa: test(2, 5),
    sentidosExtras: ["Percepção às cegas"],
    defesa: 17,
    fortitude: test(2, 5),
    reflexos: test(2, 5),
    vontade: test(1, 5),
    pontosDeVida: 45,
    resistencias: [
      { tipos: ["Balístico", "Impacto", "Perfuração"], valor: 5 },
      { tipos: ["Sangue"], valor: 10 },
    ],
    vulnerabilidades: ["Morte"],
    atributos: { agi: 2, for: 2, int: 0, pre: 1, vig: 2 },
    deslocamentoMetros: 9,
    deslocamentoQuadrados: 6,
    acoes: [
      {
        tipo: "Padrão",
        nome: "Agredir",
        ataques: [{ nome: "Garras", execucao: "Corpo a corpo x2", teste: test(2, 5), dano: { formula: "1d6+5", tipo: "corte" } }],
      },
    ],
    descricao: "Um cadáver morto de forma brutal, tomado pelo Sangue como passagem para devorar carne. Cego, cru e cego de raiva, sente o ar se mover para encontrar suas vítimas.",
    source: "Livro base",
    page: "202",
  }),
  threat({
    name: "Zumbi de Sangue Bestial",
    element: "Sangue",
    category: "Criatura",
    size: "Grande",
    vd: 100,
    presencaPerturbadora: { dt: 20, dado: "4d6", tipo: "mental", imuneDesdeNex: 45 },
    percepcao: test(2, 10),
    iniciativa: test(2, 15),
    defesa: 23,
    fortitude: test(3, 10),
    reflexos: test(2, 5),
    vontade: test(2, 5),
    pontosDeVida: 200,
    resistencias: [
      { tipos: ["Balístico", "Impacto", "Perfuração"], valor: 5 },
      { tipos: ["Sangue"], valor: 10 },
    ],
    vulnerabilidades: ["Morte"],
    atributos: { agi: 2, for: 3, int: 0, pre: 2, vig: 3 },
    pericias: [{ nome: "Furtividade", teste: test(2, 13) }],
    deslocamentoMetros: 12,
    deslocamentoQuadrados: 8,
    habilidadesPassivas: [
      { nome: "Furtivo e Letal", descricao: "Contra um alvo desprevenido, recebe +1d20 nos testes de ataque e, se acertar, cada ataque causa dois dados de dano adicional do mesmo tipo." },
      { nome: "Instinto Predatório", descricao: "Não sofre penalidade em Furtividade por se mover no seu deslocamento normal." },
    ],
    acoes: [
      {
        tipo: "Padrão",
        nome: "Agredir",
        ataques: [
          { nome: "Mordida de Sangue", execucao: "Corpo a corpo", teste: test(3, 15), dano: { formula: "2d10+5", tipo: "perfuração" } },
          { nome: "Garras de Sangue", execucao: "Corpo a corpo x2", teste: test(3, 15), dano: { formula: "2d6+5", tipo: "corte" } },
        ],
      },
    ],
    descricao: "Versão maior e mais estratégica do zumbi de Sangue, com massa triplicada e o crânio partido ao meio virando uma bocarra só. Prefere se esconder e esperar antes de atacar.",
    source: "Livro base",
    page: "203",
  }),
  threat({
    name: "O Diabo",
    element: "Sangue",
    secondaryElements: ["Conhecimento", "Medo"],
    category: "Criatura",
    size: "Médio",
    vd: 400,
    presencaPerturbadora: { dt: 45, dado: "10d8", tipo: "mental", imuneDesdeNex: null },
    enigmaDoMedo: "Chamado de Máscara do Desespero: só a intensidade dos próprios sentimentos do Diabo é capaz de romper a calmaria do Equilíbrio e resolvê-lo.",
    percepcao: test(6, 25),
    iniciativa: test(6, 35),
    sentidosExtras: ["Percepção às cegas"],
    defesa: 66,
    fortitude: test(6, 35),
    reflexos: test(6, 35),
    vontade: test(6, 35),
    pontosDeVida: 1666,
    resistencias: [{ tipos: ["Balístico", "Impacto", "Perfuração"], valor: 20 }],
    vulnerabilidades: ["Morte"],
    imunidadesDano: ["Sangue"],
    imunidadesCondicoes: ["Atordoado", "Paralisia"],
    atributos: { agi: 6, for: 6, int: 6, pre: 6, vig: 6 },
    deslocamentoMetros: 18,
    deslocamentoQuadrados: 12,
    habilidadesPassivas: [
      { nome: "Ardiloso", descricao: "O Diabo gosta de fazer pactos e ocasionalmente aparece para pessoas normais. Pode escolher não ativar sua Presença Perturbadora ao encontrar um personagem." },
      { nome: "Potência de Sangue", descricao: "Recupera 50 PV no início de cada um dos seus turnos. Seu modificador para testes de perícia baseados em Força, Vigor ou Presença é +35; para os demais atributos, é +25." },
    ],
    acoes: [
      {
        tipo: "Padrão",
        nome: "Agredir",
        ataques: [
          { nome: "Arma Sangrenta", execucao: "Corpo a corpo x2", teste: test(6, 45), critico: "x3", dano: { formula: "2d10+50", tipo: "Sangue" } },
          { nome: "Chifre do Diabo", execucao: "Corpo a corpo", teste: test(6, 45), critico: "x3", dano: { formula: "2d8+50", tipo: "Sangue" } },
        ],
      },
      {
        tipo: "Padrão",
        nome: "Agredir",
        ataques: [{ nome: "Arma Sangrenta", execucao: "Distância x2, alcance médio", teste: test(6, 45), critico: "x3", dano: { formula: "2d10+50", tipo: "Sangue" } }],
      },
      {
        tipo: "Livre",
        nome: "Explodir em Sangue",
        descricao: "O Diabo controla o sangue de qualquer ser com quem tenha contato direto. Se causar dano usando sua arma sangrenta, ou tocar diretamente numa ferida, causa 10d6 de dano de Sangue. Pode usar esta habilidade duas vezes por turno.",
      },
      {
        tipo: "Livre",
        nome: "Sangrar",
        descricao: "Se acertar com o chifre, pode soltar o apêndice e deixá-lo preso no personagem, que sofre vulnerabilidade a Sangue até removê-lo (ação padrão, causando 8d8 de dano de Sangue). O chifre sempre recresce no início do turno do Diabo.",
      },
      {
        tipo: "Movimento",
        nome: "Transportar pelo Sangue",
        descricao: "Pode se movimentar através do Sangue, inclusive daquele que esteja saindo de dentro de um personagem. Com uma ação de movimento, se desloca para qualquer espaço com grande quantidade de sangue exposta, ou adjacente a um personagem machucado ou morrendo.",
      },
    ],
    descricao: "Conhecido por incontáveis nomes — o Príncipe do Ódio, o Imperador das Aberrações — nunca foi derrotado, controlado ou aprisionado. Maquiavélico, de pele vermelha e chifruda, gosta de fazer pactos com quem já está no limite.",
    source: "Livro base",
    page: "205",
  }),
];

export const THREAT_BY_ID = new Map(THREATS.map((entry) => [entry.id, entry]));
