import { power, origin, trail, item, action, modifier, limit, attribute } from './schema.js';
const p = (page, category, name, text, rules) => power(5, page, category, name, text, rules);

export const AS05_ORIGINS = [
  origin(5, 54, 'Ufólogo', ['Ciências', 'Ocultismo'], 'Minha Teoria Absurda', 'Uma vez por missão, dedique dez minutos a registrar uma hipótese antes de conhecer a solução. Se ela estiver correta ao término da missão, ganhe permanentemente +3 PE máximos e atuais.', {
    actions: [action('teoria', 'Registrar hipótese', 0, '10 minutos', { handler: 'ufologistTheory', limit: limit('mission'), fields: ['theory'] }), action('confirmar', 'Confirmar hipótese ao fim da missão', 0, 'fim da missão', { handler: 'ufologistReward', fields: ['theoryCorrect'] })],
  }),
  origin(5, 54, 'Funcionário de Beira de Estrada', ['Fortitude', 'Intuição'], 'Turno Invertido', 'Uma vez por missão, receba os benefícios de dormir durante um interlúdio sem gastar a ação. Receba +2 para resistir a efeitos que causam inconsciência.', {
    modifiers: [modifier('resistanceTests', 2, 'unconsciousEffect')], actions: [action('descanso', 'Receber descanso', 0, 'interlúdio', { limit: limit('mission'), handler: 'sleep', fields: ['restQuality'] })],
  }),
];
export const AS05_POWERS = [
  p(55, 'Combatente', 'Aura de Confiança', 'Aliados a até 18 m recebem +5 Iniciativa e contra Presença Perturbadora. O próprio usuário não recebe esses bônus.', { modularGroup: 'combate', allyModifiers: [modifier('Iniciativa', 5), modifier('presenceResistance', 5)], radius: 18 }),
  p(55, 'Combatente', 'Fôlego de Emergência', 'Uma vez por cena, enquanto houver uma ameaça, use uma ação de movimento para recuperar 1d8 + VIG de PV ou PE.', { modularGroup: 'combate', actions: [action('folego', 'Recuperar recurso', 0, 'movimento', { handler: 'emergencyBreath', limit: limit('scene'), fields: ['recoveryResource', 'threatPresent'] })] }),
  p(55, 'Combatente', 'Parede de Carne', 'Aliados adjacentes recebem cobertura leve, equivalente a +5 Defesa.', { requirement: 'VIG 3 ou FOR 3', prerequisites: { any: [attribute('vigor', 3), attribute('forca', 3)] }, modularGroup: 'combate', allyModifiers: [modifier('defense', 5, 'adjacent', { bonusType: 'cover' })] }),
  p(55, 'Especialista', 'Adepto do Escuro', 'Ignore camuflagem leve ou total causada por escuridão. Em penumbra, receba +2 Investigação.', { modularGroup: 'combate', ignores: ['darknessConcealment'], modifiers: [modifier('Investigação', 2, 'dimLight')] }),
  p(55, 'Especialista', 'Saudosista Hi-Tech', 'Receba +5 Tecnologia ao lidar com aparelhos anteriores ao ano 2000. Pode integrar esses aparelhos à tecnologia moderna.', { modularGroup: 'utilidade', modifiers: [modifier('Tecnologia', 5, 'pre2000Device')] }),
  p(55, 'Especialista', 'Treinado nas Telas', 'Ao fazer Iniciativa ou Reflexos, gaste 2 PE para usar INT no lugar de AGI.', { cost: '2 PE', modularGroup: 'combate', actions: [action('intelecto', 'Usar Intelecto no teste', 2, 'teste', { handler: 'screenTraining', fields: ['initiativeOrReflexes'] })] }),
  p(56, 'Ocultista', 'Catálogo de Criaturas Ambulante', 'Receba +5 Ocultismo para identificar criaturas. Vestígios da criatura bastam; não precisa vê-la pessoalmente.', { modularGroup: 'utilidade', modifiers: [modifier('Ocultismo', 5, 'identifyCreature')] }),
  p(56, 'Ocultista', 'Meditação Ocultista', 'Uma vez por interlúdio, medite para recuperar PE: normal, duas vezes o limite por turno; precária, metade dessa recuperação; confortável, triplo; luxuosa, quádruplo.', { modularGroup: 'utilidade', actions: [action('meditar', 'Meditar', 0, 'interlúdio', { limit: limit('interlude'), handler: 'meditation', fields: ['restQuality'] })] }),
  p(56, 'Ocultista', 'Ruído de Comunicação', 'Reação e 4 PE invertem um bônus ou penalidade expresso em dados de um alvo em alcance curto. A inversão dura pela cena.', { cost: '4 PE', modularGroup: 'combate', actions: [action('inverter', 'Inverter modificador em dados', 4, 'reação', { handler: 'invertDice', fields: ['diceModifier', 'recipient'] })] }),
  p(56, 'Gerais', 'Apaixonado por Veículos', 'Receba Pilotagem treinada ou +2 se já treinado. Testes para proteger o veículo recebem +1d20. Na regra de veículos operacionais, acrescente uma regalia fora do limite.', { requirement: 'AGI 2', prerequisites: attribute('agilidade', 2), grantSkills: [{ skill: 'Pilotagem', existingBonus: 2 }], modifiers: [modifier('testDice', 1, 'protectVehicle')], permanent: { extraVehiclePerks: 1 } }),
  p(56, 'Gerais', 'Desafiar o Ego', 'Uma vez por rodada, ao presenciar um ataque aliado, reação e 1 PE acrescentam PRE ao dano se acertar. Se errar, recupere o PE gasto.', { requirement: 'PRE 2', prerequisites: attribute('presenca', 2), cost: '1 PE', actions: [action('incentivo', 'Incentivar ataque', 1, 'reação', { limit: limit('turn'), handler: 'challengeEgo', fields: ['attackHit'] })] }),
  p(56, 'Gerais', 'Direção Defensiva', 'Receba Pilotagem treinada ou +2 se já treinado. Ao dirigir, todos no veículo recebem +2 Defesa e resistências; o veículo operacional também recebe +2 Defesa.', { grantSkills: [{ skill: 'Pilotagem', existingBonus: 2 }], modifiers: [modifier('defense', 2, 'driving'), modifier('resistanceTests', 2, 'driving')], allyModifiers: [modifier('defense', 2, 'sameVehicle'), modifier('resistanceTests', 2, 'sameVehicle')], permanent: { vehicleDefenseWhileDriving: 2 } }),
  p(57, 'Paranormais', 'Ácido Corrosivo', 'Por 1 PE, até o fim da cena: +2 ataque e +5 dano desarmado, com dano químico. Pode afetar uma arma corpo a corpo; ela é perdida ao fim da cena se não for amaldiçoada. Afinidade: +4 ataque e +10 dano.', { group: 'Energia', element: 'Energia', cost: '1 PE', actions: [action('acido', 'Ativar dano químico', 1, 'uso', { handler: 'corrosiveAcid', fields: ['unarmedOrWeapon'] })] }),
  p(57, 'Paranormais', 'Dead Man Switch', 'Enquanto machucado, transmita seu grau de uma perícia treinada a um alvo em alcance médio. Termina quando deixa de estar machucado ou morre. Afinidade: até três alvos e duas perícias; se morrer, os últimos alvos conservam o benefício até o fim da missão.', { group: 'Conhecimento', element: 'Conhecimento', actions: [action('transmitir', 'Transmitir treinamento', 0, 'machucado', { handler: 'deadManSwitch', fields: ['skill', 'secondSkill', 'target'] })] }),
  p(57, 'Paranormais', 'Paralinguística Ampliada', 'Receba +5 para compreender linguagens paranormais e aprenda Compreensão Paranormal; se já a conhecia, seu custo diminui em 1 PE. Afinidade: bônus +10 e efeito Discente permanente.', { group: 'Conhecimento', element: 'Conhecimento', modifiers: [modifier('testBonus', [5, 10], 'paranormalLanguage')], grantRituals: [{ name: 'Compreensão Paranormal', alreadyKnownDiscount: 1 }], affinityEffect: 'Compreensão Paranormal Discente permanente' }),
];

export const AS05_TRAILS = [
  trail(5, 58, 'Ocultista', 'Criptologista do Oculto', 10, 'Método Intuitivo', 'Receba Criar Selo. Uma segunda aquisição dobra o máximo de selos simultâneos. Produza dois por ação de interlúdio, mais um por outra habilidade desta trilha adquirida.', { grants: ['Criar Selo'], permanent: { sealsPerInterludeBase: 2, sealsPerOtherTrailAbility: 1, createSealRepeat: 2 }, actions: [action('selos', 'Produzir selos', 0, 'interlúdio', { handler: 'createSeals', fields: ['ritual'] })] }),
  trail(5, 58, 'Ocultista', 'Criptologista do Oculto', 40, 'Caligrafia Eficiente', 'Selos criados por você exigem Ocultismo DT 10 + custo em PE do ritual quando o usuário não o conhece. Receba +5 para identificar rituais.', { permanent: { sealUseDcBase: 10 }, modifiers: [modifier('Ocultismo', 5, 'identifyRitual')] }),
  trail(5, 58, 'Ocultista', 'Criptologista do Oculto', 65, 'Decifrar à Distância', 'Use um selo legível em alcance curto sem segurá-lo ou falar. Receba +5 para compreender linguagens paranormais.', { permanent: { sealReadRange: 'Curto', sealNeedsSpeech: false, sealNeedsHand: false }, modifiers: [modifier('testBonus', 5, 'paranormalLanguage')] }),
  trail(5, 58, 'Ocultista', 'Criptologista do Oculto', 99, 'Selo Supremo', 'Seus selos dispensam teste de Ocultismo, aumentam a DT em 5 e acrescentam três dados de dano do mesmo tipo. O usuário não paga o acréscimo de PE das formas Discente ou Verdadeira.', { permanent: { sealUseNoTest: true, sealDcBonus: 5, sealDamageDice: 3, sealVariantSurcharge: 0 } }),
];

export const AS05_ITEMS = [
  item(5, 60, 'Câmera Filmadora', 'Acessórios', '0', 1, 'Utensílio com +2 Investigação e Percepção. Pode iluminar um cone de 9 m ou oferecer visão no escuro pela câmera.', { modifiers: [modifier('Investigação', 2), modifier('Percepção', 2)], modes: ['filmagem', 'lanterna', 'visão no escuro'] }),
  item(5, 60, 'Faixas da Vidência', 'Paranormais', 'III', 1, 'Vestimenta de Morte: +5 Defesa e resistências contra fontes em alcance curto; −5 contra fontes além de 9 m. Também fornece +2 Intimidação.', { element: 'Morte', wearable: true, modifiers: [modifier('defense', 5, 'sourceWithin9m'), modifier('resistanceTests', 5, 'sourceWithin9m'), modifier('defense', -5, 'sourceBeyond9m'), modifier('resistanceTests', -5, 'sourceBeyond9m'), modifier('Intimidação', 2)] }),
  item(5, 60, 'Joias da Mente', 'Paranormais', 'III', 1, 'Vestimenta única formada por duas peças, ambas necessárias. Concede +2 Diplomacia e resistência mental 10.', { element: 'Conhecimento', wearable: true, requiresBothPieces: true, modifiers: [modifier('Diplomacia', 2), modifier('resistance', 10, 'always', { types: ['mental'] })] }),
  item(5, 61, 'Larva da Fúria', 'Paranormais', 'II', 1, 'Consumível paranormal de Sangue. Ação de movimento: +4 nos ataques e danos corpo a corpo pela cena; impede ações de concentração, Furtividade e rituais. Termina se uma rodada acabar sem atacar nem receber um efeito hostil.', { element: 'Sangue', actions: [action('furia', 'Ativar fúria', 0, 'movimento', { consume: 1, handler: 'rage' })] }),
  item(5, 61, 'Skate Caótico', 'Paranormais', 'II', 2, 'Equipado nos pés, concede +3 m a quem tiver Acrobacia, Atletismo ou Pilotagem treinada. Pode ser arma improvisada de duas mãos, 1d12 impacto, crítico x2, ou escudo com +5 Defesa. Modificações e maldições tratam-no apenas como proteção.', { element: 'Energia', upgradeGroup: 'Proteções', modes: ['transporte', 'arma', 'escudo'], weapon: { proficiency: 'Improvisada', handling: 'Duas mãos', damage: '1d12', damageType: 'Impacto', critical: '20/x2', range: 'Corpo a corpo' }, modifiers: [modifier('movement', 3, 'skateTransportTrained'), modifier('defense', 5, 'skateShield')] }),
  item(5, 61, 'Tênis Lépidos', 'Paranormais', 'III', 1, 'Vestimenta de Energia: +12 Atletismo e +3 m. Por 2 PE até o fim do turno, ignore terreno difícil, escale com seu deslocamento terrestre e ignore dano de queda de até 9 m.', { element: 'Energia', wearable: true, modifiers: [modifier('Atletismo', 12), modifier('movement', 3)], actions: [action('movimento', 'Mover-se sobrenaturalmente', 2, 'uso', { handler: 'swiftShoes' })] }),
];

export const AS05_TRANSMISSION = [
  p(62, 'Paranormais', 'Conexão Comunicativa', 'Comunique-se mentalmente e localize outros portadores deste poder a até 90 m. Cada outro portador no alcance concede +2 para resistir à comunicação negativa de Alheios.', { handler: 'transmissionCommunication', modifiers: [modifier('resistanceTests', '2*peers', 'alienCommunication')], radius: 90 }),
  p(62, 'Paranormais', 'Sincronia Conectiva', 'Cada participante usa reação e 3 PE. Pela cena, podem compartilhar iniciativa, informação sobre inventário e ações, PE e perdas/danos que não afetem SAN. Cada gasto e transferência deve ser registrado na ficha correspondente.', { cost: '3 PE', actions: [action('sincronizar', 'Entrar em sincronia', 3, 'reação', { handler: 'connectSynchrony', fields: ['peerCount'] }), action('transferir', 'Registrar transferência combinada', 0, 'efeito compartilhado', { handler: 'synchronyTransfer', fields: ['transferResource', 'transferAmount', 'transferDirection'] })] }),
  p(63, 'Paranormais', 'Transmissão de Perícia', 'Uma vez por cena, movimento e 2 PE copiam os valores permanentes de uma perícia de outro portador em alcance curto até o fim da cena. Bônus temporários não são copiados.', { cost: '2 PE', actions: [action('pericia', 'Receber perícia transmitida', 2, 'movimento', { handler: 'transmitSkill', limit: limit('scene'), fields: ['skill', 'peerDice', 'peerRank', 'peerBonus', 'peerCount'] })] }),
  p(63, 'Paranormais', 'Transmissão de Poder', 'Uma vez por cena, movimento e 3 PE permitem usar um poder de outro portador em alcance curto pela cena, desde que cumpra os requisitos.', { cost: '3 PE', actions: [action('poder', 'Receber poder transmitido', 3, 'movimento', { handler: 'transmitPower', limit: limit('scene'), fields: ['temporaryPower', 'peerCount'] })] }),
  p(63, 'Paranormais', 'Transmissão de Ritual', 'Uma vez por cena, movimento e 3 PE permitem conjurar um ritual de outro portador em alcance curto pela cena, desde que cumpra os requisitos.', { cost: '3 PE', actions: [action('ritual', 'Receber ritual transmitido', 3, 'movimento', { handler: 'transmitRitual', limit: limit('scene'), fields: ['ritual', 'peerCount'] })] }),
].map(entry => ({ ...entry, group: 'Transmissão', requirement: 'Conexão com o Sino de Transmissão; ao menos dois seres com o mesmo poder para funcionar', mechanics: { ...entry.mechanics, element: 'Transmissão', elements: ['Conhecimento', 'Energia'], prerequisites: { story: 'transmissionBell' }, minimumParticipants: 2 } }));
