import { power, origin, ritual, item, all, any, attribute, skill, ability, action, modifier, limit } from './schema.js';
// The supplied AS06 file identifies itself as v1.1; its errata supersedes v1.0.
const p = (page, category, name, text, rules) => power(6, page, category, name, text, rules);
export const AS06_ORIGINS = [
  origin(6, 66, 'Cientista Ex-Panacea', ['Atualidades', 'Ciências'], 'Existe uma Explicação', 'Por 2 PE, faça Ciências no lugar de um teste de Ocultismo.', { cost: '2 PE', actions: [action('explicacao', 'Usar Ciências', 2, 'teste', { handler: 'replaceSkill', from: 'Ocultismo', to: 'Ciências' })] }),
  origin(6, 66, 'Cobaia Sobrevivente', ['Fortitude', 'Vontade'], 'Forças para Enfrentar', 'Um gatilho de histórico definido pelo mestre causa abalado. Por 2 PE, fique imune a medo pela cena, inclusive a essa condição.', { cost: '2 PE', actions: [action('gatilho', 'Registrar gatilho do histórico', 0, 'gatilho', { selfConditions: ['abalado'], duration: 'scene' }), action('enfrentar', 'Enfrentar o medo', 2, 'uso', { handler: 'faceFear' })] }),
  origin(6, 66, 'Segurança Ex-Panacea', ['Luta', 'Pontaria'], 'Técnicas de Contenção', 'Por 2 PE, receba +5 num teste de manobra de combate.', { cost: '2 PE', actions: [action('manobra', 'Aprimorar manobra', 2, 'teste', { modifiers: [modifier('maneuver', 5)], duration: 'nextTest' })] }),
];
export const AS06_POWERS = [
  p(67, 'Combatente', 'Análise Combativa', 'Acrescente +5 ao teste de Ciente das Cicatrizes. Depois de investigar com sucesso a ameaça, receba +2 nos testes contra ela.', { requirement: 'Ciente das Cicatrizes', prerequisites: ability('Ciente das Cicatrizes'), modularGroup: 'utilidade', modifiers: [modifier('testBonus', 5, 'cienteDasCicatrizes')], actions: [action('investigar', 'Registrar investigação bem-sucedida', 0, 'teste bem-sucedido', { handler: 'combatAnalysis', fields: ['target'] })] }),
  p(67, 'Combatente', 'Especialista em Proteção Leve', 'Enquanto usar proteção leve, receba +2 Defesa e Reflexos.', { modularGroup: 'combate', modifiers: [modifier('defense', 2, 'lightArmor'), modifier('Reflexos', 2, 'lightArmor')] }),
  p(68, 'Especialista', 'Doutor em Emergências', 'Seus medicamentos que curam ou concedem PV temporários recebem mais 1d8. Tratamento recebe +5 Medicina e concede +10, em vez de +5, ao próximo teste do paciente contra veneno ou doença.', { requirement: 'Especialista em Emergências', prerequisites: ability('Especialista em Emergências'), modularGroup: 'utilidade', permanent: { medicineHealingExtra: '1d8', medicineTemporaryHpExtra: '1d8', treatmentResistanceBonus: 10 }, modifiers: [modifier('Medicina', 5, 'treatment')] }),
  p(68, 'Especialista', 'Farmacêutico de Campo', 'No interlúdio, gaste 2 PE + 2 por categoria para produzir cicatrizante ou medicamento. Requer kit de medicina, consumido a cada três produções. A primeira produção do interlúdio não gasta ação; cada seguinte gasta uma.', { requirement: 'Medicina e Profissão (químico ou equivalente) treinadas', prerequisites: all(skill('Medicina'), { profession: 'Químico', rank: 5 }), modularGroup: 'utilidade', cost: '2 PE ou mais', actions: [action('produzir', 'Produzir medicamento', 2, 'interlúdio', { handler: 'fieldPharmacist', fields: ['createdItem', 'medicineKit'] })] }),
  p(68, 'Especialista', 'Médico da Salvação', 'Os dados d10 de cura de Paramédico tornam-se d12. Uma vez por rodada, gaste 3 PE adicionais para usar Paramédico como ação de movimento.', { requirement: 'Paramédico', prerequisites: ability('Paramédico'), modularGroup: 'utilidade', permanent: { paramedicDie: 12 }, cost: '+3 PE', actions: [action('paramedico', 'Paramédico como movimento', 3, 'movimento', { handler: 'fastParamedic', limit: limit('turn'), fields: ['baseCost', 'healingDice', 'recipient'] })] }),
  p(68, 'Especialista', 'Resgatar da Morte', 'Por 2 PE, obtenha sucesso automático em primeiros socorros. Uma vez por alvo em cada cena.', { requirement: 'Veterano em Medicina', prerequisites: skill('Medicina', 10), modularGroup: 'utilidade', cost: '2 PE', actions: [action('socorros', 'Primeiros socorros automáticos', 2, 'primeiros socorros', { limit: limit('scene', 1, true), fields: ['target'], handler: 'firstAid' })] }),
  p(68, 'Especialista', 'Veterano da Equipe de Trauma', 'Equipe de Trauma remove três condições, em vez de uma. Não remove morrendo.', { requirement: 'Paramédico e Equipe de Trauma', prerequisites: all(ability('Paramédico'), ability('Equipe de Trauma')), modularGroup: 'utilidade', permanent: { traumaConditions: 3, traumaExcludes: ['morrendo'] } }),
  p(69, 'Ocultista', 'Barreira do Oculto', 'Depois de conjurar um ritual do elemento escolhido, pode gastar PE até o limite por turno. Cada PE concede +2 Defesa por uma rodada.', { requirement: 'NEX 30% e Especialista em Elemento do mesmo elemento', unlockNex: 30, prerequisites: all({ nex: 30 }, ability('Especialista em Elemento')), modularGroup: 'combate', choices: [{ type: 'elemento', source: 'specialistElements', count: 1 }], actions: [action('barreira', 'Criar barreira', 0, 'após ritual do elemento', { handler: 'occultBarrier', fields: ['effort', 'ritual'] })] }),
  p(69, 'Ocultista', 'Grão-Mestre em Elemento', 'Ao conjurar um ritual do elemento escolhido, +1 PE aplica um efeito extra a um alvo. Sangue: aliado +2d4 Sangue no dano pela cena ou inimigo debilitado por uma rodada. Morte: aliado 3d8+3 PV temporários ou inimigo enjoado por uma rodada. Conhecimento: aliado +2 em perícias pela cena ou inimigo esmorecido por uma rodada. Energia: aliado +6 m em todos os deslocamentos pela cena ou inimigo desprevenido por uma rodada. Ignora imunidade a essas condições.', { requirement: 'NEX 60% e Mestre em Elemento do mesmo elemento', unlockNex: 60, prerequisites: all({ nex: 60 }, ability('Mestre em Elemento')), modularGroup: 'combate', choices: [{ type: 'elemento', source: 'masterElements', count: 1 }], actions: [action('grao-mestre', 'Aplicar efeito adicional', 1, 'ao conjurar', { handler: 'grandmasterElement', fields: ['ritual', 'recipient', 'friendly'] })] }),
  p(70, 'Gerais', 'Adaptação Climática', 'Receba +2 Fortitude e imunidade aos efeitos de calor e frio do clima. Não abrange ataques ou rituais.', { requirement: 'VIG 2', prerequisites: attribute('vigor', 2), modifiers: [modifier('Fortitude', 2)], immunities: ['climaticHeat', 'climaticCold'] }),
  p(70, 'Gerais', 'Especialista em Armas Improvisadas', 'Elimine a penalidade de ataque com armas improvisadas e acrescente um dado do mesmo tipo ao dano.', { requirement: '(FOR 2 ou AGI 2) e Luta treinada', prerequisites: all(any(attribute('forca', 2), attribute('agilidade', 2)), skill('Luta')), permanent: { improvisedAttackPenalty: 0, improvisedDamageDice: 1 } }),
  p(70, 'Gerais', 'Muito Sorrateiro', 'Acrescente +3 Furtividade e reduza sua visibilidade inicial em 1d4.', { requirement: 'Sorrateiro', prerequisites: ability('Sorrateiro'), modifiers: [modifier('Furtividade', 3)], actions: [action('visibilidade', 'Reduzir visibilidade inicial', 0, 'início da furtividade', { handler: 'initialVisibility', dice: '1d4' })] }),
  p(71, 'Paranormais', 'Escudo Espiral Temporal', 'Uma vez por rodada, reação e 2 PE concedem RD 20 contra munição ou RD 10 contra arma corpo a corpo; neste caso a arma recebe 10 de dano químico. Não protege de dano de Energia. Afinidade: sem limite por rodada e 20 de dano à arma.', { group: 'Morte', element: 'Morte', requirement: 'Morte 2', prerequisites: { elementPowers: 'Morte', minimum: 2 }, cost: '2 PE', actions: [action('escudo', 'Ativar escudo temporal', 2, 'reação', { handler: 'temporalShield', limit: limit('turn'), affinityUnlimited: true, fields: ['attackKind', 'damageType'] })] }),
  p(71, 'Paranormais', 'Grilhões de Lodo', 'Por 2 PE, crie uma área de 9 m centrada em você pela cena. Você e criaturas de Morte são isentos. Os demais sofrem 3d6 Morte e lento por uma rodada; Fortitude DT do maior atributo reduz o dano à metade e evita a condição. Afinidade: 6d6 e enredado.', { group: 'Morte', element: 'Morte', cost: '2 PE', actions: [action('grilhoes', 'Criar área de lodo', 2, 'uso', { handler: 'sludgeArea', radius: 9, save: 'Fortitude', dcAttribute: 'highest', duration: 'scene' })] }),
  p(71, 'Paranormais', 'Salto de Dados', 'Ação completa e 2 PE registram seu estado por um dia. Uma reação de 3 PE restaura esse estado e consome a marca; você fica alquebrado e frustrado pela cena, e pasmo por 1d4+1 rodadas. Só pode haver uma marca. Afinidade: marca válida por um ano.', { group: 'Energia', element: 'Energia', requirement: 'Energia 2', prerequisites: { elementPowers: 'Energia', minimum: 2 }, actions: [action('marcar', 'Marcar estado da ficha', 2, 'completa', { handler: 'markSnapshot' }), action('retornar', 'Retornar ao estado marcado', 3, 'reação', { handler: 'restoreSnapshot' })] }),
];
export const AS06_RITUALS = [ritual(6, 72, 'Hesitação Forçada', 'Conhecimento', 1, 'Alcance curto, uma pessoa, sustentado. No início de cada turno, o alvo testa Vontade; se falhar, rerrola e aceita o maior d20 de cada teste. Dois sucessos consecutivos encerram o efeito.', [
  { name: 'Discente', extra: 2, minCircle: 2, summary: 'Pode afetar qualquer ser. Além do efeito normal, uma falha impede ações hostis contra o conjurador.' },
  { name: 'Verdadeiro', extra: 5, minCircle: 3, affinity: true, summary: 'Vontade anula. Rerrola e aceita o menor d20; intercepta involuntariamente ataques contra aliados adjacentes. Testa novamente no começo de seu turno.' },
], { activation: 'padrão', range: 'Curto', target: '1 pessoa', duration: 'sustained', save: 'Vontade', handler: 'forcedHesitation', consecutiveSavesToEnd: 2 })];
export const AS06_ITEMS = [
  item(6, 73, 'Anel Invertido', 'Paranormais', 'II', 0.5, 'Vestimenta de Morte: reação e 2 PE concedem 4d10 de redução contra dano de um Nidére.', { element: 'Morte', wearable: true, actions: [action('proteger', 'Proteger-se de Nidére', 2, 'reação', { handler: 'invertedRing', fields: ['nidereSource'] })] }),
  item(6, 73, 'Aplicador de Adrenalina', 'Operacionais', 'I', 1, 'Medicamento de jogo consumível. Ação padrão em você ou alvo adjacente: 2d8+2 PV temporários, +3 m e +2 testes de FOR, AGI e VIG pela cena. Depois, fatigado por uma cena.', { medicine: true, actions: [action('aplicar', 'Aplicar efeito do medicamento', 0, 'padrão', { consume: 1, handler: 'adrenaline', fields: ['recipient'] })] }),
  item(6, 73, 'Lança-Nitrogênio', 'Armas', 'III', 2, 'Arma de fogo pesada de duas mãos: 6d6 frio, crítico 20/x2, alcance curto. Um ataque afeta as Defesas na linha de 1,5 m por 9 m. Acerto causa enredado; Fortitude DT AGI reduz para lento. Uma ação padrão encerra a condição. Usa combustível de nitrogênio.', { weapon: { proficiency: 'Pesada', handling: 'Fogo · duas mãos', damage: '6d6', damageType: 'Frio', critical: '20/x2', range: 'Curto' }, ammoVariant: 'Nitrogênio', area: { shape: 'line', width: 1.5, length: 9 }, save: 'Fortitude', dcAttribute: 'agilidade', conditions: ['enredado'], successConditions: ['lento'], removal: 'padrão' }),
];
export const AS06_UPGRADES = [
  { name: 'Emulsificante Químico', summary: 'Acrescente o efeito de outro medicamento não amaldiçoado, diferente e de categoria igual ou menor.', mechanics: { choice: 'otherNonCursedMedicine', maximumCategory: 'base' } },
  { name: 'Potencializador Químico', summary: 'Escolha uma melhoria aplicável: +5 ao bônus de teste, +2d8 PV temporários, +2d8 cura ou dois usos por cena no lugar de um.', mechanics: { choice: 'medicineBoost', alternatives: ['testBonus', 'temporaryHp', 'healing', 'sceneLimit'], values: [5, '2d8', '2d8', 2] } },
  { name: 'Aceleração Espiral', curse: true, element: 'Morte', summary: 'Gaste 3 PE adicionais para obter uma ação padrão extra, exceto para rituais, válida até ser usada ou acabar a cena. Fortitude DT 20; falha perde 2d8 PV.', mechanics: { actions: [action('acelerar', 'Ativar aceleração', 3, 'uso do medicamento', { handler: 'spiralAcceleration', fields: ['fortitudeResult'] })] } },
  { name: 'Esforço Espiral', curse: true, element: 'Morte', summary: 'Acrescente 1d8+1 à recuperação de PE do medicamento. Fortitude DT 20; falha envelhece um ano e fica frustrado pela cena.', mechanics: { effortRecoveryExtra: '1d8+1', actions: [action('esforco', 'Resolver efeito espiral', 0, 'uso do medicamento', { handler: 'spiralEffort', fields: ['fortitudeResult'] })] } },
].map((u, index) => ({ ...u, id: `as6-medicamento-${index + 1}`, target: 'Medicamentos', source: 'Arquivos Secretos #6', sourcePage: 74, page: '74', curse: Boolean(u.curse), spaces: 0, categoryIncrease: 1 }));
// Fictional game conditions only; no medical or chemical instructions.
export const AS06_DISEASES = [
  ['alergica', 'Crise Alérgica', 'Fortitude', 20, [{ modifiers: [modifier('allTests', -2)] }, { modifiers: [modifier('allTests', -5)] }, { modifiers: [modifier('allTests', -5)], conditions: ['enjoado'] }, { modifiers: [modifier('allTests', -5)], conditions: ['enjoado', 'asfixiado'] }]],
  ['hipertensiva', 'Crise Hipertensiva', 'Vontade', 20, [{ conditions: ['trêmulo'] }, { conditions: ['trêmulo', 'abalado'] }, { conditions: ['trêmulo', 'abalado', 'enjoado'] }, { terminal: true }]],
  ['hipocondriaca', 'Crise Hipocondríaca', null, null, [{ conditions: ['abalado'] }, { conditions: ['abalado', 'confuso'] }, { conditions: ['abalado', 'confuso'], hpLoss: '2d12', medicineBenefit: false, depleteMedicines: true }, { terminal: true }]],
  ['cerebral', 'Infecção Cerebral', 'Fortitude', 20, [{ conditions: ['frustrado'] }, { conditions: ['esmorecido'] }, { conditions: ['esmorecido'], attributeOverride: { intelecto: 0 }, communication: false }, { terminal: true }]],
  ['generalizada', 'Infecção Generalizada', 'Fortitude', 20, [{ conditions: ['fatigado'] }, { conditions: ['exausto'] }, { conditions: ['exausto', 'inconsciente'] }, { terminal: true }]],
].map(([id, name, save, dc, stages]) => ({ id: `as6-doenca-${id}`, name, source: 'Arquivos Secretos #6', sourcePage: 75, save, dc, stages }));
export const AS06_POISONS = [
  ['batracotoxina', 'Batracotoxina', 'contato', { conditions: ['exausto', 'paralisado', 'asfixiado'] }, { conditions: ['exausto'] }],
  ['cianeto', 'Cianeto de Potássio', 'ingestão', { conditions: ['inconsciente', 'asfixiado'] }, { conditions: ['asfixiado'] }],
  ['gas', 'Gás Neurotóxico', 'inalação', { conditions: ['paralisado'] }, { conditions: ['imóvel'] }],
  ['ricina', 'Ricina', 'inalação', { hpLoss: '4d6', interval: 'round', duration: 'untilCured' }, { hpLoss: '2d6', interval: 'round', rounds: '1d4+1' }],
  ['cardiotoxica', 'Toxina Cardiotóxica', 'ferimento', { hpSet: 0, conditions: ['morrendo'] }, { hpLossFraction: 0.5 }],
].map(([id, name, exposure, failure, success]) => ({ id: `as6-veneno-${id}`, name, source: 'Arquivos Secretos #6', sourcePage: 76, exposure, save: 'Fortitude', dc: 25, category: 'III', failure, success }));
