import { origin, trail, ritual, item, action, modifier, limit } from './schema.js';
export const AS07_ORIGINS = [
  origin(7, 80, 'Exorcizado', ['Fortitude', 'Ocultismo'], 'O Que Restou', 'Escolha Sangue, Morte, Conhecimento ou Energia: receba RD 5 desse elemento. O primeiro contato com ele a cada cena causa perda de 2 SAN.', { choices: [{ type: 'elemento', source: 'elements', count: 1 }], modifiers: [modifier('resistance', 5, 'chosenElement')], actions: [action('contato', 'Registrar primeiro contato na cena', 0, 'contato com o elemento', { handler: 'exorcisedContact', limit: limit('scene') })] }),
  origin(7, 80, 'Sensitivo Rebelde', ['Intuição', 'Vontade'], 'Sussurros e Vultos', 'Gaste 2 SAN para receber +5 num teste de Diplomacia, Enganação, Intimidação ou Intuição.', { cost: '2 SAN', actions: [action('sussurros', 'Aprimorar teste', 0, 'teste', { handler: 'sensitiveWhispers', fields: ['socialSkill'], additionalCosts: [{ resource: 'san', amount: 2 }] })] }),
];
export const AS07_RITUALS = [ritual(7, 76, 'Vampirismo', 'Sangue', 2, 'Ação completa, toque, uma pessoa, duração de cena. O vínculo requer um minuto e permite uma escolha por categoria sensorial do alvo: visão +5 ataque; audição aprende um ritual conhecido de 1º círculo; paladar recupera 2d8+2 PV; olfato +5 para rastrear um ser relacionado; tato concede uma perícia treinada do alvo, ou +2 se já treinada. Os benefícios terminam com a cena.', [
  { name: 'Discente', extra: 5, minCircle: 3, summary: 'Os bônus de ataque e rastreio passam a +10; aprende ritual de até 2º círculo, recupera 3d8+3 PV ou recebe grau veterano numa perícia do alvo, ou +2 se já veterano.' },
  { name: 'Verdadeiro', extra: 10, minCircle: 4, affinity: true, summary: 'Os bônus de ataque e rastreio passam a +15; aprende ritual de até 3º círculo, recupera 4d8+4 PV ou recebe grau expert numa perícia do alvo, ou +2 se já expert.' },
], { activation: 'completa', range: 'Toque', target: '1 pessoa', duration: 'scene', linkMinutes: 1, handler: 'vampirism', sourcePages: [76, 77], usesPerTargetCategory: 1, choices: ['visão', 'audição', 'paladar', 'olfato', 'tato'] })];
export const AS07_ITEMS = [
  item(7, 78, 'Carranca Caçadora', 'Paranormais', 'II', 2, 'Um vínculo material permite rastrear uma criatura por dez minutos, seguindo a rota mais perigosa. Se ela desapareceu, aponta o último local conhecido. Consome o vínculo; só pode rastrear cada criatura uma vez.', { actions: [action('rastrear', 'Rastrear criatura', 0, 'ativação', { handler: 'trackingFigure', limit: limit('ever', 1, true), fields: ['target', 'materialLink'], durationMinutes: 10 })] }),
  item(7, 78, 'Cajado da Cruz de Sangue', 'Paranormais', 'III', 2, 'Arma simples ágil, duas mãos, 1d12 corte, crítico 20/x2. Com duas armas, conta como uma de uma mão e uma leve. Um ocultista que conheça ritual de Sangue reduz em 1 PE os custos de seus poderes e rituais de Sangue, aumenta suas DTs em 1 e acrescenta um dado do mesmo tipo ao dano.', { element: 'Sangue', weapon: { proficiency: 'Simples', agile: true, handling: 'Duas mãos', damage: '1d12', damageType: 'Corte', critical: '20/x2', range: 'Corpo a corpo', double: true }, permanent: { bloodOccultistDiscount: 1, bloodOccultistDc: 1, bloodOccultistDamageDice: 1 } }),
  item(7, 79, 'Pé de Coelho', 'Paranormais', 'I', 1, 'Vestimenta. Uma vez por cena, ação de movimento concede +1d4 em todos os testes pela cena. Cada resultado ímpar nesse dado causa perda de 1d4 PV.', { wearable: true, actions: [action('sorte', 'Ativar sorte', 0, 'movimento', { handler: 'rabbitLuck', limit: limit('scene') }), action('teste', 'Rolar bônus da sorte', 0, 'teste', { handler: 'rabbitLuckRoll' })] }),
  item(7, 79, 'Sal Dourado', 'Paranormais', 'I', 1, 'Três cargas. Uma linha gasta uma carga; um círculo gasta três. Criaturas de Sangue de VD até 80 precisam passar em Vontade DT 20 para cruzar. A tentativa, com sucesso ou falha, causa frustrado pela cena.', { charges: 3, actions: [action('linha', 'Criar linha', 0, 'uso', { handler: 'goldenSalt', charges: 1 }), action('circulo', 'Criar círculo', 0, 'uso', { handler: 'goldenSalt', charges: 3 })], barrier: { element: 'Sangue', maxVd: 80, save: 'Vontade', dc: 20, condition: 'frustrado', duration: 'scene' } }),
  item(7, 79, 'Terço Maculado', 'Paranormais', 'II', 1, 'Vestimenta de Sangue vinculada a uma súplica aprovada pelo mestre. Acrescente +2d10 a testes que a favoreçam. Contrariá-la ou tentar remover o item causa perda de 2d10 PV. Cumprir a súplica torna o item mundano; outra liberação depende do mestre.', { element: 'Sangue', wearable: true, binding: true, actions: [action('vincular', 'Registrar súplica', 0, 'primeiro uso', { handler: 'rosaryBind', requiresApproval: true, fields: ['plea'] }), action('teste', 'Usar bônus da súplica', 0, 'teste relacionado', { handler: 'rosaryBonus' }), action('contrariar', 'Registrar efeito adverso', 0, 'quebra do vínculo', { handler: 'rosaryPenalty' }), action('concluir', 'Registrar súplica cumprida', 0, 'conclusão', { handler: 'rosaryComplete', requiresApproval: true })] }),
];
const elements = ['Sangue', 'Morte', 'Conhecimento', 'Energia'];
const attributes = ['forca', 'vigor', 'intelecto', 'agilidade'];
const shared = { monstrousVariant: true, exposureProgression: true, exposureMultiplierWhenSeparate: 2, affinityLockedToElement: true };
const daily = (healing, resource) => action('ativacao', 'Registrar ativação diária', 0, 'completa', { handler: 'monstrousDaily', limit: limit('day'), fields: ['componentAvailable'], healing, resource });
// These are class-specific variants. They do not replace SaH's Combatente trail.
export const AS07_TRAILS = [
  trail(7, 81, 'Especialista', 'Monstruoso', 10, 'Ser Experimentado', 'Receba Ocultismo treinado ou +2 se já treinado. Escolha um elemento; a ativação diária recupera 1d8+1 PV. Sangue: Grande, +2 manobras, −2 Furtividade; Morte: 2d6 PV temporários e uma ação padrão extra por cena; Conhecimento: duas perícias treinadas; Energia: saque livre uma vez por rodada e +6 m em todos os deslocamentos. Use FOR/VIG/INT/AGI, respectivamente, no cálculo de PE e acrescente o mesmo atributo aos testes baseados nele. Diplomacia, Enganação e Intuição −2.', {
    ...shared, choices: [{ type: 'elemento', source: 'elements', count: 1 }, { type: 'pericia', source: 'skills', count: 2, whenElement: 'Conhecimento' }], grantSkills: [{ skill: 'Ocultismo', existingBonus: 2 }], permanent: { socialPenalty: -2, effortAttributeByElement: attributes, chosenAttributeTestBonus: true },
    elementEffects: { Sangue: { size: 'Grande', maneuver: 2, Furtividade: -2 }, Morte: { dailyTemporaryHp: '2d6', extraStandardActionsPerScene: 1 }, Conhecimento: { skills: 2, rank: 5 }, Energia: { freeDrawsPerTurn: 1, allMovement: 6 } },
    actions: [daily('1d8+1', 'pv'), action('acao', 'Usar ação padrão de Morte', 0, 'livre', { handler: 'monstrousStandard', element: 'Morte', limit: limit('scene') })],
  }),
  trail(7, 82, 'Especialista', 'Monstruoso', 40, 'Ser Testado', 'A ativação diária recupera 2d8+2 PV. Diplomacia, Enganação e Intuição −5. Sangue: +1d6 Sangue no dano e RD 2; Morte: mais um turno em morrendo e 2d8 PV temporários no início da cena; Conhecimento: +1d6 nos testes de INT; Energia: +1d6 nos ataques e +2 Defesa. Pode ampliar cada benefício sacrificando pontos de INT/FOR/AGI/VIG, respectivamente. Essa redução não altera máximos de recursos nem quantidade de perícias e não aceita atributos temporários.', {
    ...shared, permanent: { socialPenalty: -5 }, tradeAttributesByElement: ['intelecto', 'forca', 'agilidade', 'vigor'], excludesTradeFromDerived: true,
    elementEffects: { Sangue: { damagePerUnit: '1d6', resistancePerUnit: 2 }, Morte: { dyingTurnsPerUnit: 1, sceneTemporaryHpPerUnit: '2d8' }, Conhecimento: { intellectTestsPerUnit: '1d6' }, Energia: { attackPerUnit: '1d6', defensePerUnit: 2 } },
    actions: [daily('2d8+2', 'pv'), action('trocar', 'Registrar troca de atributo', 0, 'escolha do benefício', { handler: 'monstrousTrade', fields: ['attributePoints'] }), action('cena', 'Receber PV temporários de Morte', 0, 'início da cena', { handler: 'monstrousSceneHp', element: 'Morte', limit: limit('scene') })],
  }),
  trail(7, 83, 'Especialista', 'Monstruoso', 65, 'Ser Expurgado', 'A ativação diária recupera 3d8+3 PV. PRE −1 e −1d20 nos testes sociais da trilha. Aumente em 1 o atributo do elemento. Sangue: +1d8 nos ataques corpo a corpo e dados de Ser Testado tornam-se d8; depois de atacar com outra arma, 1 PE dá ataque desarmado extra uma vez por rodada. Morte: primeiro toque num objeto, 3 PE, causa 50 Morte ou revela um minuto de seu último dono. Conhecimento: ação completa e 3 PE dão Detecção de Ameaças Discente pessoal pela cena ou Mergulho Mental de toque por três rodadas sem resistência ou sustentação. Energia: movimento e 2 PE tornam os braços incorpóreos pela cena; uso criativo pode conceder +5 em testes. No interlúdio, pode fixar um item de uma mão.', {
    ...shared, sourcePages: [83, 84], permanent: { socialPenalty: -5, socialDicePenalty: -1, presencePenalty: -1, elementAttributeBonus: 1 },
    elementEffects: { Sangue: { meleeAttack: '1d8', testedDamageDie: 8 }, Morte: { objectDamage: 50 }, Conhecimento: { grantedEffects: ['Detecção de Ameaças Discente', 'Mergulho Mental'] }, Energia: { incorporealTestBonus: 5 } },
    actions: [daily('3d8+3', 'pv'), action('desarmado', 'Ataque desarmado adicional', 1, 'após outro ataque', { element: 'Sangue', limit: limit('turn'), handler: 'extraUnarmed' }), action('objeto', 'Aplicar toque de Morte', 3, 'primeiro toque', { element: 'Morte', handler: 'monstrousObject', fields: ['target', 'objectEffect', 'opposedTouchSuccess'] }), action('mente', 'Aplicar efeito de Conhecimento', 3, 'completa', { element: 'Conhecimento', handler: 'monstrousMind', fields: ['recipient', 'opposedTouchSuccess'] }), action('bracos', 'Ativar incorporeidade', 2, 'movimento', { element: 'Energia', handler: 'incorporealArms' }), action('fixar', 'Fixar item de uma mão', 0, 'interlúdio', { element: 'Energia', handler: 'attachItem', fields: ['inventoryItem'] })],
  }),
  trail(7, 84, 'Especialista', 'Monstruoso', 99, 'Ser Apavorante', 'A ativação diária recupera 4d8+4 PV. PRE total −2 e −2d20 nos testes sociais da trilha. Mais +1 no atributo do elemento. Sangue: Enorme, +5 manobras, −5 Furtividade, aprende Vínculo de Sangue. Morte: 4d6 PV temporários e duas ações padrão extras por cena, aprende Distorção Temporal. Conhecimento: três perícias expert, aprende Controle Mental. Energia: saque livre três vezes por rodada e +12 m em todos os deslocamentos, aprende Teletransporte.', {
    ...shared, permanent: { socialPenalty: -5, socialDicePenalty: -2, presencePenalty: -2, elementAttributeBonus: 2 }, choices: [{ type: 'pericia', source: 'skills', count: 3, whenElement: 'Conhecimento' }],
    elementEffects: { Sangue: { size: 'Enorme', maneuver: 5, Furtividade: -5, ritual: 'Vínculo de Sangue' }, Morte: { dailyTemporaryHp: '4d6', extraStandardActionsPerScene: 2, ritual: 'Distorção Temporal' }, Conhecimento: { skills: 3, rank: 15, ritual: 'Controle Mental' }, Energia: { freeDrawsPerTurn: 3, allMovement: 12, ritual: 'Teletransporte' } },
    actions: [daily('4d8+4', 'pv'), action('acao', 'Usar ação padrão de Morte', 0, 'livre', { handler: 'monstrousStandard', element: 'Morte', limit: limit('scene', 2) })],
  }),
  trail(7, 85, 'Ocultista', 'Monstruoso', 10, 'Ser Escarificado', 'Receba +2 Ocultismo e escolha um elemento. A ativação diária recupera 1d4 PE. Sangue/Morte/Conhecimento/Energia aumentam FOR/VIG/INT/AGI em 1, respectivamente; use esse atributo no PE e na DT de rituais. Diplomacia, Enganação e Intuição −2.', { ...shared, choices: [{ type: 'elemento', source: 'elements', count: 1 }], modifiers: [modifier('Ocultismo', 2)], permanent: { socialPenalty: -2, elementAttributeBonus: 1, effortAttributeByElement: attributes, ritualDcAttributeByElement: attributes }, actions: [daily('1d4', 'effort')] }),
  trail(7, 86, 'Ocultista', 'Monstruoso', 40, 'Ser Perfurado', 'A ativação diária recupera 1d6 PE. Diplomacia, Enganação e Intuição −5. Receba Tatuagem Ritualística, estendida aos rituais marcados do próprio elemento; +5 em concentração nesses rituais. Uma vez por cena, pode conjurar um deles como reação ao gatilho do elemento: Sangue, machucado ou fadiga; Morte, morrendo ou condição sensorial; Conhecimento, condição mental ou de medo; Energia, paralisia ou condição sensorial.', { ...shared, grants: ['Tatuagem Ritualística'], permanent: { socialPenalty: -5, markedOwnRitualDiscount: 1, markedConcentrationBonus: 5 }, actions: [daily('1d6', 'effort'), action('marcar', 'Registrar ritual marcado', 0, 'registro', { handler: 'markRitual', fields: ['ritual'] }), action('reacao', 'Conjurar ritual marcado como reação', 0, 'reação ao gatilho', { handler: 'markedReaction', limit: limit('scene'), fields: ['ritual', 'variant', 'trigger'] })] }),
  trail(7, 87, 'Ocultista', 'Monstruoso', 65, 'Ser Rasgado', 'A ativação diária recupera 1d8 PE. PRE −1, −1d20 nos testes sociais da trilha; rituais marcados do elemento recebem +2 DT. Depois de ritual do elemento: Sangue, movimento e 2d8+2 PV concedem a um aliado adjacente voluntário +1d20 em FOR/AGI/VIG pela cena; Morte, conjura Cicatrização como movimento após outro ritual de Morte; Conhecimento, movimento e 2 PE fazem cinco perguntas ao alvo ou revelam seres paranormais ocultos ao próprio usuário; Energia, movimento e 3 PE teleportam 3 m e dão Defesa igual ao PE do ritual por uma rodada. Morte também aprende Cicatrização ou reduz seu custo em 1 se já conhecida.', {
    ...shared, permanent: { socialPenalty: -5, socialDicePenalty: -1, presencePenalty: -1, markedRitualDcBonus: 2 }, grantRituals: [{ name: 'Cicatrização', element: 'Morte', alreadyKnownDiscount: 1 }],
    actions: [daily('1d8', 'effort'), action('sangue', 'Conceder benefício ao aliado', 0, 'movimento após ritual', { element: 'Sangue', handler: 'monstrousBloodAlly', additionalCosts: [{ resource: 'pv', dice: '2d8+2' }], fields: ['target', 'friendly', 'ritual'] }), action('morte', 'Conjurar Cicatrização como movimento', 0, 'movimento após outro ritual de Morte', { element: 'Morte', handler: 'monstrousHealing', fields: ['variant', 'previousRitual'] }), action('conhecimento', 'Aplicar efeito de Conhecimento', 2, 'movimento após ritual', { element: 'Conhecimento', handler: 'monstrousQuestions', fields: ['recipient', 'ritual'] }), action('energia', 'Teleportar após ritual', 3, 'movimento após ritual', { element: 'Energia', handler: 'monstrousTeleport', fields: ['ritualCost', 'ritual'] })],
  }),
  trail(7, 88, 'Ocultista', 'Monstruoso', 99, 'Ser Mutilado', 'A ativação diária recupera 1d12 PE. PRE total −2, −2d20 nos testes sociais da trilha e mais +1 no atributo do elemento. Rituais marcados desse elemento dispensam gestos, fala e componentes. Aprenda um ritual de 4º círculo do elemento e outro de Medo, que recebe os benefícios da trilha como se fosse do seu elemento.', { ...shared, permanent: { socialPenalty: -5, socialDicePenalty: -2, presencePenalty: -2, elementAttributeBonus: 2, markedRitualNeedsGesture: false, markedRitualNeedsSpeech: false, markedRitualNeedsComponents: false }, choices: [{ type: 'ritual', source: 'ownElementCircle4', count: 1 }, { type: 'ritual', source: 'fearCircle4', count: 1 }], actions: [daily('1d12', 'effort')] }),
];
export const AS07_ELEMENTS = elements;
